### ISSUE TITLE
Expected bot response "" to match one of ""

### ISSUE THREAD

**Issue by ptedeschi** [codeforequity-at/botium-core#102]
When botium-cli tries to match an empty property from json data in convos, it fails:
>  Expected bot response "" to match one of ""

It happens when a bot shows only cards and carrousels but no text.
Ex.: 

<pre>
...
...
"from": {
    "id": "mybot-channel-reg",
    "name": "mybot"
  },
  "conversation": {
    "id": "(.*?)"
  },
  <b>"text":""</b>,
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
...
...
</pre>

Tested with the following config file:
<pre>
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "mybot",
      "CONTAINERMODE": "directline3",
      "SCRIPTING_MATCHING_MODE": "regexp",
      "DIRECTLINE3_SECRET": "mysecret",
      "DIRECTLINE3_WEBSOCKET": true,
      "DIRECTLINE3_POLLINGINTERVAL": 1000
    }
  }
}
</pre>

**Comment by DipaliK9** [comment]
I am also facing the same issue. However, I think it is not about convo file. Bot Response is not getting captured. Bot response says undefined, if it consists of button or image.

**Comment by codeforequity-at** [comment]
The best way to get forward on this is to enable debug mode (see https://github.com/codeforequity-at/botium-core/wiki/Troubleshooting) to actually see the traffic happening between Botium and your Bot. Can you please do this and attach the log output here.

**Comment by DipaliK9** [comment]
[Log1.txt](https://github.com/codeforequity-at/botium-core/files/2419703/Log1.txt)
I have attached log file. Please let me know if you need anything else.

**Comment by codeforequity-at** [comment]
I deleted your post with the logfile above, as the attached file contained your facebook password.

**Comment by DipaliK9** [comment]
Thank you so much.. I really appreciate it. I mistakenly missed to delete it.

**Comment by codeforequity-at** [comment]
this has been fixed with the latest build.
