### ISSUE TITLE
Dialog flow Output Context always displaying as null value in WaitBotSays(console.log)

### ISSUE THREAD

**Issue by Arun-wws** [codeforequity-at/botium-core#103]
I'm doing Console.log with WaitBotSays(console.log) while testing with Google dialog-flow.

I have defined valid Output contexts for all my Intents which display correctly in Simulator.
But in WaitBotSays, 
I'm getting the full-filment text value correctly as defined in dialog-flow.
it outputs null value for Output Context, need a fix for this.

                await driver.BuildFluent()
                    .Start()
                    .UserSaysText(singleMsg)
                    .WaitBotSays((text) => console.log(text))                 
                    .Stop()
                    .Clean()
                    .Exec()
                    .then(() => {
                        console.log(`Test Passed for FAQ Training message: ${singleMsg}`);
                    })
                    .catch((err) => {
                        console.log(`ERROR, Test Failed ${singleMsg}: `, err)
                        assert.fail(text, text, err);
                    });

sample Botium script and Output Context :  

{ sender: 'bot',
  sourceData:
   { fulfillmentMessages: [ [Object] ],
     outputContexts: [ [Object], [Object], [Object] ],
     queryText: 'I need information on Food Safety?',
     speechRecognitionConfidence: 0,
     action: '',
     parameters: { fields: {} },
     allRequiredParamsPresent: true,
     fulfillmentText: 'If you require Food Safety documentation to comply with your business regulations please contact the Business Support Team',
     webhookSource: '',
     webhookPayload: null,
     intent:
      { inputContextNames: [],
        events: [],
        trainingPhrases: [],
        outputContexts: [],
        parameters: [],
        messages: [],
        defaultResponsePlatforms: [],
        followupIntentInfo: [],
        name: 'projects/chatbot/agent/intents/<intent-id>',
        displayName: 'FAQ-How can I obtain information on Food Safety?',
        priority: 0,
        isFallback: false,
        webhookState: 'WEBHOOK_STATE_UNSPECIFIED',
        action: '',
        resetContexts: false,
        rootFollowupIntentName: '',
        parentFollowupIntentName: '',
        mlDisabled: false },
     intentDetectionConfidence: 1,
     diagnosticInfo: null,
     languageCode: 'en-us' },
  messageText: 'If you require Food Safety documentation to comply with your business regulations please contact the Business Support Team',
  channel: 'default' }

**Comment by codeforequity-at** [comment]
In the beginning of your log output above, there obviously are 3 output contexts available:

{ sender: 'bot',
sourceData:
{ fulfillmentMessages: [ [Object] ],
**outputContexts: [ [Object], [Object], [Object] ],**
queryText: 'I need information on Food Safety?',
...

I don't understand what you mean.

**Comment by Arun-wws** [comment]
What I meant is the Output Contexts inside the intent is null.

intent:
{ inputContextNames: [],
events: [],
trainingPhrases: [],
**outputContexts: []**,
parameters: [],

the output contexts inside intents. and also what it means by [Object] [Object] is not clear to me.
I think it should output the Object information there.

outputContexts: [ [Object], [Object], [Object] ],

**Comment by Arun-wws** [comment]
See for example response from Postman on Contexts



{
    "id": "<<some_id>>",
    "timestamp": "2018-09-21T06:30:13.836Z",
    "lang": "en",
    "result": {
        "source": "agent",
        "resolvedQuery": "I need information on Food Safety?",
        "action": "",
        "actionIncomplete": false,
        "parameters": {},
        "contexts": [
            {
                "name": "bot_feedback",
                "parameters": {},
                "lifespan": 1
            },
            {
                "name": "business",
                "parameters": {},
                "lifespan": 2
            },
            {
                "name": "order",
                "parameters": {},
                "lifespan": 1
            },
            {
                "name": "",
                "parameters": {},
                "lifespan": 2
            }
        ],
        "metadata": {
            "intentId": "<<intent_id>>",
            "webhookUsed": "false",
            "webhookForSlotFillingUsed": "false",
            "isFallbackIntent": "false",
            "intentName": "FAQ-How can I obtain information on Food Safety?"
        },
        "fulfillment": {
            "speech": "If you require Food Safety documentation to comply with your business regulations please contact the Business Support Team",
            "messages": [
                {
                    "type": 0,
                    "speech": "If you require Food Safety documentation to comply with your business regulations please contact the Business Support Team"
                }
            ]
        },
        "score": 1
    },
    "status": {
        "code": 200,
        "errorType": "success"
    },
    "sessionId": "1234567"
}

**Comment by Arun-wws** [comment]
looks Good ! I'm able to get Output Context when JSON.stringify(msg) is used, thanks for this.
But still curious to know why the Output Contexts inside the intents remains null, even if we can close issue.

**Comment by codeforequity-at** [comment]
I think this is just a special case in the dialogflow API. If you follow the API link above and drill down to the "intent" field, there is a hint that not all field might be filled here.

> Intent
> 
> The intent that matched the conversational query. Some, not all fields are filled in this message, 
> including but not limited to: name, display_name and webhook_state.
