### ISSUE TITLE
 "SCRIPTING_UTTEXPANSION_MODE": "First" is not working

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#111]
"SCRIPTING_UTTEXPANSION_MODE": "first"
I added this in botium.json. However, it is still executing all utterances in combination
E.g there are 2 files 
File A contains 2 utterances and File B contains 3 utterances then it executes the test 6 times with all combinations. I want to execute 1 utterance only once.

**Comment by codeforequity-at** [comment]
This is strange. Can you please enable debug mode and attach the output here. thanks.

**Comment by DipaliK9** [comment]
> 
> 
> This is strange. Can you please enable debug mode and attach the output here. thanks.
Enabled debug mode using command export DEBUG=testmybot*,botium* and copied log in attached file.
[Log.txt](https://github.com/codeforequity-at/botium-core/files/2419583/Log.txt)

**Comment by codeforequity-at** [comment]
What version of botium-cli are you running ? Please use the latest build - to log file doesn't show one important output line, which makes me believe that this feature is not yet included in your local installation.

**Comment by DipaliK9** [comment]
> 
> 
> What version of botium-cli are you running ? Please use the latest build - to log file doesn't show one important output line, which makes me believe that this feature is not yet included in your local installation.
It is 0.0.18. Which version should I install?

**Comment by codeforequity-at** [comment]
just use the latest one (0.0.22, just three weeks old).

**Comment by DipaliK9** [comment]
Thanks for the quick reply.
I did git clone https://github.com/codeforequity-at/botium-cli.git
But it still shows 
 botium-cli --version
0.0.18
Am I missing anything? Please help.

**Comment by DipaliK9** [comment]
Thank you so much :) I missed to delete it mistakenly.

You were right. After updating version,"SCRIPTING_UTTEXPANSION_MODE": "first" worked.
This will take only first utterance. 
Since logged issue is already resolved. I am not sure if this is the right place to continue my question in the same thread or not. But to some extent this is related so here is my question.

I have 3 utterance files having 4 , 3 and 2 utterances respectively.
My requirement is to execute convo with all utterances only once. i.e. in this case there will be 5 cases to be executed. However if I add "SCRIPTING_UTTEXPANSION_MODE": "random" and count 4, it executes combination of all utterances and executes 12 cases. Is there any other way?

**Comment by DipaliK9** [comment]
E.g.  See convo file and utterances file as given below. Here if I add SCRIPTING_UTTEXPANSION_MODE": "first" This will execute only one case with Greeting. utterances. txt as Hi and Question as What is your name?. However, if I say SCRIPTING_UTTEXPANSION_MODE": "random" with count 4 or SCRIPTING_UTTEXPANSION_MODE": "all" This will execute all combinations 4*2=8 test cases.
I want Hi utterance to be used only once.
Hope this helps you to understand my requirement. :)

**Test.convo.txt**
"#me
Greeting. utterances. txt
'#bot
Welcome to bot.
'#me
Question

**File: Greeting. utterances. txt**
Hi
Hello
Good Morning
Good Evening

**File: Question.utterances.txt**
What is your name?
May I know your name?

**Comment by codeforequity-at** [comment]
I think the file syntax is wrong. The file name for the utterances file are not important (only the ".utterances.txt" suffix).
* First line contains a "reference code" for the utterances
* Following lines contain sample utterances
See https://github.com/codeforequity-at/botium-core/wiki/Botium-Scripting#utterances-syntax

So this is the right file content for your use case:

**Test.convo.txt**
"#me
greeting.utterances
'#bot
Welcome to bot.
'#me
question.utterances

**File: Greeting. utterances. txt**
greeting.utterances
Hi
Hello
Good Morning
Good Evening

**File: Question.utterances.txt**
question.utterances
What is your name?
May I know your name?


And no, I stil don't understand your requirement. Botium expands the conversation based on the expansion mode - with "first", only ONE of each utterance will be used, with "all", all COMBINATIONS of utterances will be used, and with "random", some of the utterances are selected and all combinations of them are formed.

**Comment by codeforequity-at** [comment]
Any Update here ?

**Comment by codeforequity-at** [comment]
no feedback.
