### ISSUE TITLE
Support for websockets

### ISSUE THREAD

**Issue by mvsmurty** [codeforequity-at/botium-core#112]
Hello,
Is the containers available for testing using websockets? I am building my own bot framework using websockets. Appreciate your help.
Venkat

**Comment by codeforequity-at** [comment]
this is currently not supported, but as lots of web-based chatbots are working with websockets, it would definitely be a good idea to have a connector for this.

**Comment by mvsmurty** [comment]
Do you have any implementation in your roadmap?

**Comment by codeforequity-at** [comment]
no, not really. we are community driven, and I heard about missing support for websockets several times, so there are good changes that someone will work on it in near future. After all, it isn't much effort, we already have a generic HTTP/JSON connector, would be a good base for supporting websockets.

**Comment by codeforequity-at** [comment]
added it to our internal backlog.
