### ISSUE TITLE
How to install and configure BOTIUM?

### ISSUE THREAD

**Issue by rajesh4252** [codeforequity-at/botium-core#113]
Dear Team,
 
         Please help with below details as I am beginner to this tool .

How to install BOTIUM??
What are the prerequisites to install BOTIUM?

**Comment by codeforequity-at** [comment]
Those questions are not so easy to answer as you would expect. In some cases, downloading a standalone program and using Excel for composing the test case is sufficient, and I recommend this article to get started: https://chatbotsmagazine.com/3-steps-setup-automated-testing-for-google-assistant-and-dialogflow-de42937e57c6

If you want to implement continuous testing and/or integration Botium into your continuous delivery and build pipelines, the requirements (technical and knowledge) are higher of course.
