### ISSUE TITLE
If any of the test case failed, chatbot does not get reset and all remaining test cases gets failed. Any workaround for this?

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#114]
If any of the test case failed, chatbot does not get reset and all remaining test cases gets failed. Any workaround for this?
Is there any way that I can apply a condition through code saying that if test case fails then exit from chatbot conversation. So that new test case will start conversation from scratch.

Note: I am using FBdirect container mode in Botium CLI

**Comment by codeforequity-at** [comment]
The test cases should be split into several convo files - each file is then run in it's own sandbox and won't tear down the other ones.

**Comment by DipaliK9** [comment]
Thanks for the quick reply.

I have created one convo file for test case. However within that convo file n number of utterances  are being used. So if any of the utterance gets failed. chatbot does not get reset and continues the conversation and hence all remaining cases gets failed.

**Comment by codeforequity-at** [comment]
If one step in a convo file fails, the test case is considered to be failed as a whole, and the next convo file is used. 
In your case the problem might be that with the fbdirect mode, it is not possible to just "reset" the chatbot, as Facebook itself stores the state. We had similar problems, and we decided to introduce a "reset" command which cleans up all conversation and session related data in the chatbot code - but this is something you will have to develop in your chatbot code first, afterwards, just send the keyword "reset" to the bot at the beginning of each convo file.

**Comment by DipaliK9** [comment]
Do you mean I need to add intent as Reset in my chatbot or do some coding. Can you please elaborate more.
Thanks :)

**Comment by DipaliK9** [comment]
> 
> 
> If one step in a convo file fails, the test case is considered to be failed as a whole, and the next convo file is used.
> In your case the problem might be that with the fbdirect mode, it is not possible to just "reset" the chatbot, as Facebook itself stores the state. We had similar problems, and we decided to introduce a "reset" command which cleans up all conversation and session related data in the chatbot code - but this is something you will have to develop in your chatbot code first, afterwards, just send the keyword "reset" to the bot at the beginning of each convo file.

Thanks  Reset worked. :)
