### ISSUE TITLE
Using DialogFlow facebook responses, not default responses for testing

### ISSUE THREAD

**Issue by madtaras** [codeforequity-at/botium-core#118]
Hi!

I used this article to set up tests https://chatbotsmagazine.com/3-steps-setup-automated-testing-for-google-assistant-and-dialogflow-de42937e57c6

Most of the tests fail because of Botium is waiting for DialogFlow default answers, not facebook answers. How can I configure Botium to use facebook answers?

<img width="357" alt="screen shot 2018-10-02 at 4 31 35 pm" src="https://user-images.githubusercontent.com/14792549/46351739-bfb0df80-c660-11e8-81f1-57d07244cce3.png">
<img width="362" alt="screen shot 2018-10-02 at 4 31 42 pm" src="https://user-images.githubusercontent.com/14792549/46351741-bfb0df80-c660-11e8-8f21-e06807bc0fb5.png">

**Comment by codeforequity-at** [comment]
The dialogflow connector currently doesn't support this. But I agree that this is more than useful. I am tracking this topic, hopefully we will be able to provide a solution soon.

**Comment by madtaras** [comment]
@codeforequity-at cool!
I checked out the connector code. Looks like know what to do. Could you please help me? I can't find the place where to choose facebook response in dialogflow API https://github.com/googleapis/nodejs?

**Comment by codeforequity-at** [comment]
The latest build includes this feature. The new capability is named "DIALOGFLOW_OUTPUT_PLATFORM", set it to "FACEBOOK"

**Comment by madtaras** [comment]
@codeforequity-at thanks!
I'm getting undefined on 
`
  .UserSaysText('hi')
  .WaitBotSaysText(console.log)
  .WaitBotSays(console.log)
`

buy console.log(response.queryResult.fulfillmentMessages) in connector code returns 
`
[ { platform: 'FACEBOOK',
    card: 
     { buttons: [Array],
       title: '',
       subtitle: ',
       imageUri: '' },
    message: 'card' },
  { platform: 'PLATFORM_UNSPECIFIED',
    text: { text: [Array] },
    message: 'text' } ]

` (I deleted the values from object). Will try to fix this

**Comment by madtaras** [comment]
@codeforequity-at any ideas on why this happens?

**Comment by codeforequity-at** [comment]
Hi, we are working hard to not only support text messages, but also the rich messages and custom payload.  So the cards you are obviously using can now be asserted in Botium scripts with some simple tags in the convo files.
