### ISSUE TITLE
Is there any way to add wait before executing next test case( conversation.) in Directline3.

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#120]
Is there any way to add wait before executing next test case( conversation) in Directline

Conversation1
Wait for 5 mins
Conversation2
................
My Requirement is for each conversation new session should be started and 
in case of my bot, if user gives response after 5 mins then Previous session gets expired and conversation starts from beginning.

So please let me know either a way to apply wait or a way to expire previous session and start new session for each new conversation.

**Comment by codeforequity-at** [comment]
Yes, this is possible but it requires a little bit coding.
Botium supports "custom hooks", see https://github.com/codeforequity-at/botium-core/wiki/Botium-Configuration#custom-hooks

you can pass in a function for the "on start" hook which will just return a promise which resolves after 5 minutes.
