### ISSUE TITLE
Randomly getting Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#122]
Hi,
I am using Directline3  and I am randomly getting  following error.

```
Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\--\AppData\Roaming\npm\node_modules\botium-cli\src\run\mocha.spec.js)

```

**Comment by codeforequity-at** [comment]
I experienced the same several times, but I haven't found a solution yet. From what I found out so far, this is not a Botium problem, and not a problem with the Chatbot, but with Directline itself - sometimes it just doesn't respond. I will have to investigate in detail, but it takes some time.

**Comment by codeforequity-at** [comment]
First, please get the latest version of Botium-CLI. When running in verbose mode, you should now see the Directline connection status, maybe this provides some hints.
Furthermore, have you tried to set the capability "DIRECTLINE3_WEBSOCKET" to false ? Sometimes, there are problems with HTTP proxies when running websocket connection.
