### ISSUE TITLE
How to handle inputs from action buttons in chatbot

### ISSUE THREAD

**Issue by AdityaJasti** [codeforequity-at/botium-core#124]
Hi,

we have a requirement to handling action  buttons in  botium, can u let us know how to write test cases for handling action button in botium.

for example clicking on button bot will reply with out any message of user says.

thank you

**Comment by codeforequity-at** [comment]
Hello
Supporting this kind of interaction is currently one of our high priority
topics in development. What action buttons are you talking about? Facebook
messenger?

AJ <notifications@github.com> schrieb am Fr., 12. Okt. 2018, 15:11:

**Comment by AdityaJasti** [comment]
No we are currently looking for actions for bot developed with Microsoft bot framework, and direct line channel.

**Comment by codeforequity-at** [comment]
no feedback.

**Comment by vijaysimh** [comment]
Hello is there any progress on performing click actin on buttons,adaptive cards,Videos

**Comment by codeforequity-at** [comment]
Yes, most directline content types are supported now.

**Comment by VijaySimhas** [comment]
Please share the url of site where can get example of performing click action on button

**Comment by codeforequity-at** [comment]
One of the Directline connector samples includes button clicks:
https://github.com/codeforequity-at/botium-connector-directline3/tree/master/samples/convo
