### ISSUE TITLE
how to use botium agent?

### ISSUE THREAD

**Issue by ajaykumar1452** [codeforequity-at/botium-core#13]
can u help with working with botium agent while running samples example watson conversation service

**Comment by codeforequity-at** [comment]
what is the problem ?

**Comment by ajaykumar1452** [comment]
can u explain how to run sample of watson conversation service(in  botium core) using botium agent?

**Comment by codeforequity-at** [comment]
that's fully undocumented right now. I will add documentation and write a blog article about it soon.

**Comment by codeforequity-at** [comment]
See here: https://github.com/codeforequity-at/botium-core/wiki/The-Botium-Grid
