### ISSUE TITLE
Can anyone point me to a way to run the tests on a mobile device?

### ISSUE THREAD

**Issue by ShamaUgale** [codeforequity-at/botium-core#130]
I want to execute the tests on mobile device. is this possible with botium? If yes, can you please point me to a sample

**Comment by codeforequity-at** [comment]
You mean, you have a smartphone app containing a chatbot ? Or you want to test a chatbot running on a website on a mobile browser ?

**Comment by ShamaUgale** [comment]
Thanks for looking into this. I would like to do both, as part of app and on a mobile browser. Is this possible with botium?

**Comment by codeforequity-at** [comment]
Testing a chatbot within a mobile browser is supported by the Webdriver Connector, you can find some samples in the repository: https://github.com/codeforequity-at/botium-connector-webdriverio

Botium relies on a running Selenium server, but its very easy to connect Botium with a cloud provider like Saucelabs for example.

Testing chatbots running within a smartphone app is on our Todo list - it won't be much difference to the webdriver connector, because Appium and Selenium are not that different in usage, but we don't have a working sample for it.

**Comment by ShamaUgale** [comment]
thanks for the link. I pulled the repo in my local and i am executing using the below commands and i am getting errors.

npm install
npm run selenium


i also tried 

npm install
npm run phantomjs

i am getting errors like below

> botium-connector-webdriverio@0.0.6 selenium /Users/shamau/Downloads/botium-connector-webdriverio-master
> selenium-standalone start --drivers.chrome.version=2.43

no main manifest attribute, in /Users/shamau/Downloads/botium-connector-webdriverio-master/node_modules/selenium-standalone/.selenium/selenium-server/3.12.0-server.jar
/Users/shamau/Downloads/botium-connector-webdriverio-master/node_modules/selenium-standalone/bin/selenium-standalone:79
        throw err;
        ^

Error: Selenium server did not start.
Another Selenium process may already be running or your java version may be out of date.
Be sure to check the official Selenium release notes for minimum required java version: https://raw.githubusercontent.com/SeleniumHQ/selenium/master/java/CHANGELOG

    at ChildProcess.errorIfNeverStarted (/Users/shamau/Downloads/botium-connector-webdriverio-master/node_modules/selenium-standalone/lib/start.js:158:10)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botium-connector-webdriverio@0.0.6 selenium: `selenium-standalone start --drivers.chrome.version=2.43`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the botium-connector-webdriverio@0.0.6 selenium script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shamau/.npm/_logs/2018-10-31T10_15_10_492Z-debug.log

**Comment by codeforequity-at** [comment]
Selenium has some requirements on Java, please check first if you have to right java version.

You are trying to use the Selenium server started by the Botium webdriver connector - this doesn't work out of the box. I will add some instructions to the repository Readme later on. Usually, you already have some kind of Selenium server started before using the Botium webdriver connector.

**Comment by ShamaUgale** [comment]
ok, i will try having a selenium server up and running before running the botium tests. Also do you have any sort of training or execution videos for reference?

**Comment by codeforequity-at** [comment]
I added some instructions to the Readme file: https://github.com/codeforequity-at/botium-connector-webdriverio/blob/master/README.md

The Webdriver connector is pretty new - we've had some demos at meetups and conferences, but currently there is not much information available, I didn't have the time yet to write a blog post or much documentation, but this will follow for sure in the next weeks.

**Comment by ShamaUgale** [comment]
Hi,
I have followed https://github.com/codeforequity-at/botium-connector-webdriverio/blob/master/README.md 
and been trying to run the https://github.com/codeforequity-at/botium-connector-webdriverio/tree/master/samples/dialogflow 
 sample on "chrome" and i am getting the below error, the file missing. Is there any change to be made for pakage.json ??


INShamaugales-MacBook-Pro:dialogflow shamau$ npm install
npm WARN samples@1.0.0 No description
npm WARN samples@1.0.0 No repository field.

npm ERR! path /Users/xyz/Desktop/botAutomation/wd_sample/botium-connector-webdriverio/samples/dialogflow/node_modules/.staging/botium-connector-webdriverio-bbe81832/node_modules/@types/estree
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/xyz/Desktop/botAutomation/wd_sample/botium-connector-webdriverio/samples/dialogflow/node_modules/.staging/botium-connector-webdriverio-bbe81832/node_modules/@types/estree' -> '/Users/xyz/Desktop/botAutomation/wd_sample/botium-connector-webdriverio/samples/dialogflow/node_modules/.staging/@types/estree-892fb725'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xyz/.npm/_logs/2019-01-08T09_45_34_550Z-debug.log



I have changed the browserName in botium-local.json file as below 

"desiredCapabilities": {
          "browserName": "phantomjs",
"__browserName": "chrome",

also marked "WEBDRIVERIO_START_PHANTOMJS": true to "WEBDRIVERIO_START_PHANTOMJS": false
