### ISSUE TITLE
Need help in automating voice skill using webspeech

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#131]
Hi,
I want to create automation script to test my alexa voice skill. Please let me know the best way to do it in botium.
Thanks  :)

**Comment by codeforequity-at** [comment]
I wrote a blog article some time ago: https://chatbotslife.com/alexa-are-you-ok-test-automation-for-alexa-skills-53088429d53 - I think you will find hints on the first steps there

**Comment by DipaliK9** [comment]
I already saw your blog. It was very useful and I wanted to go for option given below. However, I couldn't figure out how to use Webspeech connector and setup the whole thing.
can you please help?
    Place an Amazon Echo next to your workstation
    Configure Botium to use the Webspeech connector
    Listen and enjoy :-)

**Comment by codeforequity-at** [comment]
Triggered by your request, I finally wrote some documentation for the Webspeech capabilities:
https://github.com/codeforequity-at/botium-core/wiki/Operation-Mode-webspeech

This should be enough to give it a try. A [sample](https://github.com/codeforequity-at/botium-core/blob/master/samples/webspeech/botiumFluent.js) is available as well.

**Comment by DipaliK9** [comment]
Thanks :) 
I will try this.

**Comment by DipaliK9** [comment]
I am new to this, so not sure . But The Sample that you provided, there is no Botium.js file where in webspeech is used as container mode. How do we connect to a specific skill and do the set up is still not clear.
Any help will be appreciated.
Thanks

**Comment by codeforequity-at** [comment]
In the sample, the capabilities are defined in the script file itself, should have been extracted to botium.json, right.

The webspeech connector is intended to use with a real home automation device like Amazon Alexa. The speakers of your workstation are used for outputting text, the microphone for input. So you don't need to configure a Skill ID.
Just let Botium say "Alexa, open spotify and play frank sinatra" :-)

**Comment by codeforequity-at** [comment]
And by the way, you don't even need a home automation device, you could do this part with your own voice as well ...

**Comment by codeforequity-at** [comment]
Is it possible to launch your skill on your echo device ? If yes, then you should be fine if you just create a convo file as usual. Just use the same texts you are using when launching your skill by voice.

**Comment by DipaliK9** [comment]
Hi
I tried this. However, when I run the script, Alexa doesnt get invoke. I am not able to adjust volume and pitch. I can hear the sound but Alexa is not getting invoked and also, if I say the message manually instead of using Amazon Echo device, still script is not listening to my voice.
Am I missing anything?

`"CONTAINERMODE": "webspeech",
      "WEBSPEECH_LANGUAGE": "en-US",
      "WEBSPEECH_PITCH": 6,
      "WEBSPEECH_CLOSEBROWSER": true,
	  "WEBSPEECH_BROWSER_APP": "Chrome",
	 "WEBSPEECH_SERVER_PORT": 46050,
	 "WEBSPEECH_VOLUME": 50000,
	 "WAITFORBOTTIMEOUT": 30000,
	 "WEBSPEECH_RATE": 0.5`

**Comment by DipaliK9** [comment]
When I run botium, Browser window is visible and I can hear conversation (per the file I created).
But I am using Alexa device. And when my scripts executes, there is something wrong with the pitch and volume, Alexa is not getting invoked, Because when my script says invoke statement, I can hear it but Alexa doesn't understand.
I tried all combinations but the pitch and volume is not getting changed.

**Comment by codeforequity-at** [comment]
So, when I tested it last time, I had this kind of trouble as well, it only worked when I made it with maximum volume (on my laptop speakers), and placed Alexa directly in front of them. 
We are currently working on better support for testing Alexa skills by using the Alexa Voice Service.

**Comment by DipaliK9** [comment]
I have a mic and I tried to record my voice using it. So I know it works properly for sure. But my script still says "Bot says nothing". Could you please help what could be wrong?

**Comment by codeforequity-at** [comment]
Is there any log output in the browser window ? I think you already set "WEBSPEECH_CLOSEBROWSER" to false, so the browser window should stay open.
By the way, for testing Alexa skills, there is a better option now to use the [Alexa Voice Service](https://github.com/codeforequity-at/botium-connector-alexa-avs)

**Comment by DipaliK9** [comment]
Thanks. I will go with this option. But just one question it can be used for e2e testing of skill right. using actual alexa device, I should be able to test. Please confirm.

**Comment by codeforequity-at** [comment]
It's an E2E-Test, but without an actual Alexa device. It's done with a kind of "virtual" alexa device using Text-To-Speech and Speech-To-Text technology.

**Comment by sabiha09** [comment]
The sample for webspeech (https://github.com/codeforequity-at/botium-core/blob/master/samples/webspeech/) has been removed now. Does botium no longer supports it? Or where can i find sample connector to proceed with it?
