### ISSUE TITLE
Unable to validate the configuration by running botium in emulator mode

### ISSUE THREAD

**Issue by sarom12** [codeforequity-at/botium-core#134]
Im trying out this : https://chatbotsmagazine.com/10-minutes-codeless-test-automation-for-ibm-watson-chatbots-d71eac9626d7

But unable to validate the configuration by running Botium in “emulator”mode 
> botium-cli emulator --config path/to/botium.json
Error: Loading Botium plugin failed
    at Validate.Validate.then (C:\....\botium-cli\node_modules\botium-core\src\containers\PluginConnectorContainer.js:56:15)

Is there a problem in installing the botium package?

**Comment by codeforequity-at** [comment]
Please only use this issue tracker if you think you found a bug in Botium.

* For asking questions please use Stackoverflow - we are monitoring and answering questions there.
* The documentation on a very technical level can be found in the [Botium Wiki](https://github.com/codeforequity-at/botium-core/wiki).
* For our VIP users, there is also a Slack workspace available (coming soon).
