### ISSUE TITLE
WATSON_USE_INTENT not working

### ISSUE THREAD

**Issue by k3rm17** [codeforequity-at/botium-core#139]
Following the guide from 10 Minutes: Codeless Test Automation for IBM Watson Chatbots,  I was able to import watson-intents and create testcases to test intents but recently, I have not been able to do so - I set WATSON_USE_INTENTS to true, but it continues to return me the whole text when I run the testcases.

**Comment by codeforequity-at** [comment]
It is only five days ago that this bug has been fixed. did you upgrade to the latest build ?

**Comment by k3rm17** [comment]
I did a fresh install and its working again - sorry about that.  I swear I had updated though...

**Comment by codeforequity-at** [comment]
np
glad to help
