### ISSUE TITLE
/ is changed to &#x2F;

### ISSUE THREAD

**Issue by huberrom** [codeforequity-at/botium-core#157]
I have a test where the user send a message using /, and my bot receive &#x2F; instead.
I saw this issue (https://github.com/codeforequity-at/botium-core/issues/29) about encoding that says it should be fixed.
I'm using the latest docker image of botium-cli.
Any idea ?

**Comment by codeforequity-at** [comment]
Can you please run it in debug mode (see Troubleshooting in Botium Wiki) and attach the log file here - take care to remove any secrets before posting it ...

**Comment by huberrom** [comment]
[log_botium.txt](https://github.com/codeforequity-at/botium-core/files/2680549/log_botium.txt)

Please find the log in the file.
I replace all "secrets" by [Name of secret]
The interesting part I think is : 

`botium_1  | 2018-12-14T15:09:18.843Z botium-Convo CBT-113-Bienvenue/Line 6: user says {
botium_1  |   "sender": "me",
botium_1  |   "channel": null,
botium_1  |   "messageText": "/bienvenue",
botium_1  |   "stepTag": "Line 6",
botium_1  |   "not": false,
botium_1  |   "asserters": []
botium_1  | }
botium_1  | 2018-12-14T15:09:18.846Z botium-SimpleRestContainer constructed requestOptions {
botium_1  |   "uri": "[SIMPLEREST URL]",
botium_1  |   "method": "POST",
botium_1  |   "json": true,
botium_1  |   "headers": {
botium_1  |     "Authorization": "Bearer [JWT TOKEN]"
botium_1  |   },
botium_1  |   "body": {
botium_1  |     "query": "&#x2F;bienvenue"
botium_1  |   }
botium_1  | }`

**Comment by codeforequity-at** [comment]
Try to replace the body template capability, use **3 braces** instead of 2. Mustache is used for text replacement here, which will do some unwanted encoding otherwise.

```
SIMPLEREST_BODY_TEMPLATE: '{ "query": "{{{msg.messageText}}}" }',
```

**Comment by huberrom** [comment]
Working, thank you !
Only issue (but quickly fixed, just for others), json doesn't allow single quote, so the correct line I had to use was :

```"SIMPLEREST_BODY_TEMPLATE": "{ \"query\": \"{{{msg.messageText}}}\" }"```
