### ISSUE TITLE
how to integrate entities from dialogflow into Botuim 

### ISSUE THREAD

**Issue by Qrt487293** [codeforequity-at/botium-core#159]

**Comment by codeforequity-at** [comment]
Please give an example what you want to do.

**Comment by Qrt487293** [comment]
I want to use entities also in my training phrases while creating test cases. Let say i have one Intent Deliver Pizza. I have user says like
I haven't received my pizza
My pizza order not deleiverd yet.

So here i have entities order_not_received in which values(synonyms) are haven't received,have not received,didn't get,not deleiverd yet.when i am importing test cases in that time only user says is coming. I want to get my entities synonims too in that case like
I haven't received my pizza
I didn't get my pizza
I have not received my pizz order

So how we can get the entities different values(synonyms)combiend with user says in convo files through Botium.
And for webhook response how botuim will identify the response from webhook and match with output file.Because in output file text are present which we have defined in default response not in webhook. It's call webhook when test cases are running.

**Comment by codeforequity-at** [comment]
I think what you need is to separate conversation structure from the utterances (synonyms). Did you have a look at the "Botium in a nutshell" blog, especially [Part 2](https://medium.com/@floriantreml/botium-in-a-nutshell-part-2-writing-chatbot-tests-8726204c8da6)
