### ISSUE TITLE
Incomplete documentation on running tests

### ISSUE THREAD

**Issue by staticdev** [codeforequity-at/botium-core#169]
I've read the "Botium in a Nutshell" and wiki, but I am struggling with Part 3 (running the tests). The tutorial "Botium in a Nutshell" only shows how to configure botium.json for Microsoft Bot Framework using the CLI. I wanted to run Botium CLI calling a HTTP/JSON API to send messages to my bot. After reading through the wiki, I haven't seen an example or explanation of the parameters to do that.

Boting Bindings and Botium Box part of the tutorial is also "Coming soon …" for some time now.

**Comment by codeforequity-at** [comment]
you are absolutly right that the documentation is incomplete.
there is a page in the wiki for the http connector https://github.com/codeforequity-at/botium-core/wiki/operation-mode-simplerest
and the samples folder in the repository has sample configuration. 
botium box will be released in january

**Comment by staticdev** [comment]
@codeforequity-at thanks a lot! After reading everything more carefully I was able to identify I need this simplerest mode. I think it is extremely important to explain the CONTAINERMODE for the minimal understanding of Botium here:
 https://medium.com/@floriantreml/botium-in-a-nutshell-part-3-automating-chatbot-tests-6c4e9e85121e

**Comment by codeforequity-at** [comment]
Feedback appreciated. Blog will be updated.
