### ISSUE TITLE
Call custom webhook in before each method

### ISSUE THREAD

**Issue by huberrom** [codeforequity-at/botium-core#174]
Hi, 

Is there a way to call a custom webhook (which is different to the SIMPLEREST_URL) before each convo ? I need it to pass some value to the chatbot before each conversation, otherwise the bot is no going to work. I could do it in a before all method if the conversation id doesn't change during the tests.

**Comment by huberrom** [comment]
Is it possible to send a payload with the ping url ? And can we chose which method is used (POST, GET..)

Indeed, I found where I could handle the conversation id, thank you

**Comment by codeforequity-at** [comment]
Currently it is not possible to specify anything else but the URL - it is more for asserting that the endpoint is online, than for doing initialization stuff.
There is an additional option to use the custom hooks (https://github.com/codeforequity-at/botium-core/wiki/Botium-Configuration#custom-hooks) to run a wget/curl command before each convo, capability CUSTOMHOOK_ONSTART can be used.

[One of the samples](https://github.com/codeforequity-at/botium-core/blob/master/samples/rasa/botium.json) is using the custom hooks command to startup and teardown Rasa server.

**Comment by huberrom** [comment]
Well that would have been perfect thank you. I found an workaround with rasa too, but thanks for your help !
