### ISSUE TITLE
Rate limit on SimpleREST

### ISSUE THREAD

**Issue by staticdev** [codeforequity-at/botium-core#178]
**Is your feature request related to a problem? Please describe.**
Some bots call APIs that has rate limits.

**Describe the solution you'd like**
A parameter to execute tests with a maxium of X per second.

**Describe alternatives you've considered**
Setting a delay between tests could be an alternative.

**Additional context**
Executing tests too fast could make users blocked.

**Comment by codeforequity-at** [comment]
I agree, this might be very useful. I added it to our backlog.

Your suggested alternative solution could work: just add a PAUSE instruction to the convo file in the first #me section:



    ...
    #me
    PAUSE 5000
    text to send ...
    
    #bot
    ...

This will wait 5 seconds before starting the conversation.

**Comment by codeforequity-at** [comment]
@staticdev This was added in the latest Botium Core. https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360603/Botium+Configuration+-+Capabilities#Rate-Limiting
