### ISSUE TITLE
 error is displayed in npm install for botbuilderwebchat

### ISSUE THREAD

**Issue by hitesh22nov** [codeforequity-at/botium-core#179]
Following error is displayed in npm install for botbuilderwebchat

erwebchat> npm install
npm WARN samples@1.0.0 No description
npm WARN samples@1.0.0 No repository field.

npm ERR! path C:\Users\hiteshyadav\Desktop\ChatAuto\UnderTest\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\botbuilderwebchat\node_modules.staging\botium-connector-webdriverio-a26a90de\node_modules@types\estree
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

Using visual studio code

**Comment by codeforequity-at** [comment]
Please run "npm  install" in the root folder of the repository first.

**Comment by hitesh22nov** [comment]
Already done that, in root folder installation was successful but the above error is encountered "npm install" is done for samples/botbuilderwebchat

**Comment by codeforequity-at** [comment]
no feedback
