### ISSUE TITLE
How to install Botium?

### ISSUE THREAD

**Issue by stephenws** [codeforequity-at/botium-core#18]
Can you explain how to install Botium in Eclipse

**Comment by codeforequity-at** [comment]
https://chatbotsmagazine.com/5-steps-automated-testing-of-chatbots-in-eclipse-ef4c3dcaf233

**Comment by stephenws** [comment]
Do we need to install npm botium-core before above steps?

**Comment by codeforequity-at** [comment]
will be installed automatically

2018-03-19 19:09 GMT+01:00 stephenws <notifications@github.com>:
