### ISSUE TITLE
Chatbot Automation containing 8000+ transaction

### ISSUE THREAD

**Issue by Kiruthi464** [codeforequity-at/botium-core#181]
Is this possible to automate a Facebook / Web- Client chat-bot containing 8000+ contents. Ideally the thing to verify whether the ML prediction is happening exactly.

**Comment by codeforequity-at** [comment]
hi, this is exactly what botium is about :-)
it scales very well to hundred thousands of test cases and supports lots of
different chatbot architectures and infrastructures.

Am Do., 10. Jän. 2019, 10:10 hat KiruthikaSelenium <notifications@github.com>
geschrieben:
