### ISSUE TITLE
Unable to run tests - Loading botium plugin failed for directline3

### ISSUE THREAD

**Issue by vivekbrahmadandi** [codeforequity-at/botium-core#184]
Hi,

I am attempting to test against direclist

Running:
ubuntu -16.04
Node -10.15.0
Npm 6.4.1
Step by step what I did:

I installed botium-cli: npm i botium-cli -g
Where this is my package.json:
`{
  "name": "botium",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "emulator": "botium-cli emulator console --convos ./spec/convos --config ./botium.json",
    "emulatorBrowser": "botium-cli emulator browser --convos ./spec/convos --config ./botium.json"
  },
  "author": "",
  "license": "ISC"
}`

And this is my botium.json:

<code>
{  
   "botium":{  
      "Capabilities":{  
         "PROJECTNAME":"",
         "CONTAINERMODE":"directline3",
         "DIRECTLINE3_SECRET":",
         "DIRECTLINE3_WEBSOCKET":true,
         "DIRECTLINE3_POLLINGINTERVAL":1000
      },
    "Sources": {},
      "Envs": {
        "NODE_TLS_REJECT_UNAUTHORIZED": 0
      }  
   }
}
</code>

And i Wrote  a file botiumFluent.json file 

<code>
const BotDriver = require('botium-core').BotDriver
const driver = new BotDriver()
driver.BuildFluent()
  .Start()
  .UserSaysText('Hello')
  .WaitBotSaysText(console.log)
  .WaitBotSays((msg) => console.log(JSON.stringify(msg, null, 2)))
  .WaitBotSays((msg) => console.log(JSON.stringify(msg, null, 2)))
  .WaitBotSays((msg) => console.log(JSON.stringify(msg, null, 2)))
  .WaitBotSays((msg) => console.log(JSON.stringify(msg, null, 2)))
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })
</code>

I used the command to run this file as "node botiumFluent.js" and it gives and error saying "ERROR:  Error: Loading Botium plugin failed
    at Validate.Validate.then (/home/vivekb/tamara/tamara-example/node_modules/botium-core/src/containers/PluginConnectorContainer.js:56:15)"

**Comment by codeforequity-at** [comment]
Please have a look at the [Readme for the Directline Connector](https://github.com/codeforequity-at/botium-connector-directline3) - what I noticed immediately is that the _botium.json_ file is missing the directline secret. Furthermore, when using botium-cli, you don't need to code any javascript.

**Comment by codeforequity-at** [comment]
Please use Stackoverflow for questions, the issue tracker is for bug reports and feature requests only.

**Comment by vivekbrahmadandi** [comment]
I wantedly kept empty here , in my local it has

**Comment by vivekbrahmadandi** [comment]
it worked after installing npm package called npm install -g botium-connector-directline3

**Comment by codeforequity-at** [comment]
Great. It is strange in a way that you already installed botium-cli in global npm cache, and this should mean that the botium-connector-directline3 module (as a dependency) should have been installed already. But good to hear that you found the solution!

**Comment by vivekbrahmadandi** [comment]
thanks for looking into the isses

**Comment by vivekbrahmadandi** [comment]
How can add the mochawesome to the botium-bindings

**Comment by codeforequity-at** [comment]
Please see this sample: https://github.com/codeforequity-at/botium-bindings/tree/master/samples/watson
you have to add the dependency to package.json and add additional options to the mocha command.

**Comment by vivekbrahmadandi** [comment]
thanks for helping out
