### ISSUE TITLE
Account Linking in Botium

### ISSUE THREAD

**Issue by jgsheffer** [codeforequity-at/botium-core#185]
I have a google action which requires an account to be linked.  I am unable to find any examples on how to interact with authenticated actions.  Is this currently possible to test this with Botium?

**Comment by ujja** [comment]
we did not check oauth version of account linking yet (https://developers.google.com/actions/identity/google-sign-in-oauth), it is possible that our solution will cover it too.

**Comment by ujja** [comment]
https://www.npmjs.com/package/botium-connector-google-assistant
