### ISSUE TITLE
More detail on the botium.json file?

### ISSUE THREAD

**Issue by OBrien1510** [codeforequity-at/botium-core#186]
I'm trying to set up botium for my MBF v3 bot but I've been unable to connect to my bot. Specifically I'm confused what the field in the botium.json file, "DIRECTLINE3_SECRET" refers to. Is this meant to be the app id of the bot? Or maybe the URL of the deployed bot? Any help would be appreciated.

**Comment by codeforequity-at** [comment]
Please see the [connector documentation](https://github.com/codeforequity-at/botium-connector-directline3#connecting-microsoft-bot-framework-to-botium) how to retrieve the directline secret.

Please, use Stackoverflow for questions, this forum is for bug reports and feature requests only ...
