### ISSUE TITLE
WebdriverIO Supported Capabilities Documentation

### ISSUE THREAD

**Issue by chrisgomez** [codeforequity-at/botium-core#189]
Is there documentation for WebdriverIO supported capability usage? For capabilities such as those ending with 'ELEMENT' it appears that the acceptable value is the locator but for many of the others, there doesn't seem to be any supplied docs.

**Comment by codeforequity-at** [comment]
The documentation is incomplete, that's in our backlog.
It will be available very soon in the repository Readme (https://github.com/codeforequity-at/botium-connector-webdriverio).

Until then, from the samples I think you can get a good overview what's possible and what isn't. For every aspect it is possible to define locators (css and xpath), JS functions, JS modules - the connector tries to provide maximum flexibility for all possible situation, within a framework which does most of the hard work in a reasonable way.

**Comment by chrisgomez** [comment]
Ah, gotcha. Yeah, I can piece enough of it together with the sample projects to get started. Thanks for replying, I'll keep a eye out for updated docs.

**Comment by codeforequity-at** [comment]
Will close for now. Feel free to post questions on Stackoverflow or register feature requests / bug reports here.
