### ISSUE TITLE
Alexa AVS- What should be client ID name while enabling CBL

### ISSUE THREAD

**Issue by ChampNBM** [codeforequity-at/botium-core#194]
**Bug Description**
As per the steps given in https://github.com/codeforequity-at/botium-connector-alexa-avs#preparing-botium-capabilities, I need to enable CBL.

I followed the steps given in https://developer.amazon.com/docs/alexa-voice-service/code-based-linking-other-platforms.html to enable CBL. However, I am unable to figure out what is Client ID name ?
Can you please give me one example.
Is it device name?

**Comment by ujja** [comment]
For Botium it does not matter, it can be even a random text. I have used 'BotiumConnector'. Device name is a good choice.
