### ISSUE TITLE
Alexa AVS-Getting error while authorizing code 

### ISSUE THREAD

**Issue by ChampNBM** [codeforequity-at/botium-core#201]
**Describe the bug**
I executed following command

>./node_modules/.bin/botium-connector-alexa-avs-init

It gives me failed error as given below.
```

Authorizing device...
Device serial number: ********
Please login on https://amazon.com/us/code and enter [code]
Press enter after done
npm[15612]: src\node_file.cc:1311: Assertion `args[1]->IsInt32()' failed.
 1: 000000013F989055
 2: 000000013F962FE6
 3: 000000013F9630B1
 4: 000000013F92A687
 5: 000000013FF7B022
 6: 000000013FF7C4CD
 7: 000000013FF7B559
 8: 000000013FF7B43B
 9: 000000477EB841C1
```

**Comment by ujja** [comment]
Pease try on tty compatible console.

I got this error if I run it from Webstorm. (rightclick on js, and run) If I use windows command line, or start it from Webstorm terminal, then it works.

It looks it does not work on git bash, it freezes after start.

What are you using?

**Comment by ChampNBM** [comment]
It worked. Thanks :)

**Comment by ujja** [comment]
:)
