### ISSUE TITLE
Facing the below issue while i was trying to run node botium.js (botium-connector-alexa-smapi)

### ISSUE THREAD

**Issue by krishnasaikumarraju** [codeforequity-at/botium-core#205]
**Describe the bug**
when i was trying to run command **node botium.js** (for botium-connector-alexa-smapi).

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
It should run the test case(which has been coded in botium.js).

**Screenshots**
![image](https://user-images.githubusercontent.com/42143138/51971269-bfa1de80-249e-11e9-9f58-d011f3f907f6.png)

**Desktop (please complete the following information):**
 - OS: linux(ubuntu)
 - Version : 16

**Additional context**
why the command (i.e node botium.js) is expecting for the path/directory instead of running test case.

**Below screenshot describes the  code of botium.js**:
![image](https://user-images.githubusercontent.com/42143138/51971472-3a6af980-249f-11e9-9e9e-6e51a6c2eb3e.png)

**Comment by krishnasaikumarraju** [comment]
screenshot:
![image](https://user-images.githubusercontent.com/42143138/52051142-abcaab00-2578-11e9-84b3-248758f6079f.png)

**Comment by schwarka** [comment]
I am seeing the same issue.

"botium-cli": "0.0.44",
"botium-connector-alexa-smapi": "0.0.2",
"botium-core": "^1.4.7"

Tried running both via `botium-cli` and by defining a `botium.js` test runner file.

**Comment by codeforequity-at** [comment]
It is definitly a bug in the connector. I am working on it the next days. New build will be out on Monday.

**Comment by codeforequity-at** [comment]
The latest build of the connector (0.0.3) contains the fix for this. It is not yet available in botium-cli, will be done with the next build.

**Comment by krishnasaikumarraju** [comment]
Thnx to the botium-core team
