### ISSUE TITLE
Alexa AVS connector- incorrect conversion of speech to text of Alexa response.

### ISSUE THREAD

**Issue by ChampNBM** [codeforequity-at/botium-core#214]
Hi,
My skill is getting invoked and if I debug I am getting proper Audio response from Alexa as expected. But my test case gets failed since that response is not getting converted to text properly. There are 3 statements and it skips Hi There! and translates 2nd statement that too with incorrect spelling.
Is there any solution or workaround for this?

**Comment by ujja** [comment]
Hello,

For us it worked. What where those statements?

We support two speech to text provider now. One from google, one from amazon. Google text to speech is simplier, and faster, we suggest to use it. But it is possible that Amazon text to speech (transcribe) is better, or at least fits better to other amazon product as Alexa.

You can give a try for the other provider, but I dont expect too mutch difference there.

**Comment by ChampNBM** [comment]
Statement was Hello there, Welcome to your book recommendation assistant, Let’s get started. 
and instead of this statement I am getting Welcome to book redemption assistant
Hello there and lets get started missing.

**Comment by ujja** [comment]
We have found something to improve it, update is coming in some days.

**Comment by ChampNBM** [comment]
Please let me know once it is ready for use.
Thanks :)

**Comment by ujja** [comment]
It is out yesterday.

Documentation at: https://github.com/codeforequity-at/botium-connector-alexa-avs#alexa_avs_stt_google_cloud_speech_send_text_as_phrase_hint

Changed: 
- [Core](https://www.npmjs.com/package/botium-core)
- [Connector](https://www.npmjs.com/package/botium-connector-alexa-avs)

But I suppose It wont help you. It helped me, if I used a world which is unknown to Google, and easy to misunderstand (krls or something was it) for normal worlds it did not helped. But I tested on german.

Please inform us about your experience.

If it does not changes anything, then send logs please.
