### ISSUE TITLE
Testing chatbots using Botium (Unable to access the url https://www.botium.at)

### ISSUE THREAD

**Issue by KummaraSaiVenkateswar** [codeforequity-at/botium-core#215]
We are evaluating botium for testing chatbot application and interested to know about the functionalities and components of the framework.

But we are unable to access the url https://www.botium.at and its showing forbidden (403 error).

Do we have any other url for accessing the same?

**Comment by ujja** [comment]
It is working for us now. It was maybe some temporary error. Please try again.

If you get the same error, then try other browser/computer/incognito mode please.

**Comment by codeforequity-at** [comment]
For some reason our website seems to be blocked from some countries. Working on it. Has nothing to do with Botium software.
