### ISSUE TITLE
Error: Cannot find module 'google-assistant' 

### ISSUE THREAD

**Issue by mahmeds7777** [codeforequity-at/botium-core#218]
Hi @codeforequity-at 

I hope you've been well! I noticed the recently added support for [Google Actions](https://chatbotslife.com/ok-google-how-are-you-testing-google-actions-with-botium-794e3503c512) and therefore wasted no time in folllowing the instructions outlined [here](https://www.npmjs.com/package/botium-connector-google-assistant) in an attempt to set it up.

Unfortunately, while at the "Run Botium Connector Google Actions Initialization Tool" step, I encountered the following issue:

> Capabilities are written to botium.json
> 
> Validating Capabilities...
> /Users/mahmeds/Documents/Botium/node_modules/botium-connector-google-assistant/src/actions-on-google.js:301
>             : debugInfo.finalResponse.richResponse
>                                       ^
> 
> TypeError: Cannot read property 'richResponse' of undefined
>     at ClientDuplexStream.conversation.on (/Users/mahmeds/Documents/Botium/node_modules/botium-connector-google-assistant/src/actions-on-google.js:301:39)
>     at ClientDuplexStream.emit (events.js:182:13)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at ClientDuplexStream.Readable.push (_stream_readable.js:219:10)
>     at Object.onReceiveMessage (/Users/mahmeds/Documents/Botium/node_modules/grpc/src/client_interceptors.js:1292:19)
>     at InterceptingListener.recvMessageWithContext (/Users/mahmeds/Documents/Botium/node_modules/grpc/src/client_interceptors.js:607:19)
>     at /Users/mahmeds/Documents/Botium/node_modules/grpc/src/client_interceptors.js:706:14

Running > Botium-cli Emulator -v yielded:

> cagtam1079296:botium mahmeds$ botium-cli emulator --v
>   botium-cli Using Botium configuration file ./botium.json +0ms
>   botium-cli-emulator command options: { _: [ 'emulator' ],
>   botium-cli-emulator   help: false,
>   botium-cli-emulator   h: false,
>   botium-cli-emulator   version: false,
>   botium-cli-emulator   V: false,
>   botium-cli-emulator   v: true,
>   botium-cli-emulator   verbose: true,
>   botium-cli-emulator   convos: [ '.' ],
>   botium-cli-emulator   C: [ '.' ],
>   botium-cli-emulator   config: './botium.json',
>   botium-cli-emulator   c: './botium.json',
>   botium-cli-emulator   ui: 'console',
>   botium-cli-emulator   emulatorport: 3000,
>   botium-cli-emulator   '$0': '/usr/local/bin/botium-cli' } +0ms
>   botium-BotDriver Loaded Botium configuration file ./botium.json +0ms
>   botium-BotDriver Loaded Botium configuration file ./botium.json +1ms
>   botium-BotDriver Changed capability CONFIG to "./botium.json" using environment variables. +0ms
>   botium-BotDriver BuildCompiler: Capabilites: { PROJECTNAME: 'Botium Project Google Assistant',
>   botium-BotDriver   TEMPDIR: 'botiumwork',
>   botium-BotDriver   CLEANUPTEMPDIR: true,
>   botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
>   botium-BotDriver   SIMULATE_WRITING_SPEED: false,
>   botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
>   botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
>   botium-BotDriver   DOCKERMACHINE: false,
>   botium-BotDriver   DOCKERIMAGE: 'node:boron',
>   botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
>   botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
>   botium-BotDriver   BOT_HEALTH_STATUS: 200,
>   botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
>   botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
>   botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
>   botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
>   botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
>   botium-BotDriver   SIMPLEREST_PING_RETRIES: 6,
>   botium-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
>   botium-BotDriver   SIMPLEREST_PING_VERB: 'GET',
>   botium-BotDriver   SIMPLEREST_METHOD: 'GET',
>   botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
>   botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
>   botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
>   botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_SPLIT: '\r',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
>   botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
>   botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
>   botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
>   botium-BotDriver   SCRIPTING_ENABLE_MEMORY: false,
>   botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
>   botium-BotDriver   ASSERTERS: [],
>   botium-BotDriver   LOGIC_HOOKS: [],
>   botium-BotDriver   CONTAINERMODE: 'google-actions',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_ID:
>   botium-BotDriver    '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_SECRET: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_REFRESH_TOKEN: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_TYPE: 'authorized_user',
>   botium-BotDriver   GOOGLE_ASSISTANT_START_UTTERANCE: 'Talk to my test app',
>   botium-BotDriver   GOOGLE_ASSISTANT_END_UTTERANCE: 'Cancel',
>   botium-BotDriver   CONFIG: './botium.json' } +0ms
>   botium-ScriptingProvider Using matching mode: includeLowerCase +0ms
>   botium-asserterUtils Loaded Default asserter - [ 'BUTTONS',
>   botium-asserterUtils   'MEDIA',
>   botium-asserterUtils   'PAUSE_ASSERTER',
>   botium-asserterUtils   'ENTITIES',
>   botium-asserterUtils   'ENTITY_VALUES',
>   botium-asserterUtils   'INTENT',
>   botium-asserterUtils   'INTENT_CONFIDENCE' ] +0ms
>   botium-asserterUtils Loaded Default logic hook - [ 'PAUSE', 'WAITFORBOT' ] +0ms
>   botium-BotDriver Build - Capabilites: { PROJECTNAME: 'Botium Project Google Assistant',
>   botium-BotDriver   TEMPDIR: 'botiumwork',
>   botium-BotDriver   CLEANUPTEMPDIR: true,
>   botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
>   botium-BotDriver   SIMULATE_WRITING_SPEED: false,
>   botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
>   botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
>   botium-BotDriver   DOCKERMACHINE: false,
>   botium-BotDriver   DOCKERIMAGE: 'node:boron',
>   botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
>   botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
>   botium-BotDriver   BOT_HEALTH_STATUS: 200,
>   botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
>   botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
>   botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
>   botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
>   botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
>   botium-BotDriver   SIMPLEREST_PING_RETRIES: 6,
>   botium-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
>   botium-BotDriver   SIMPLEREST_PING_VERB: 'GET',
>   botium-BotDriver   SIMPLEREST_METHOD: 'GET',
>   botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
>   botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
>   botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
>   botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_SPLIT: '\r',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
>   botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
>   botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
>   botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
>   botium-BotDriver   SCRIPTING_ENABLE_MEMORY: false,
>   botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
>   botium-BotDriver   ASSERTERS: [],
>   botium-BotDriver   LOGIC_HOOKS: [],
>   botium-BotDriver   CONTAINERMODE: 'google-actions',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_ID:
>   botium-BotDriver    '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_SECRET: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_REFRESH_TOKEN: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_TYPE: 'authorized_user',
>   botium-BotDriver   GOOGLE_ASSISTANT_START_UTTERANCE: 'Talk to my test app',
>   botium-BotDriver   GOOGLE_ASSISTANT_END_UTTERANCE: 'Cancel',
>   botium-BotDriver   CONFIG: './botium.json' } +207ms
>   botium-BotDriver Build - Sources : { LOCALPATH: '.',
>   botium-BotDriver   GITPATH: 'git',
>   botium-BotDriver   GITBRANCH: 'master',
>   botium-BotDriver   GITDIR: '.' } +1ms
>   botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +0ms
>   botium-PluginConnectorContainer Loading Botium plugin from google-actions failed - { Error: Cannot find module 'google-actions'
>   botium-PluginConnectorContainer     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>   botium-PluginConnectorContainer     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>   botium-PluginConnectorContainer     at Module.require (internal/modules/cjs/loader.js:637:17)
>   botium-PluginConnectorContainer     at require (internal/modules/cjs/helpers.js:22:18)
>   botium-PluginConnectorContainer     at tryLoadPlugin (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:16:20)
>   botium-PluginConnectorContainer     at Validate.Validate.then (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:45:29) code: 'MODULE_NOT_FOUND' } +0ms
>   botium-PluginConnectorContainer Loading Botium plugin botium-connector-google-actions failed, try "npm install botium-connector-google-actions" - { Error: Cannot find module 'botium-connector-google-actions'
>   botium-PluginConnectorContainer     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
>   botium-PluginConnectorContainer     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>   botium-PluginConnectorContainer     at Module.require (internal/modules/cjs/loader.js:637:17)
>   botium-PluginConnectorContainer     at require (internal/modules/cjs/helpers.js:22:18)
>   botium-PluginConnectorContainer     at tryLoadPlugin (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:29:20)
>   botium-PluginConnectorContainer     at Validate.Validate.then (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:45:29) code: 'MODULE_NOT_FOUND' } +0ms
>   botium-BotDriver BotDriver Build error: Error: Loading Botium plugin failed +10ms
> Error: Loading Botium plugin failed

Re-running `npm install botium-connector-google-actions` made no difference.

Other behavior:

- "CONTAINERMODE": is set to "google-assistant"  when running `./node_modules/.bin/botium-connector-google-assistant-init`, as opposed to the recommended "google-actions" mode in the [documentation](https://www.npmjs.com/package/botium-connector-google-assistant)
- The command `botium-cli init-google-assistant` resulted in a `Unknown argument: init-google-assistant`
- The command `botium-connector-google-actions-init` also resulted in a `command not found`
- The command `./node_modules/.bin/botium-connector-google-actions-init` had to be modified to `./node_modules/.bin/botium-connector-google-assistant-init` to run as noted above

Please let me know if I'm doing something wrong, I do appreciate your feedback & assistance! Thank you

**Comment by codeforequity-at** [comment]
hello, in short the documentation is partly wrong, we will fix this. the correct container mode is google-assistant

**Comment by codeforequity-at** [comment]
Documentation is updated.

**Comment by mahmeds7777** [comment]
@codeforequity-at Thank you for your prompt response!

I followed the updated documentation [here](https://github.com/codeforequity-at/botium-connector-google-assistant#how-it-works) and received this when I ran `botium-cli emulator`

I used the following commands for installation: 
> npm install -g botium-cli
> npm install -g botium-connector-google-assistant
> botium-cli init
> botium-cli run

Then ran `botium-connector-google-assistant-init` for setup. I get the same error when running `botium-connector-google-assistant-init` or `botium-clie emulator` as seen below:

CONTAINERMODE is set to `google-assistant` 

> $ botium-cli emulator -v
>   botium-cli Using Botium configuration file ./botium.json +0ms
>   botium-cli-emulator command options: { _: [ 'emulator' ],
>   botium-cli-emulator   help: false,
>   botium-cli-emulator   h: false,
>   botium-cli-emulator   version: false,
>   botium-cli-emulator   V: false,
>   botium-cli-emulator   v: true,
>   botium-cli-emulator   verbose: true,
>   botium-cli-emulator   convos: [ '.' ],
>   botium-cli-emulator   C: [ '.' ],
>   botium-cli-emulator   config: './botium.json',
>   botium-cli-emulator   c: './botium.json',
>   botium-cli-emulator   ui: 'console',
>   botium-cli-emulator   emulatorport: 3000,
>   botium-cli-emulator   '$0': '/usr/local/bin/botium-cli' } +0ms
>   botium-BotDriver Loaded Botium configuration file ./botium.json +0ms
>   botium-BotDriver Loaded Botium configuration file ./botium.json +1ms
>   botium-BotDriver Changed capability CONFIG to "./botium.json" using environment variables. +0ms
>   botium-BotDriver BuildCompiler: Capabilites: { PROJECTNAME: 'Botium Project Google Assistant',
>   botium-BotDriver   TEMPDIR: 'botiumwork',
>   botium-BotDriver   CLEANUPTEMPDIR: true,
>   botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
>   botium-BotDriver   SIMULATE_WRITING_SPEED: false,
>   botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
>   botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
>   botium-BotDriver   DOCKERMACHINE: false,
>   botium-BotDriver   DOCKERIMAGE: 'node:boron',
>   botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
>   botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
>   botium-BotDriver   BOT_HEALTH_STATUS: 200,
>   botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
>   botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
>   botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
>   botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
>   botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
>   botium-BotDriver   SIMPLEREST_PING_RETRIES: 6,
>   botium-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
>   botium-BotDriver   SIMPLEREST_PING_VERB: 'GET',
>   botium-BotDriver   SIMPLEREST_METHOD: 'GET',
>   botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
>   botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
>   botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
>   botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_SPLIT: '\r',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
>   botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
>   botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
>   botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
>   botium-BotDriver   SCRIPTING_ENABLE_MEMORY: false,
>   botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
>   botium-BotDriver   ASSERTERS: [],
>   botium-BotDriver   LOGIC_HOOKS: [],
>   botium-BotDriver   USER_INPUTS: [],
>   botium-BotDriver   CONTAINERMODE: 'google-assistant',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_ID:
>   botium-BotDriver    '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_SECRET: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_REFRESH_TOKEN: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_TYPE: 'authorized_user',
>   botium-BotDriver   GOOGLE_ASSISTANT_START_UTTERANCE: 'Talk to my test app',
>   botium-BotDriver   GOOGLE_ASSISTANT_END_UTTERANCE: 'Cancel',
>   botium-BotDriver   CONFIG: './botium.json' } +0ms
>   botium-ScriptingProvider Using matching mode: includeLowerCase +0ms
>   botium-asserterUtils Loaded Default asserter - [ 'BUTTONS',
>   botium-asserterUtils   'MEDIA',
>   botium-asserterUtils   'PAUSE_ASSERTER',
>   botium-asserterUtils   'ENTITIES',
>   botium-asserterUtils   'ENTITY_VALUES',
>   botium-asserterUtils   'INTENT',
>   botium-asserterUtils   'INTENT_CONFIDENCE' ] +0ms
>   botium-asserterUtils Loaded Default logic hook - [ 'PAUSE', 'WAITFORBOT' ] +1ms
>   botium-asserterUtils Loaded Default user input - [ 'BUTTON', 'MEDIA' ] +0ms
>   botium-BotDriver Build - Capabilites: { PROJECTNAME: 'Botium Project Google Assistant',
>   botium-BotDriver   TEMPDIR: 'botiumwork',
>   botium-BotDriver   CLEANUPTEMPDIR: true,
>   botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
>   botium-BotDriver   SIMULATE_WRITING_SPEED: false,
>   botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
>   botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
>   botium-BotDriver   DOCKERMACHINE: false,
>   botium-BotDriver   DOCKERIMAGE: 'node:boron',
>   botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
>   botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
>   botium-BotDriver   BOT_HEALTH_STATUS: 200,
>   botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
>   botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
>   botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
>   botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
>   botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
>   botium-BotDriver   SIMPLEREST_PING_RETRIES: 6,
>   botium-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
>   botium-BotDriver   SIMPLEREST_PING_VERB: 'GET',
>   botium-BotDriver   SIMPLEREST_METHOD: 'GET',
>   botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
>   botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
>   botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
>   botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_SPLIT: '\r',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
>   botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
>   botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
>   botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
>   botium-BotDriver   SCRIPTING_ENABLE_MEMORY: false,
>   botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
>   botium-BotDriver   ASSERTERS: [],
>   botium-BotDriver   LOGIC_HOOKS: [],
>   botium-BotDriver   USER_INPUTS: [],
>   botium-BotDriver   CONTAINERMODE: 'google-assistant',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_ID:
>   botium-BotDriver    '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_SECRET: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_REFRESH_TOKEN: '1***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_TYPE: 'authorized_user',
>   botium-BotDriver   GOOGLE_ASSISTANT_START_UTTERANCE: 'Talk to my test app',
>   botium-BotDriver   GOOGLE_ASSISTANT_END_UTTERANCE: 'Cancel',
>   botium-BotDriver   CONFIG: './botium.json' } +207ms
>   botium-BotDriver Build - Sources : { LOCALPATH: '.',
>   botium-BotDriver   GITPATH: 'git',
>   botium-BotDriver   GITBRANCH: 'master',
>   botium-BotDriver   GITDIR: '.' } +1ms
>   botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +0ms
>   botium-PluginConnectorContainer **Loading Botium plugin from google-assistant failed - { Error: Cannot find module 'google-assistant'
>   botium-PluginConnectorContainer     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)**
>   botium-PluginConnectorContainer     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>   botium-PluginConnectorContainer     at Module.require (internal/modules/cjs/loader.js:637:17)
>   botium-PluginConnectorContainer     at require (internal/modules/cjs/helpers.js:22:18)
>   botium-PluginConnectorContainer     at tryLoadPlugin (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:16:20)
>   botium-PluginConnectorContainer     at Validate.Validate.then (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:45:29) code: 'MODULE_NOT_FOUND' } +0ms
>   botium-PluginConnectorContainer Botium plugin botium-connector-google-assistant loaded +281ms
>   botium-connector-google-assistant Validate called +0ms
>   botium-connector-google-assistant Build called +1ms
>   botium-connector-google-assistant Start called +2ms
> (node:55266) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
> /usr/local/lib/node_modules/botium-connector-google-assistant/src/actions-on-google.js:301
>             : debugInfo.finalResponse.richResponse
>                                       ^
> 
> TypeError: Cannot read property 'richResponse' of undefined
>     at ClientDuplexStream.conversation.on (/usr/local/lib/node_modules/botium-connector-google-assistant/src/actions-on-google.js:301:39)
>     at ClientDuplexStream.emit (events.js:182:13)
>     at ClientDuplexStream.EventEmitter.emit (domain.js:441:20)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at ClientDuplexStream.Readable.push (_stream_readable.js:219:10)
>     at Object.onReceiveMessage (/usr/local/lib/node_modules/botium-connector-google-assistant/node_modules/grpc/src/client_interceptors.js:1292:19)
>     at InterceptingListener.recvMessageWithContext (/usr/local/lib/node_modules/botium-connector-google-assistant/node_modules/grpc/src/client_interceptors.js:607:19)
>     at /usr/local/lib/node_modules/botium-connector-google-assistant/node_modules/grpc/src/client_interceptors.js:706:14

Appreciate your feedback.
