### ISSUE TITLE
DialogFlow using Excel file

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-core#219]
Hi ,

Please provide us an example illustrating working on excel File connecting using dialog flow.
a. What are the capabilities required for excel file path  and sheet name and configuration to be made in botium.json?
b .Assert excel data with dialog-flow to validate data.
c. Creating intent and utterances in separate excel sheet of same file  and how to create variables in excel file for intent and utterances.

Thanks
Vijay

**Comment by codeforequity-at** [comment]
Hi, this is in our backlog for a long time now, definitely too long. I will update the "Botium in a nutshell" blog in the next days.

**Comment by vijaysimh** [comment]
Hi ,

Can you please share the supporting link and would be better if you provide
us video illustrating on working with excel files  as its too important

Thanks and Regards,
Vijay

**Comment by codeforequity-at** [comment]
Updated Botium Wiki with section and samples for Botium excel files
https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/48922649/Composing+in+Excel+files
