### ISSUE TITLE
TypeError: Cannot read property 'richResponse' of undefined with Google Assistant 

### ISSUE THREAD

**Issue by mahmeds7777** [codeforequity-at/botium-core#220]
@codeforequity-at 

Google Assistant's plugin fails to load for me.

I followed the updated documentation [here](https://github.com/codeforequity-at/botium-connector-google-assistant#how-it-works) but received an error when I ran `botium-cli emulator`

I used the following commands for installation: 
> npm install -g botium-cli
> npm install -g botium-connector-google-assistant
> botium-cli init
> botium-cli run

Then ran `botium-connector-google-assistant-init` for setup. I see the same error when running `botium-connector-google-assistant-init` or `botium-cli emulator`

CONTAINERMODE is set to `google-assistant` 

I see the same error on macOS & Windows10 (fresh installation) 
Error: 

> $ botium-cli emulator -v
>   botium-cli Using Botium configuration file ./botium.json +0ms
>   botium-cli-emulator command options: { _: [ 'emulator' ],
>   botium-cli-emulator   help: false,
>   botium-cli-emulator   h: false,
>   botium-cli-emulator   version: false,
>   botium-cli-emulator   V: false,
>   botium-cli-emulator   v: true,
>   botium-cli-emulator   verbose: true,
>   botium-cli-emulator   convos: [ '.' ],
>   botium-cli-emulator   C: [ '.' ],
>   botium-cli-emulator   config: './botium.json',
>   botium-cli-emulator   c: './botium.json',
>   botium-cli-emulator   ui: 'console',
>   botium-cli-emulator   emulatorport: 3000,
>   botium-cli-emulator   '$0': '/usr/local/bin/botium-cli' } +0ms
>   botium-BotDriver Loaded Botium configuration file ./botium.json +0ms
>   botium-BotDriver Loaded Botium configuration file ./botium.json +1ms
>   botium-BotDriver Changed capability CONFIG to "./botium.json" using environment variables. +0ms
>   botium-BotDriver BuildCompiler: Capabilites: { PROJECTNAME: 'Botium Project Google Assistant',
>   botium-BotDriver   TEMPDIR: 'botiumwork',
>   botium-BotDriver   CLEANUPTEMPDIR: true,
>   botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
>   botium-BotDriver   SIMULATE_WRITING_SPEED: false,
>   botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
>   botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
>   botium-BotDriver   DOCKERMACHINE: false,
>   botium-BotDriver   DOCKERIMAGE: 'node:boron',
>   botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
>   botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
>   botium-BotDriver   BOT_HEALTH_STATUS: 200,
>   botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
>   botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
>   botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
>   botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
>   botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
>   botium-BotDriver   SIMPLEREST_PING_RETRIES: 6,
>   botium-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
>   botium-BotDriver   SIMPLEREST_PING_VERB: 'GET',
>   botium-BotDriver   SIMPLEREST_METHOD: 'GET',
>   botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
>   botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
>   botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
>   botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_SPLIT: '\r',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
>   botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
>   botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
>   botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
>   botium-BotDriver   SCRIPTING_ENABLE_MEMORY: false,
>   botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
>   botium-BotDriver   ASSERTERS: [],
>   botium-BotDriver   LOGIC_HOOKS: [],
>   botium-BotDriver   USER_INPUTS: [],
>   botium-BotDriver   CONTAINERMODE: 'google-assistant',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_ID:
>   botium-BotDriver    '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_SECRET: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_REFRESH_TOKEN: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_TYPE: 'authorized_user',
>   botium-BotDriver   GOOGLE_ASSISTANT_START_UTTERANCE: 'Talk to my test app',
>   botium-BotDriver   GOOGLE_ASSISTANT_END_UTTERANCE: 'Cancel',
>   botium-BotDriver   CONFIG: './botium.json' } +0ms
>   botium-ScriptingProvider Using matching mode: includeLowerCase +0ms
>   botium-asserterUtils Loaded Default asserter - [ 'BUTTONS',
>   botium-asserterUtils   'MEDIA',
>   botium-asserterUtils   'PAUSE_ASSERTER',
>   botium-asserterUtils   'ENTITIES',
>   botium-asserterUtils   'ENTITY_VALUES',
>   botium-asserterUtils   'INTENT',
>   botium-asserterUtils   'INTENT_CONFIDENCE' ] +0ms
>   botium-asserterUtils Loaded Default logic hook - [ 'PAUSE', 'WAITFORBOT' ] +1ms
>   botium-asserterUtils Loaded Default user input - [ 'BUTTON', 'MEDIA' ] +0ms
>   botium-BotDriver Build - Capabilites: { PROJECTNAME: 'Botium Project Google Assistant',
>   botium-BotDriver   TEMPDIR: 'botiumwork',
>   botium-BotDriver   CLEANUPTEMPDIR: true,
>   botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
>   botium-BotDriver   SIMULATE_WRITING_SPEED: false,
>   botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
>   botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
>   botium-BotDriver   DOCKERMACHINE: false,
>   botium-BotDriver   DOCKERIMAGE: 'node:boron',
>   botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
>   botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
>   botium-BotDriver   BOT_HEALTH_STATUS: 200,
>   botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
>   botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
>   botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
>   botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
>   botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
>   botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
>   botium-BotDriver   SIMPLEREST_PING_RETRIES: 6,
>   botium-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
>   botium-BotDriver   SIMPLEREST_PING_VERB: 'GET',
>   botium-BotDriver   SIMPLEREST_METHOD: 'GET',
>   botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
>   botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
>   botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
>   botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_SPLIT: '\r',
>   botium-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
>   botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
>   botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
>   botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
>   botium-BotDriver   SCRIPTING_ENABLE_MEMORY: false,
>   botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
>   botium-BotDriver   SCRIPTING_UTTEXPANSION_INCOMPREHENSION: 'INCOMPREHENSION',
>   botium-BotDriver   ASSERTERS: [],
>   botium-BotDriver   LOGIC_HOOKS: [],
>   botium-BotDriver   USER_INPUTS: [],
>   botium-BotDriver   CONTAINERMODE: 'google-assistant',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_ID:
>   botium-BotDriver    '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_CLIENT_SECRET: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_REFRESH_TOKEN: '***redacted***',
>   botium-BotDriver   GOOGLE_ASSISTANT_TYPE: 'authorized_user',
>   botium-BotDriver   GOOGLE_ASSISTANT_START_UTTERANCE: 'Talk to my test app',
>   botium-BotDriver   GOOGLE_ASSISTANT_END_UTTERANCE: 'Cancel',
>   botium-BotDriver   CONFIG: './botium.json' } +207ms
>   botium-BotDriver Build - Sources : { LOCALPATH: '.',
>   botium-BotDriver   GITPATH: 'git',
>   botium-BotDriver   GITBRANCH: 'master',
>   botium-BotDriver   GITDIR: '.' } +1ms
>   botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +0ms
>   botium-PluginConnectorContainer **Loading Botium plugin from google-assistant failed - { Error: Cannot find module 'google-assistant'
>   botium-PluginConnectorContainer     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)**
>   botium-PluginConnectorContainer     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
>   botium-PluginConnectorContainer     at Module.require (internal/modules/cjs/loader.js:637:17)
>   botium-PluginConnectorContainer     at require (internal/modules/cjs/helpers.js:22:18)
>   botium-PluginConnectorContainer     at tryLoadPlugin (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:16:20)
>   botium-PluginConnectorContainer     at Validate.Validate.then (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/containers/PluginConnectorContainer.js:45:29) code: 'MODULE_NOT_FOUND' } +0ms
>   botium-PluginConnectorContainer Botium plugin botium-connector-google-assistant loaded +281ms
>   botium-connector-google-assistant Validate called +0ms
>   botium-connector-google-assistant Build called +1ms
>   botium-connector-google-assistant Start called +2ms
> (node:55266) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
> /usr/local/lib/node_modules/botium-connector-google-assistant/src/actions-on-google.js:301
>             : debugInfo.finalResponse.richResponse
>                                       ^
> 
> TypeError: Cannot read property 'richResponse' of undefined
>     at ClientDuplexStream.conversation.on (/usr/local/lib/node_modules/botium-connector-google-assistant/src/actions-on-google.js:301:39)
>     at ClientDuplexStream.emit (events.js:182:13)
>     at ClientDuplexStream.EventEmitter.emit (domain.js:441:20)
>     at addChunk (_stream_readable.js:283:12)
>     at readableAddChunk (_stream_readable.js:264:11)
>     at ClientDuplexStream.Readable.push (_stream_readable.js:219:10)
>     at Object.onReceiveMessage (/usr/local/lib/node_modules/botium-connector-google-assistant/node_modules/grpc/src/client_interceptors.js:1292:19)
>     at InterceptingListener.recvMessageWithContext (/usr/local/lib/node_modules/botium-connector-google-assistant/node_modules/grpc/src/client_interceptors.js:607:19)
>     at /usr/local/lib/node_modules/botium-connector-google-assistant/node_modules/grpc/src/client_interceptors.js:706:14

Appreciate your feedback.

**Comment by codeforequity-at** [comment]
Botium tries to load a plugin reference from several locations, so this error message means nothing. A few lines below, you can read:

    botium-PluginConnectorContainer Botium plugin botium-connector-google-assistant loaded +281ms

So this is ok. The following error is another problem:

    TypeError: Cannot read property 'richResponse' of undefined

@ujja will look into that.

**Comment by ujja** [comment]
Unfortunately error coming before reaching our code, we dont see anything in log.

Could you say what is the response of your action? Plain text/other component/speech/other state change? Or can you send some code? Do you have surface dependent code? Any special setting on action?

FYI: we support now just text responses. Everything else is dropped.

**Comment by mahmeds7777** [comment]
@ujja Our action has a speech and text response. There are no state changes, just simple text and speech responses. We support: phone, voice, and surface devices. 

I can send you the googleConfig file securely, but I'm not sure how if you'd like for debugging purposes.

**Comment by mahmeds7777** [comment]
@ujja @codeforequity-at Thank you, I've had a chance to look further into this issue, and it was an issue on our backend service. 

I just had 2 follow-up questions:

1) What approach do you recommend for writing Test Cases / validating the responses against Google Assistant

2) How do I switch between the text & speech response for the action?

Thank you

**Comment by ujja** [comment]
@mahmeds7777 You are welcome.

1. Did you read the [Botium in a Nutshell](https://medium.com/@floriantreml/botium-in-a-nutshell-part-1-overview-f8d0ceaf8fb4) articles? There is nothing special with Google Assistant, except Account Linking. 
2. Currently we support just text messages. No switch, no speech response. We plan to support other components, like carousel. We could support speech too, but with a text to speech service, what is not free. And thats all, we dont have other plans with Google Assistant. Please requests into other issue.

**Comment by ujja** [comment]
@mahmeds7777 could you say please what the problem was? It is good that an external error causes exception in our code.

**Comment by mahmeds7777** [comment]
@ujja Thank you for the feedback, I really do appreciate it. I did read the Botium in a Nutshell articles, however, there's is not much documentation regarding how to setup MS Excel's utterances, but I see that said concern has already been raised at issue#219.

As for what caused the error, we had an problem with Account Linking on our backend, so the service was returning an undefined response since it wasn't able to connect.
