### ISSUE TITLE
transcript error- error sending to bot Error: Skill simulation for simulation id xzxxxxxxx returned failure

### ISSUE THREAD

**Issue by krishnasaikumarraju** [codeforequity-at/botium-core#222]
Issue faced (command : node botium.js) :
![image](https://user-images.githubusercontent.com/42143138/52579235-c55ad500-2e4b-11e9-9a08-7d8af0e008d1.png)
package.json(file):
![image](https://user-images.githubusercontent.com/42143138/52579383-0ce16100-2e4c-11e9-831c-fe238839702d.png)
botium.json(file):
![image](https://user-images.githubusercontent.com/42143138/52579486-42864a00-2e4c-11e9-901b-637083b6a2af.png)
botium.js(file):
![image](https://user-images.githubusercontent.com/42143138/52579611-7d887d80-2e4c-11e9-8e99-cd94a2bd04a4.png)

Expectations:
Please sort out the issue and if in case i was not following the proper procedure to work on smapi module please suggest me the proper documented Url by that way i can make sure of this issue.

**Comment by codeforequity-at** [comment]
Pls attach debug output (DEBUG=botium* node botium.js)

**Comment by krishnasaikumarraju** [comment]
command(DEBUG=botium* node botium.js):
![image](https://user-images.githubusercontent.com/42143138/52627351-2978aa00-2edb-11e9-99b3-e2f4c5c6a522.png)

**Comment by ujja** [comment]
It does not looks correct in botium.json?

ALEXA_SMAPI_LOCALE="de_DE"

Is german supported by your interaction model?

**Comment by krishnasaikumarraju** [comment]
Sorry, Team i didnt checked locale properly and as well a very helpful Thanks to the botium team,  For supporting me and giving immediate reply's to my issues.

Thanks&Regards
krishna sai

**Comment by krishnasaikumarraju** [comment]
Hii, 
1. Any command to import alexa skill intents (i.e botium-cli import smapi-conversations). That is how we use import dialog flow intents (i.e botium-cli import dialogflow-conversations).
2. Any command is available to store logs.

**Comment by codeforequity-at** [comment]
1. No there is currently no command available to do this. I added it to our backlog, but to be honest it is currently not priorized very high.

2. What logs do you mean ?

**Comment by krishnasaikumarraju** [comment]
>     2. What logs do you mean ?

1. While running the testcases if any of the testcase got failed while comparing the content( i.e bot response ) the failed scenarios should get captured( as a logs ).

2. One more question is like if any of the test case is failed while comparing the content( i.e bot response ) and by the way it is stopping at that point it is not testing for the next scenario

**Comment by codeforequity-at** [comment]
Take a look at Botium-Bindings, Botium CLI or Botium Box.

**Comment by krishnasaikumarraju** [comment]
Hi,
Both Redis labs and prisma both are paid versions right, Is there any sample free version to test at intial stages ( i.e to test a single skill ).

If there is possibility to work on trial versions can you please suggest me any kind of reference link to work out on that.

**Comment by codeforequity-at** [comment]
https://github.com/codeforequity-at/botium-box-basic-dist#prerequisites

**Comment by krishnasaikumarraju** [comment]
> https://github.com/codeforequity-at/botium-box-basic-dist#prerequisites

Is it available for free to run a sample demo alexa skill

**Comment by codeforequity-at** [comment]
yes

**Comment by codeforequity-at** [comment]
@krishnasaikumarraju we recently worked on an extension to import the Alexa intent utterances into Botium, see https://github.com/codeforequity-at/botium-connector-alexa-smapi/tree/feature/BOT-423-connector-alexa-smapi-import-int
