### ISSUE TITLE
Not able to start docker container

### ISSUE THREAD

**Issue by hitesh22nov** [codeforequity-at/botium-core#224]
Hi,
I am new to botium. 
While running facebook sample, I am getting the following error:
D:\ChatAuto\BotiumCoreLatest\botium-core-master\samples\connectors\docker\facebook> node botiumFluent.js
ERROR:  Error: Start failed 'Cannot start docker containers: Error: docker-compose returned error code 1\n    at ChildProcess.runningProcess.on (D:\\ChatAuto\\BotiumCoreLatest\\botium-core-master\\src\\helpers\\ProcessUtils.js:40:18)\n    at ChildProcess.emit (events.js:189:13)\n    at maybeClose (internal/child_process.js:970:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)'
    at async.series (D:\ChatAuto\BotiumCoreLatest\botium-core-master\src\containers\DockerContainer.js:400:25)
    at D:\ChatAuto\BotiumCoreLatest\botium-core-master\node_modules\async\dist\async.js:3888:9
    at D:\ChatAuto\BotiumCoreLatest\botium-core-master\node_modules\async\dist\async.js:473:16
    at iterateeCallback (D:\ChatAuto\BotiumCoreLatest\botium-core-master\node_modules\async\dist\async.js:988:17)
    at D:\ChatAuto\BotiumCoreLatest\botium-core-master\node_modules\async\dist\async.js:969:16
    at D:\ChatAuto\BotiumCoreLatest\botium-core-master\node_modules\async\dist\async.js:3885:13
    at dockerCmd.startContainer.then.catch (D:\ChatAuto\BotiumCoreLatest\botium-core-master\src\containers\DockerContainer.js:369:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Docker is installed in my machine.

Also, I am facing another issues with botframework in samples>Container>Docker
The following capabilities need to be derived from where(Azure?)
 "BOTFRAMEWORK_APP_ID": "19b4b278-4b77-4769-bb2f-1e610851f2d7",
"appId\"
"mymicrosoftappid\"
Also, if we are fetching code from GIT, then whats the need of mymicrosoftappid and appid, as we are running code in docker. I just want to understand the concept as I want to automate testing of chatbots.

Thanks in Advance

**Comment by codeforequity-at** [comment]
Botium's docker mode is both experimental and deprecated. We don't recommend using it, in most cases there are better options.

The appid is handed over to the docker container running the bot code as environment variable. As the goal for this connector was to encapsulate the bot code within a docker network and prevent any contact to the azure servers, you can basically use anything you want, or just leave the default.
