### ISSUE TITLE
BUTTON custom identifiers

### ISSUE THREAD

**Issue by xmichele** [codeforequity-at/botium-core#225]
Dear Team, 

I have tried the nice and recent BUTTON click feature in the convo txt file.
I'm using last botium-cli and webdriverio container mode. 
From what I've seen, the button are identified bt "title" html property. Is it true?
My question: is it possible simulate BUTTON click by using, instead of the exact title, some string patterns about the title (i.e. startsWith, endsWith, contains ecc..) 

Thanks

**Comment by codeforequity-at** [comment]
hello, this is the selector, it means that there is substring matching on the title attribute done:

const qrSelector = `button[title*='${msg.buttons[0].text}']:not(:disabled)`

**Comment by xmichele** [comment]
Ok, thanks. And use alternative properties than "title"

**Comment by codeforequity-at** [comment]
you can just add your own function snippet if the existing predefined functionality doesnt match your bot .... i added this question to our backlog, good one.

**Comment by codeforequity-at** [comment]
In this stackoverflow-article you can see how a rather smart guy did exactly this: https://stackoverflow.com/questions/54645876/overriding-actions-for-botium-webdriverio-connector/54685047

**Comment by xmichele** [comment]
Ok, looking into it. Thanks

**Comment by oferdan** [comment]
I have also encountered this problem with finding buttons to be clicked by just title. Maybe I am missing something but wouldn't it be better to search for buttons by elementIdText, same as it is asserting them in bot's responses? It seem to be overkill to rewrite functions. Sorry for reopening.

**Comment by codeforequity-at** [comment]
yes, that's a good point. it is already in our backlog to make the selectors more flexible. cannot tell for now when it will make it into a sprint planning. contributions are welcome, if you are good with selenium/webdriver ...

**Comment by oferdan** [comment]
Looking into documentation (http://v4.webdriver.io/v3.4/guide/usage/selectors.html - Element with certain text) looks like: 
``const qrSelector = `button*=${msg.buttons[0].text}` ``
 would do?

**Comment by codeforequity-at** [comment]
both are fine, and there should be an option to configure them as needed. Botium has some reasonable defaults included, but they clearly don't match any possible situations.
