### ISSUE TITLE
Agent not recognized properly in Botium

### ISSUE THREAD

**Issue by balasundarbala** [codeforequity-at/botium-core#227]
I am using Botium to validate dialog flow  Intents and Training phrases. I have 3 agents in my dialog flow account. In which one agent only recognizing all the intents properly.others are not. Mostly the intents using fulfillment responses not recognized.It always calling default falback intent.

Can you help me to solve this issue ?

**Comment by codeforequity-at** [comment]
pls use stackoverflow for questions. i recommend to check the language code for your agents and botium.
