### ISSUE TITLE
Documentation for simplerest

### ISSUE THREAD

**Issue by akshayCha** [codeforequity-at/botium-core#23]
Could you possibly give a small bit of documentation regarding the different capabilities for Simple rest and what each of them mean? I am new to using applications like postman and I need to test a chatbot.

**Comment by codeforequity-at** [comment]
I added some documentation to the Wiki pages:
https://github.com/codeforequity-at/botium-core/wiki/Botium-Configuration#capabilities-for-operation-mode-simplerest

I hope this is useful for you. If you have troubles setting it up, maybe I can assist.

**Comment by akshayCha** [comment]
Thanks for the documentation, I'll try to test my bot and let you know if I run into any problems

**Comment by akshayCha** [comment]
This is my code. 

const BotDriver = require('botium-core').BotDriver
const Capabilities = require('botium-core').Capabilities
const Source = require('botium-core').Source

function assert (expected, actual) {
  if (!actual || actual.indexOf(expected) < 0) {
    console.log(`ERROR: Expected <${expected}>, got <${actual}>`)
  } else {
    console.log(`SUCCESS: Got Expected <${expected}>`)
  }
}

const driver = new BotDriver()
  .setCapability(Capabilities.PROJECTNAME, 'Delta-Chatomate')
  .setCapability(Capabilities.CONTAINERMODE, 'simplerest')
  .setCapability(Capabilities.SIMPLEREST_URL, 'https://delta-chatomate.herokuapp.com/bot/')
  .setCapability(Capabilities.SIMPLEREST_METHOD, 'POST')
  .setCapability(Capabilities.SIMPLEREST_BODY_TEMPLATE, {
   "userUtterance": "{{msg.messageText}}",
   "sender": "765757765"
  })
  .setCapability(Capabilities.SIMPLEREST_HEADERS_TEMPLATE, '{ "Content-Type": "application/x-www-form-urlecoded" }')
  .setCapability(Capabilities.SIMPLEREST_CONTEXT_JSONPATH, '$')
  .setCapability(Capabilities.SIMPLEREST_RESPONSE_JSONPATH, '$.utterance.*')

driver.BuildFluent()
  .Start()
  .UserSaysText('Hello there')
  .WaitBotSaysText((text) => assert('Hello there. I am ChatomateBot.', text))
  .UserSaysText('What can you do?')
  .WaitBotSaysText((text) => assert('I can help you learn about Chatomate. If you have questions, fire away.', text))
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })

This is a screenshot from Postman. I'm not sure what I am doing wrong here.

<img width="1272" alt="screen shot 2018-04-03 at 04 23 09" src="https://user-images.githubusercontent.com/15046617/38227585-d33c3378-36f6-11e8-876b-6d4c98f90782.png">

**Comment by codeforequity-at** [comment]
I see what's the problem - you did everything right, but posting body as x-www-form-urlecoded is not supported right now, just json. 

If you know javascript (I suppose you do), you could add the required code in file: 
https://github.com/codeforequity-at/botium-core/blob/master/src/containers/SimpleRestContainer.js, function "_buildRequest" at the bottom. Shouldn't be hard to do.

**Comment by akshayCha** [comment]
Thanks for your response. I'm not very sure what to change, can you perhaps guide me a bit? Thanks

**Comment by codeforequity-at** [comment]
In this function the HTTP request content is composed. Currently, body is hardcoded to always use JSON. With some small changes, the HTTP request content can be changed to x-www-form-urlencoded

**Comment by codeforequity-at** [comment]
Are you ok if I use your endpoint for adding this feature today ? You are not the first one asking for it, so I think it is time to add it ...

**Comment by akshayCha** [comment]
Yes you can use my endpoint for adding this feature. I would really appreciate it and it would be really helpful.

**Comment by akshayCha** [comment]
Thanks a lot for your help! Thanks for adding those features!
