### ISSUE TITLE
General Query on  Automation Frameworks

### ISSUE THREAD

**Issue by mangeshkhaire14** [codeforequity-at/botium-core#231]
Hi,

I know this is not forum for this question but just want suggestion on choosing the correct automation framework, the application is going to built on Node.js and React which is Widget based single page application. I am bit confused which framework/tools I should use for it. I have following questions in mind

1.  Whether we use Robot Framework - does it have market value today
2. Can protractor supports for react applications or it is only for angular
3.  Selenium with java testng  
Which will be the best option considering the application(Widget based single page application build on Node.js, React, java backend)

Please don't ignore this post you suggestions will helpme alot

Thanks,
Mangesh

**Comment by codeforequity-at** [comment]
We are not experts in those fields, stackoverflow community will be lot more helpful for these questions.
