### ISSUE TITLE
Alexa AVS- My skill gives more than one welcome messages randomly. Is there any way to verify it?

### ISSUE THREAD

**Issue by ChampNBM** [codeforequity-at/botium-core#233]
Alexa AVS- My skill gives more than one welcome messages randomly. Is there any way to verify it?

**Comment by ujja** [comment]
Please read https://medium.com/@floriantreml/botium-in-a-nutshell-part-2-writing-chatbot-tests-8726204c8da6

BOT_GREETING_UTT can help you
