### ISSUE TITLE
i am using botium any try to connect chatbot by IBM watson but, "Loading workspaces failed: Missing 'version' query parameter" - how to resolve this issue? 

### ISSUE THREAD

**Issue by shubham8121996** [codeforequity-at/botium-core#234]
**Is your feature request related to a problem? Please describe.**
![capture e](https://user-images.githubusercontent.com/47881127/53224948-70655d00-369c-11e9-8411-482c31c53106.PNG)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by codeforequity-at** [comment]
This is a known bug with Watson and will be resolved with Botium Box 1.3
