### ISSUE TITLE
botium-webdriverio-connector screenshots not working for samples\custom scripts

### ISSUE THREAD

**Issue by chrisgomez** [codeforequity-at/botium-core#236]
**Describe the bug**
Using the samples\custom scripts with setting "WEBDRIVERIO_SCREENSHOTS": "onstop", screenshots are never taken. The same behavior exists for all other "WEBDRIVERIO_SCREENSHOTS" values. 

The _takeScreenshot() function appears to be missing the writeFile method. I've modified this method so that it works and writes the screen shot to the local directory but I'm unsure if this is the correct coarse for the framework.

**To Reproduce**
Using botium-connector-webdriver
Set "WEBDRIVERIO_SCREENSHOTS" = onStop
Execute test script within the samples\custom folder

**Expected behavior**
A screenshot should be written to the local directory

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by codeforequity-at** [comment]
This works as expected. The screenshots are not saved into the current folder but attached to the Botium message - Botium Box will extract them and show in the test report.
But I agree, there should be an option to just dump them to a local directory. 
Currently, when running in debug mode, and something fails, then a screenshot will be dumped to the local directory - but only if failing.
