### ISSUE TITLE
Undocumented DIRECTLINE3_GENERATE_USERNAME for directline3 connector

### ISSUE THREAD

**Issue by alopix** [codeforequity-at/botium-core#239]
There's a DIRECTLINE3_GENERATE_USERNAME config option for the directline3 connector but it is not documented in the corresponding README file.
We found out about it when pocking around the source after having issues with the state not properly being reset between tests using the default.

Would be nice to have this documented for future adopters.

**Comment by codeforequity-at** [comment]
Done :-)
https://github.com/codeforequity-at/botium-connector-directline3#directline3_generate_username
