### ISSUE TITLE
How emulate user storage with dialogflow in Botium

### ISSUE THREAD

**Issue by Symfomany** [codeforequity-at/botium-core#243]
**Describe the bug**
i try uterrance with user storage in Dialogflow with "conv.user.storage" but it's failed... How emulate session/storage in my case? 

**To Reproduce**
i try uterrance with user storage in Dialogflow with "conv.user.storage" but it's failed... How emulate session/storage in my case?

**Comment by codeforequity-at** [comment]
Pls attach configuration (botium.json) and log output (enable verbose mode). Take care to mask any secret information in the files.

**Comment by Symfomany** [comment]
This is my botium.json

`{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "Dialogflow Sample Test",
      "CONTAINERMODE": "dialogflow",
      "DIALOGFLOW_LANGUAGE_CODE": "fr",
      "DIALOGFLOW_PROJECT_ID": "hsv-taiwa",
      "DIALOGFLOW_CLIENT_EMAIL": "hsv-taiwa@appspot.gserviceaccount.com",
      "DIALOGFLOW_PRIVATE_KEY": "XXXX",
      "DIALOGFLOW_INPUT_CONTEXT_LIFESPAN": 2,
      "DIALOGFLOW_INPUT_CONTEXT_NAME": "testmode",
      "DIALOGFLOW_USE_INTENT": true,
      "DIALOGFLOW_INPUT_CONTEXT_PARAMETERS": {
        "IsBotiumTest": true
      },
      "SCRIPTING_ENABLE_MEMORY": true
    },
    "Sources": {},
    "Envs": {
      "NODE_ENV": "prod"
    }
  }
}
`

I have an intent with context "ResultatDiagIntent-followup" to be able to jump tree intents in standalone intent. Botium bot response is empty... It's freemium version?

**Comment by codeforequity-at** [comment]
Botium Box is "Freemium", but in the connectors there is absolutely no difference between the community edition and the commercial editions.

thanks for the botium.json - please let it run in verbose mode and attach the logfile here (or send it by email if you don't want to see it public).

**Comment by Symfomany** [comment]
Yes this is log in verbose...

`
botium-Convo Context Test/Default-Welcome-Intent_input-L1 wait for bot null +297ms
  botium-Convo Context Test/Default-Welcome-Intent_input-L1: bot says {
  botium-Convo   "sender": "bot",
  botium-Convo   "sourceData": {
  botium-Convo     "fulfillmentMessages": [
  botium-Convo       {
  botium-Convo         "platform": "ACTIONS_ON_GOOGLE",
  botium-Convo         "simpleResponses": {
  botium-Convo           "simpleResponses": [
  botium-Convo             {
  botium-Convo               "textToSpeech": "D'accord. Êtes-vous client HomeServe ?",
  botium-Convo               "ssml": "",
  botium-Convo               "displayText": ""
  botium-Convo             }
  botium-Convo           ]
  botium-Convo         },
  botium-Convo         "message": "simpleResponses"
  botium-Convo       },
  botium-Convo       {
  botium-Convo         "platform": "PLATFORM_UNSPECIFIED",
  botium-Convo         "text": {
  botium-Convo           "text": [
  botium-Convo             ""
  botium-Convo           ]
  botium-Convo         },
  botium-Convo         "message": "text"
  botium-Convo       }
  botium-Convo     ],
  botium-Convo     "outputContexts": [
  botium-Convo       {
  botium-Convo         "name": "projects/hsv-taiwa/agent/sessions/c1627930-4a0c-11e9-a307-b1e5d63c7f6c/contexts/resultatdiagintent-followup",
  botium-Convo         "lifespanCount": 1,
  botium-Convo         "parameters": {
  botium-Convo           "fields": {}
  botium-Convo         }
  botium-Convo       },
  botium-Convo       {
  botium-Convo         "name": "projects/hsv-taiwa/agent/sessions/c1627930-4a0c-11e9-a307-b1e5d63c7f6c/contexts/plombintent-followup-2",
  botium-Convo         "lifespanCount": 2,
  botium-Convo         "parameters": {
  botium-Convo           "fields": {
  botium-Convo             "gaz.original": {
  botium-Convo               "kind": "stringValue",
  botium-Convo               "stringValue": "gaz"
  botium-Convo             },
  botium-Convo             "gaz": {
  botium-Convo               "kind": "stringValue",
  botium-Convo               "stringValue": "gaz"
  botium-Convo             }
  botium-Convo           }
  botium-Convo         }
  botium-Convo       },
  botium-Convo       {
  botium-Convo         "name": "projects/hsv-taiwa/agent/sessions/c1627930-4a0c-11e9-a307-b1e5d63c7f6c/contexts/testmode",
  botium-Convo         "lifespanCount": 196,
  botium-Convo         "parameters": {
  botium-Convo           "fields": {
  botium-Convo             "gaz": {
  botium-Convo               "kind": "stringValue",
  botium-Convo               "stringValue": "gaz"
  botium-Convo             },
  botium-Convo             "gaz.original": {
  botium-Convo               "kind": "stringValue",
  botium-Convo               "stringValue": "gaz"
  botium-Convo             }
  botium-Convo           }
  botium-Convo         }
  botium-Convo       },
  botium-Convo       {
  botium-Convo         "name": "projects/hsv-taiwa/agent/sessions/c1627930-4a0c-11e9-a307-b1e5d63c7f6c/contexts/gazyesintent-followup",
  botium-Convo         "lifespanCount": 1,
  botium-Convo         "parameters": {
  botium-Convo           "fields": {}
  botium-Convo         }
  botium-Convo       },
  botium-Convo       {
  botium-Convo         "name": "projects/hsv-taiwa/agent/sessions/c1627930-4a0c-11e9-a307-b1e5d63c7f6c/contexts/resultatdiagintent-yes-followup",
  botium-Convo         "lifespanCount": 2,
  botium-Convo         "parameters": {
  botium-Convo           "fields": {}
  botium-Convo         }
  botium-Convo       }
  botium-Convo     ],
  botium-Convo     "queryText": "oui",
  botium-Convo     "speechRecognitionConfidence": 0,
  botium-Convo     "action": "ResultatDiagIntent.ResultatDiagIntent-yes",
  botium-Convo     "parameters": {
  botium-Convo       "fields": {}
  botium-Convo     },
  botium-Convo     "allRequiredParamsPresent": true,
  botium-Convo     "fulfillmentText": "",
  botium-Convo     "webhookSource": "",
  botium-Convo     "webhookPayload": null,
  botium-Convo     "intent": {
  botium-Convo       "inputContextNames": [],
  botium-Convo       "events": [],
  botium-Convo       "trainingPhrases": [],
  botium-Convo       "outputContexts": [],
  botium-Convo       "parameters": [],
  botium-Convo       "messages": [],
  botium-Convo       "defaultResponsePlatforms": [],
  botium-Convo       "followupIntentInfo": [],
  botium-Convo       "name": "projects/hsv-taiwa/agent/intents/190c5db6-a3fe-46f6-9a12-c47ebf0d520e",
  botium-Convo       "displayName": "ResultatDiagIntent - yes",
  botium-Convo       "priority": 0,
  botium-Convo       "isFallback": false,
  botium-Convo       "webhookState": "WEBHOOK_STATE_UNSPECIFIED",
  botium-Convo       "action": "",
  botium-Convo       "resetContexts": false,
  botium-Convo       "rootFollowupIntentName": "",
  botium-Convo       "parentFollowupIntentName": "",
  botium-Convo       "mlDisabled": false
  botium-Convo     },
  botium-Convo     "intentDetectionConfidence": 0.75,
  botium-Convo     "diagnosticInfo": null,
  botium-Convo     "languageCode": "fr"
  botium-Convo   },
  botium-Convo   "nlp": {
  botium-Convo     "intent": {
  botium-Convo       "name": "ResultatDiagIntent - yes",
  botium-Convo       "confidence": 0.75
  botium-Convo     },
  botium-Convo     "entities": []
  botium-Convo   },
  botium-Convo   "messageText": "",
  botium-Convo   "channel": "default"
  botium-Convo } +32ms
  botium-ScriptingProvider assertBotResponse Context Test/Default-Welcome-Intent_input-L1/Line 24 (Line 21: #me - oui) BOT:  = client ... +356ms
  botium-cli-run Context Test/Default-Welcome-Intent_input-L1 failed: { TranscriptError: Error: Context Test/Default-Welcome-Intent_input-L1/Line 24: Expected bot response (on Line 21: #me - oui) "" to match one of "client"
  botium-cli-run     at async.waterfall (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:177:25)
  botium-cli-run     at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:473:16
  botium-cli-run     at next (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:5329:29)
  botium-cli-run     at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:969:16
  botium-cli-run     at runConversation (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:161:15)
  botium-cli-run     at async.mapSeries (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:346:9)
  botium-cli-run     at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:1140:9
  botium-cli-run     at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:473:16
  botium-cli-run     at iterateeCallback (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:988:17)
  botium-cli-run     at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:969:16
  botium-cli-run   name: 'TranscriptError',
  botium-cli-run   transcript:
  botium-cli-run    Transcript {
  botium-cli-run      steps:
  botium-cli-run       [ [TranscriptStep],
  botium-cli-run         [TranscriptStep],
  botium-cli-run         [TranscriptStep],
  botium-cli-run         [TranscriptStep],
  botium-cli-run         [TranscriptStep],
  botium-cli-run         [TranscriptStep],
  botium-cli-run         [TranscriptStep],
  botium-cli-run         [TranscriptStep] ],
  botium-cli-run      scriptingMemory: {},
  botium-cli-run      convoBegin: 2019-03-19T06:03:48.343Z,
  botium-cli-run      convoEnd: 2019-03-19T06:03:53.119Z,
  botium-cli-run      err:
  botium-cli-run       Error: Context Test/Default-Welcome-Intent_input-L1/Line 24: Expected bot response (on Line 21: #me - oui) "" to match one of "client"
  botium-cli-run           at ScriptingProvider.assertBotResponse (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\ScriptingProvider.js:81:17)
  botium-cli-run           at scriptingEvents.onBotStart.then.then (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:296:42) } } +5s
    1) Context Test/Default-Welcome-Intent_input-L1
  botium-connector-dialogflow Stop called +120ms
  botium-connector-dialogflow Clean called +2ms
  botium-BaseContainer Cleanup rimrafing temp dir C:\Users\boyer\Desktop\node_ibm\emulator\botiumwork\Dialogflow-Sample-Test-20190319-070344-vdp86 +0ms


  0 passing (9s)
  1 failing

  1) Botium Test-Suite
       Context Test/Default-Welcome-Intent_input-L1:
     TranscriptError: Error: Context Test/Default-Welcome-Intent_input-L1/Line 24: Expected bot response (on Line 21: #me - oui) "" to match one of "client"
      at async.waterfall (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:177:25)
      at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:473:16
      at next (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:5329:29)
      at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:969:16
      at runConversation (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:161:15)
      at async.mapSeries (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\scripting\Convo.js:346:9)
      at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:1140:9
      at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:473:16
      at iterateeCallback (C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:988:17)
      at C:\Users\boyer\AppData\Roaming\npm\node_modules\botium-cli\node_modules\async\dist\async.js:969:16

`

It's works on my Google Assistant and Simulator of Action on, google...

What are advantages for my client to switch premium plans? More tools? More speed?

**Comment by Symfomany** [comment]
Same error on Botium Emulator or Botium Emulator Browser...

**Comment by Symfomany** [comment]
Second question: "Cannot display response in Dialogflow simulator. Please test on the Google Assistant simulator instead." How emulate the response message in Botium?

**Comment by codeforequity-at** [comment]
You should set the DIALOGFLOW_OUTPUT_PLATFORM capability to ACTIONS_ON_GOOGLE (https://github.com/codeforequity-at/botium-connector-dialogflow#dialogflow_output_platform).

When developing Actions on Google, you should better use the Botium Google Assistant connector (https://github.com/codeforequity-at/botium-connector-google-assistant)

**Comment by Symfomany** [comment]
Can you help me to install and configure because on the document i have somes errors.Please send me an email on j.boyer69003@gmail.com
