### ISSUE TITLE
any way to connect/test locally running bots (based on Microsoft Bot Framework) through Botium ?

### ISSUE THREAD

**Issue by Anant13579** [codeforequity-at/botium-core#244]
Hi,

Although I am able to connect/test our bots hosted on Azure through Botium using DirectLine connector, I am not able to connect/test our locally running bots.

Is there any way using Botium by which I may connect/test locally running bots (based on Microsoft Bot Framework) ? If yes, can you please point out to the exact documentation for the reference ?

Note that, I tried docker operation, but reached to the following issue and then stopped using that.  https://github.com/codeforequity-at/botium-core/issues/224

I also tried simple REST operation, but it seems that this operation does not work on bots based on Microsoft Bot Framework.

Thanks.

**Comment by Anant13579** [comment]
In particular, I want to run my bot locally on my machine to ensure all test-cases running correctly before pushing the bot-code or new test-cases to respective code-repositories. If Botium doesn't support such use-case for now, are Botium DEVs planning to support such use-case in near future ? Any possible ETA ?

**Comment by codeforequity-at** [comment]
Never tried myself, but to my knowledge, the "DIRECTLINE3_DOMAIN" url can point to your locally running bot framework bot:
https://github.com/codeforequity-at/botium-connector-directline3#directline3_domain

**Comment by Anant13579** [comment]
I am using the following configs and tried many subsets of http://localhost:3978/api/messages/ in DIRECTLINE3_DOMAIN; but, every time Botium says, "error sending to bot Error: Error posting activity: Error: failed to connect"

Any clue ?

{
	"botium": {
		"Capabilities": {
			"PROJECTNAME": "My Botium Project using Direct Line API v 3.0",

			"CONTAINERMODE": "directline3",
			"DIRECTLINE3_SECRET": "<the secret key>",
			"DIRECTLINE3_WEBSOCKET": true,
			"DIRECTLINE3_POLLINGINTERVAL": 1000,
			"DIRECTLINE3_DOMAIN": "http://localhost:3978/api/messages/",
		
			"SCRIPTING_FORMAT": "xlsx",
			"SCRIPTING_XLSX_STARTROW": 2,
			"SCRIPTING_XLSX_STARTCOL": 1,
			"SCRIPTING_XLSX_SHEETNAMES": "Testcases",
			"SCRIPTING_XLSX_SHEETNAMES_UTTERANCES": "Utterances",
			"SCRIPTING_ENABLE_MEMORY": true
		}
	}
}

**Comment by williamium** [comment]
Is your direct line domain correct? We have it working correctly pointing to: `"DIRECTLINE3_DOMAIN": "http://localhost:5000/v3/directline",`

**Comment by Anant13579** [comment]
Ok. Now, I used offline-directline package (https://www.npmjs.com/package/offline-directline); and yes, after correcting the direct line domain, it worked.

Thank you for your responses.
