### ISSUE TITLE
how to send an existing conversation id in a test case ?

### ISSUE THREAD

**Issue by Anant13579** [codeforequity-at/botium-core#245]
Hi,

How can botium use a conversation-id returned from a bot (developed using Microsoft Bot Framework) during first test-case in the next test-cases ?

In our use-case, the bot returns a conversation-id to botium on the very first test-case. If botium does not send that conversation-id back to the bot in the next text-cases, the bot considers the next test-cases as a totally new conversation, and hence, responds with greetings, which are unexpected and unnecessary.

Can you please provide a solution for that ?

Thanks.

**Comment by codeforequity-at** [comment]
This works as designed - the test cases should be independent of each other.
The whole bot connection is reset after each test case, it is even possible to use unique user names for each test case (DIRECTLINE3_GENERATE_USERNAME). 
My advice is to rework your test cases to take care for this - maybe you can use the INCLUDE logic hook to catch the greetings in all of your test cases.
