### ISSUE TITLE
Interaction with secured chatbot

### ISSUE THREAD

**Issue by xmichele** [codeforequity-at/botium-core#246]
Dear Team,

a security layer, given by keycloak, has been added to the chatbot that I'm testing (with WEBDRIVERIO mode) . So there is user login, token OAuth2 ecc.. is there any way to handle it with botium-cli options or something else?

Thanks

**Comment by codeforequity-at** [comment]
As long as you can pass the security layer by clicking buttons or entering some text, that should not be a big deal - but you will have to write code for it - escpecially the WEBDRIVERIO_OPENBOT extension point is important (https://github.com/codeforequity-at/botium-connector-webdriverio#webdriverio_openbot-1)

**Comment by xmichele** [comment]
Got it. Can I use facebook username and psw webdriverio options or handle it customizing txt convo file and botium.json i.e. putting in OR the textBoxes elements ?

**Comment by codeforequity-at** [comment]
You can use the existing WEBDRIVERIO_USERNAME/PASSWORD capabilities, or you can just invent your own and add them to botium.json - the "container" is accessible in the openbot-extension function (first param, see https://github.com/codeforequity-at/botium-connector-webdriverio#webdriverio_openbot), and _container.caps["MY_USERNAME"]_ will read your capabitilies.

**Comment by xmichele** [comment]
with WEBDRIVERIO_USERNAME/PASSWORD no success, trying with webdriverio_openbot option and a custom js file

**Comment by codeforequity-at** [comment]
Sorry for the misunderstanding - of course you need to write the JS code to fill the username/password into the right fields with Selenium - but you can use the existing capabilities for it, you don't have to invent new ones ... currently, the username/password capabilities are used by the predefined facebook profile only.

**Comment by xmichele** [comment]
Works fine with openbot and customJs file : )
