### ISSUE TITLE
SMTP Report generation

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-core#250]
Hi

Please need suggestion on how to do SMTP for mochawesome reports that is mail triggering of the generated report.
Please suggest Us.

Thanks,

**Comment by codeforequity-at** [comment]
You would need another tool for sending emails, that is out of scope for Botium.
If you integrated Botium in a CI/CD pipeline like Bamboo or Jenkins, you can configure mail notifications there. If you need CLI tool, you can have a look at nodemailer.
