### ISSUE TITLE
Watson URL needs to be updated for London and Tokio locations

### ISSUE THREAD

**Issue by radhabasida** [codeforequity-at/botium-core#253]
Not able to connect with Watson for London region as service endpoint URL is not setup correctly in botium box. Not able to load workspace for London location
Service endpoints by location, Also for tokio location endpoint is not  available

Dallas: https://gateway.watsonplatform.net/assistant/api
Washington, DC: https://gateway-wdc.watsonplatform.net/assistant/api
Frankfurt: https://gateway-fra.watsonplatform.net/assistant/api
Sydney: https://gateway-syd.watsonplatform.net/assistant/api
Tokyo: https://gateway-tok.watsonplatform.net/assistant/api
London: https://gateway-lon.watsonplatform.net/assistant/api

![botium-box-available-endpoints](https://user-images.githubusercontent.com/48954471/55003019-8ba9ec00-4ffd-11e9-87b3-147cddcd6d6f.png)
![ibm-watson-service-endpoints](https://user-images.githubusercontent.com/48954471/55003020-8ba9ec00-4ffd-11e9-9353-4f5bbfb2f8e9.png)

**Comment by codeforequity-at** [comment]
Hello, I added this to our internal backlog. Most likely part of this weeks build.
