### ISSUE TITLE
botium-connector-google-assistant-init no longer works

### ISSUE THREAD

**Issue by JShefferPillar** [codeforequity-at/botium-core#254]
**Describe the bug**
We have been testing with Botium on three projects for over a month and it started failing today on all of them.

We get the same error trying to execute the tests that we get when trying to run botium-connector-google-assistant-init

**To Reproduce**

Running 
```
botium-connector-google-assistant-init
```
 within an npm run command gives the following error after following all the prompts.

```
Capabilities are written to botium.json

Validating Capabilities...
Error: Empty response, configuration, or start utterance Talk to AEP Dev One invalid!
{ micOpen: false,
  textToSpeech: [],
  displayText: [],
  ssml: [],
  suggestions: [] }

```
Trying to run the tests with the generated config give a very similar error

```
botium-cli run -c $BOTIUM_CONFIG -C $BOTIUM_CONVOS



  Botium Test-Suite
(node:16899) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
    1) "before each" hook for "GetActivityTimeOutRetry/retryUtterances-L1/yesUtterances-L1"


  0 passing (3s)
  1 failing

  1) Botium Test-Suite
       "before each" hook for "GetActivityTimeOutRetry/retryUtterances-L1/yesUtterances-L1":
     Error: Empty response, configuration, or start utterance Talk to Test Dev One invalid!
{ micOpen: false,
  textToSpeech: [],
  displayText: [],
  ssml: [],
  suggestions: [] }
      at Start.client.send.then (node_modules/botium-connector-google-assistant/index.js:59:19)
      at process.internalTickCallback (internal/process/next_tick.js:77:7)



npm ERR! Test failed.  See above for more details.
```

**Expected behavior**
I expect the tests to continue to execute

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.13.6
 -  npm 6.4.1
 - Node 11.3.0
- botium-cli : "~0.0.45",
- botium-connector-google-assistant: "~0.0.1"

**Comment by codeforequity-at** [comment]
I confirm that exactly the same is happening for us as well since today.
@ujja any ideas ?

**Comment by JShefferPillar** [comment]
I don't know if it will help but just a thought, if it is an issue on google's end I wonder if they have changed something with some of their APIs.  I know the internet has been buzzing about the changes they are making to the gmail APIs this week which is going to break the IFTTT integration.

**Comment by codeforequity-at** [comment]
Hi, it started to work again today for me ... can you please check ?

**Comment by JShefferPillar** [comment]
I just confirmed that it appears to be working now.  Any ideas on what the issue was?

**Comment by codeforequity-at** [comment]
No idea ...
