### ISSUE TITLE
how to find in buttons in JSON-Response

### ISSUE THREAD

**Issue by dShreya1701** [codeforequity-at/botium-core#258]
My bot has some buttons in the response but it is not shown in botium. There is one solution which I found and that is SIMPLEREST_BUTTONS_JSONPATH , but I don't know how to use this capability in Botium Box. Any solution?

**Comment by codeforequity-at** [comment]
When selecting "Advanced Settings" in the connector technology field, you get access to the raw capability list and can add this buttons capability there.

![image](https://user-images.githubusercontent.com/26287439/55380131-8843c280-551f-11e9-9c99-63c1d70ee6fa.png)

**Comment by dShreya1701** [comment]
But what will be the type and capability value while setting this capability?

**Comment by codeforequity-at** [comment]
Type "Text". Value: JSONPath expression.
https://github.com/codeforequity-at/botium-core/wiki/operation-mode-simplerest#simplerest_buttons_jsonpath

**Comment by dShreya1701** [comment]
What is JSONPath expression? I am very new to this Sorry for the silly question.

**Comment by codeforequity-at** [comment]
http://lmgtfy.com/?q=what+is+jsonpath

**Comment by dShreya1701** [comment]
do I need to set "JSONPath Expression" or some Json expression is there for the buttons?

**Comment by codeforequity-at** [comment]
Yes, you have to compose a JSONPath expression resolving to the buttons - this depends on your implementation. If you attach a sample JSON response from your HTTP endpoint, I can give you some hints.

**Comment by maland89** [comment]
Dear @codeforequity-at,

Can you give me a hint related to this topic?
I Receive a JSON in the following format (RASA fromat)
```
[
  {
    "recipient_id": "recipient_id_1",
    "text": "Hello!"
  },
  {
    "recipient_id": "recipient_id_1",
    "text": "I am your cool boot."
  },
  {
    "recipient_id": "recipient_id_1",
    "text": "I can help you with following services",
    "buttons": [
      {
        "payload": "/operator",
        "title": "Connect with an operator"
      }
    ]
  },
  {
    "recipient_id": "recipient_id_1",
    "text": "OR",
    "buttons": [
      {
        "payload": "/get_balance.get_balance",
        "title": "To get balance on your account"
      },
      {
        "payload": "/currency_rates.currency_rates",
        "title": "Get current currency rates"
      }
    ]
  }
]
```
To get a bot response (**SIMPLEREST_RESPONSE_JSONPATH** ) I use the following JSONPath - **$.*.text** 
To get a buttons (**SIMPLEREST_BUTTONS_JSONPATH**) I use the following JSONPath - **$.*.buttons[*].title** 
It works fine for me and Botium Box can find text and buttons in the bot answer. But there is only one thing what I can not solve and didn't find any information in docs about it. 
If I have more complex bot answer like a JSON above - where I have several text answers and only some of them have buttons, I have a combinations of all buttons from the bot answer under every text answer.

Is it possible to control which text answer has buttons?

**Comment by ujja** [comment]
It is not supported.

(we have created a new connector for Rasa (https://www.npmjs.com/package/botium-connector-rasa) but has the same limitation)

We are planning to support it, but cant say when.
