### ISSUE TITLE
Node Modules Error in Eclipse

### ISSUE THREAD

**Issue by stephenws** [codeforequity-at/botium-core#26]
Hi 

I am new in Botium and trying to configure Botium Project in Eclipse Neon with reference artical: https://chatbotsmagazine.com/5-steps-automated-testing-of-chatbots-in-eclipse-ef4c3dcaf233

I am getting few Error here : 
in Node Modules Jar:
![image](https://user-images.githubusercontent.com/26320996/38357966-ae486338-38e1-11e8-99ca-b9430a8a3de1.png)

My Project Structure: 
![image](https://user-images.githubusercontent.com/26320996/38358030-d591792a-38e1-11e8-89ca-0e0167a37c63.png)

Package.json file
![image](https://user-images.githubusercontent.com/26320996/38358110-08c51d60-38e2-11e8-89e0-87e28cd1d491.png)

testmybot.json
![image](https://user-images.githubusercontent.com/26320996/38358153-22b61468-38e2-11e8-9557-253e81ccdce5.png)

testmybot.js
![image](https://user-images.githubusercontent.com/26320996/38358280-72cfe00a-38e2-11e8-9490-14a3a90791be.png)

RunConfig
![image](https://user-images.githubusercontent.com/26320996/38358356-9fa0deae-38e2-11e8-9464-8e44116b4ca4.png)

It should be 25 matches as per documents but  showing only 20 matches

  Please Note: I am using same configuration and Project name as per doc.

**Comment by codeforequity-at** [comment]
this "unexpected token" usually means that a javascript language feature used in the code or in some depending code (in this case the module "bytebuffer") is not supported by the runtime. what Node.js version do you have installed ?

**Comment by stephenws** [comment]
npm = 3.10.10
node = 6.10.2

**Comment by codeforequity-at** [comment]
I see, you are running a Node.js application. when following the mentioned article, you should run the script from the package.json.

In the last screenshot it seems as if you are trying to run some file embeded in node_modules, no idea why you are trying to do this, but it's not a surprise that it doesn't work:

![image](https://user-images.githubusercontent.com/26287439/38362108-fe94fd7c-38cf-11e8-9056-c39e243f43a0.png)

**Comment by stephenws** [comment]
As per the documentation we followed Step2 in which **Just right click on “package.json”, open the “Run As” menu and select “npm Install”.** that time not all the jars are downaloded out of 25 only 19 jars are downloaded.

In Step5: 
 RunConfiguration, Npm package is not seen.
![image](https://user-images.githubusercontent.com/26320996/38363423-46dd2902-38f2-11e8-94c4-0d6d61202382.png)

Thanks in Advance.

**Comment by stephenws** [comment]
Done npm install in step2  but jars are downloaded and having error in that file 
![image](https://user-images.githubusercontent.com/26320996/38366644-148f716a-38fe-11e8-9f3e-4cc7cf1c54b6.png)

**Comment by codeforequity-at** [comment]
The errors maybe could mean that Eclipse is linked to a wrong NPM version (see here how to change: https://www.eclipse.org/community/eclipse_newsletter/2016/may/article3.php). I am not a big fan of eclipse, and I am not using it in daily work, just for writing the article, so I am clearly not the best consulter for this kind of problems.

But given that we just ignore this red marks and continue to step 5, when right-clicking on packag.json, there is no NPM run configuration available now ? So you cannot run the "test" target within eclipse ?

**Comment by stephenws** [comment]
Question: when right-clicking on packag.json, there is no NPM run configuration available now ?
Ans: Yes , no NPM Run configuration available

So you cannot run the "test" target within eclipse ?
Yes, right 

Can you suggest any other way to setup Botium Chatbot Project?

**Comment by codeforequity-at** [comment]
Running it in eclipse is only one of the options. You can find some documentation in the [ Testmybot Wiki](https://github.com/codeforequity-at/testmybot/wiki/) and in the [Botium Wiki](https://github.com/codeforequity-at/botium-core/wiki).

There is also an early-stage project "botium-cli" providing command line tools for generating and running test cases, but it currently is fully undocumented (https://github.com/codeforequity-at/botium-cli), just command line help available.

**Comment by codeforequity-at** [comment]
This Stackoverflow post is maybe also useful:
https://stackoverflow.com/questions/48860364/testing-the-chatbots-using-botium-and-testmybot-packages

**Comment by Ukr1244** [comment]
When I'm trying to open Test Cases(convo files) in browser emulator, throwing error
readConvo error: Error: ENOENT: no such file or directory, open 'C:\Users\VSCBS\
Desktop\Botium\[object Object]'

Please help me

**Comment by codeforequity-at** [comment]
Hello, this is clearly a bug in the browser emulator, I noticed this myself. It is in our backlog and will be fixed soon.

**Comment by codeforequity-at** [comment]
Closed for long inactivity.
