### ISSUE TITLE
Performance Testing for ChatBot response for utterences / Email Notifications

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-core#260]
In Botium can you provide us on whether chatbot utterances and bot responses performances can be verified for its stability and reports.

Thanks
Vijay

**Comment by codeforequity-at** [comment]
We are currently working on providing Performance testing with Botium - I assume by "performance" you mean stress and load testing.

**Comment by vijaysimh** [comment]
Yes i meant Stress and Load testing and also we need another feature -
SMTP  mail  to send auto-generated machawesme reports to particular emails
we wish.

Thanks and Regards,
Vijaysimha.N

**Comment by codeforequity-at** [comment]
So, stress and load testing is one of the features we are actually working on (see our [Roadmap](https://medium.com/@floriantreml/botium-box-release-notes-66cf337bc1a1)).

Regarding the email notifications, we think that this is out of scope for a tool like Botium, and there are way better tools to automate sending of email notifications, which can be combined with Botium. Nevertheless, I will discuss this with my team, as we heard this request several times now.

**Comment by ujja** [comment]
Performance test feature is ready: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/32145428/Performance+test
