### ISSUE TITLE
QUICKSTART ISSUE

### ISSUE THREAD

**Issue by rixj** [codeforequity-at/botium-core#262]
**Describe the bug**
The instructions say to enter
`$ curl --output docker-compose-all.yml https://raw.githubusercontent.com/codeforequity-at/botium-box-basic-dist/master/docker-compose-all.yml`
`$ docker-compose -f docker-compose-all.yml up`
![Screen Shot 2019-04-04 at 1 43 51 PM](https://user-images.githubusercontent.com/23671952/55576817-28484a00-56e0-11e9-8d70-c358ffc784b4.png)
but when I do I am getting the error `ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.`

**Expected behavior**
It to work? More precisely, to start the docker server and that I can view it via browser.

**Screenshots**
![Screen Shot 2019-04-04 at 1 40 46 PM](https://user-images.githubusercontent.com/23671952/55576566-a22c0380-56df-11e9-9009-2e5d6cfa76a0.png)

text version:
$ curl --output docker-compose-all.yml https://raw.githubusercontent.com/codeforequity-at/botium-box-basic-dist/master/docker-compose-all.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1071  100  1071    0     0   4266      0 --:--:-- --:--:-- --:--:―  4284
$ docker-compose -f docker-compose-all.yml up
ERROR: Couldn't connect to Docker daemon - you might need to run docker-machine start default.

**Desktop (please complete the following information):**
 - OS: 10.14.1
- Docker version 18.09.4, build d14af54
- docker-compose version 1.24.0, build unknown
- Redis 5.0.4

**Comment by codeforequity-at** [comment]
have you tried to do what the error message suggests ?
"ERROR: Couldn't connect to Docker daemon - you might need to run
docker-machine start default"


DC <notifications@github.com> schrieb am Do., 4. Apr. 2019, 19:52:

**Comment by rixj** [comment]
Yep. Tried that even before I wrote this issue. Also I tried their next suggestion and it didn't work as well.
![Screen Shot 2019-04-04 at 1 18 02 PM](https://user-images.githubusercontent.com/23671952/55630009-a0674c00-5782-11e9-8dc9-dce117fb3217.png)

**Comment by codeforequity-at** [comment]
Obviously, there is something wrong or not ready with your docker installation. At a minimum, the command 
```docker run hello-world```
should show a success message.
See https://docs.docker.com/get-started/

**Comment by rixj** [comment]
Sorry I didn't know better.
