### ISSUE TITLE
bot says nothing

### ISSUE THREAD

**Issue by Raj17940** [codeforequity-at/botium-core#266]
Issue: Actually bot giving proper response, but botium say's "bot says nothing". kindly help me resolve the issue.

"TranscriptError: Error: hello.convo.txt/Line 5: bot says nothing"
  at async.waterfall (node_modules\botium-core\src\scripting\Convo.js:207:25)
      at C:\Users\Dell\Downloads\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\custom- changes\node_modules\async\dist\async.js:473:16
      at next (node_modules\async\dist\async.js:5329:29)
      at C:\Users\Dell\Downloads\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\custom- changes\node_modules\async\dist\async.js:969:16
      at runConversation (node_modules\botium-core\src\scripting\Convo.js:185:15)
      at async.mapSeries (node_modules\botium-core\src\scripting\Convo.js:376:9)
      at C:\Users\Dell\Downloads\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\custom- changes\node_modules\async\dist\async.js:1140:9
      at C:\Users\Dell\Downloads\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\custom- changes\node_modules\async\dist\async.js:473:16
      at iterateeCallback (node_modules\async\dist\async.js:988:17)
      at C:\Users\Dell\Downloads\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\custom- changes\node_modules\async\dist\async.js:969:16
      at C:\Users\Dell\Downloads\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\custom- changes\node_modules\async\dist\async.js:1137:13
      at convoStepDone (node_modules\botium-core\src\scripting\Convo.js:251:11)
      at scriptingEvents.onBotStart.then.then (node_modules\botium-core\src\scripting\Convo.js:312:24)

**Comment by ujja** [comment]
Is the response of the bot normal text?

**Comment by Raj17940** [comment]
> 
> 
> Is the response of the bot normal text?

ya normal text message

**Comment by codeforequity-at** [comment]
Pls enable debug mode and attach full log output here. thanks.

**Comment by codeforequity-at** [comment]
news ?

**Comment by mcconejero** [comment]
i'm using botium-connector-botkit and have the same problem? Some help?

**Comment by codeforequity-at** [comment]
@mcconejero pls separate ticket
