### ISSUE TITLE
if WATSON_COPY_WORKSPACE value is true and run the test suite, connector is not deleting copied workspace after the execution.

### ISSUE THREAD

**Issue by radhabasida** [codeforequity-at/botium-core#271]
If I specify WATSON_COPY_WORKSPACE = true, connector is copying workspace and creating  a new to run test suie. But after the execution, it is nor deleting new created workspace. Please look into this issue.

It should be automatically deleted as per guide line mentioned here https://github.com/codeforequity-at/botium-connector-watson

**Comment by codeforequity-at** [comment]
Can you please provide a log output ? Indeed, this should work. Are you using the V1 or the V2 assistant version ?

**Comment by codeforequity-at** [comment]
any update ?
