### ISSUE TITLE
How to export test results while using CLI

### ISSUE THREAD

**Issue by hossa95** [codeforequity-at/botium-core#276]
I ran tests using cli .. by this command 

> botium-cli run --config path/to/botium.json --convos path/to/files

the results are shown in the terminal .. how can I export this results in txt file?

**Comment by hossa95** [comment]
I tried this .. but it just change the format appears in the terminal .. i want to export it in a txt file to save it for later compare

**Comment by codeforequity-at** [comment]
You can add "> output.txt" to the commandline to redirect the output to a file.

**Comment by hossa95** [comment]
I tried this .. but it just change the format appears in the terminal .. i want to export it in a txt file to save it for later compare

**Comment by codeforequity-at** [comment]
will test myself and maybe provide fix for it

**Comment by codeforequity-at** [comment]
Tested it and it works:

    botium-cli run > out.txt

Will write the test report to out.txt
For plain text reports, the [TAP-format](https://mochajs.org/#tap) is maybe the best choice.

    botium-cli run tap > out.txt

Output file looks like this:

    1..1
    ok 1 Botium Test-Suite give me picture
    # tests 1
    # pass 1
    # fail 0
