### ISSUE TITLE
Multiple Response Path SimpleREST ContainerMode

### ISSUE THREAD

**Issue by husseinadell** [codeforequity-at/botium-core#277]
**The problem**
we're working with RASA framework, and i faced two problems, during handling response from the bot, the response comes with 2 different types: 
1- without a database query: 
{
        "recipient_id": "1",
        "text": "bot response"
}
2- with a database query: 
[
    {
        "recipient_id": "1",
        "text": "query output"
    },
    {
        "recipient_id": "1",
        "text": "bot response"
    }
]
the first problem is that i want to define 2 different paths for extracting the text, the second is that i want to know how to parse the json output if given as a list of objects (with the database query)
**Solution**
if there is a solution on how to get the 2 problems done, or i suggest extending the "SIMPLEREST_RESPONSE_JSONPATH" to accept a list of paths

**Comment by codeforequity-at** [comment]
I think Botium can do what you want out of the box.

The capability SIMPLEREST_RESPONSE_JSONPATH can be used multiple times, with suffix added

```
  "SIMPLEREST_RESPONSE_JSONPATH": "$.text",
  "SIMPLEREST_RESPONSE_JSONPATH_1": "$.anotherselector",
```

The JSONPaths will be evaluated one after the other against the JSON response. In case a JSONpath resolves to an array, every single array element is treated as a bot response.

see https://github.com/codeforequity-at/botium-core/wiki/operation-mode-simplerest

**Comment by husseinadell** [comment]
can i add a customized path using a .js file, 
ex: in case of array response 
```
[
  {
     "recipient_id": "1",
     "text": "query output"
  },
  {
    "recipient_id": "1",
    "text": "bot response"
  }
]
```
i want to test over the text on the second object, is it doable?

**Comment by ujja** [comment]
yes.

$.[1:2].text

you can try it online here: https://jsonpath.com/
