### ISSUE TITLE
Achieving the E2E testing with the Selenium Server

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#284]
In the Enterprise plan, how to achieve end to end testing with the Selenium Server? Referring to the https://medium.com/@floriantreml/botium-in-a-nutshell-part-6-e2e-testing-with-botium-box-9bd8acdf5a70, I am unable to get the Selenium Configuration details

**Comment by codeforequity-at** [comment]
You absolutely need a Selenium server. This can be a local installation of Selenium, or you can try it with a Docker image for Selenium, or you can use a Cloud provider like Saucelabs or Experitest. But without a Selenium server, it won't work.
As a starter, you can use the "Integrated PhantomJS" device provider.

**Comment by Aishwarya-J-S** [comment]
We are using Selenium Grid . What should be Selenium Endpoint?

Should it be the Selenium Grid URL?

Also What should be the start url and webdriver script for WebdriverIO(selenium/Appium)?

Do you have any documentation on that? or any sample video?

**Comment by codeforequity-at** [comment]
Best source for documentation is the mentioned blog article and the Github repository (https://github.com/codeforequity-at/botium-connector-webdriverio).
Selenium Endpoint is the grid url, yes. 
Start Url is the Url of the website to test. Webdriver Scripts are prepared for some chatbot widgets out there, but you will most likely have to customize the Botium capabilities for your own chatbot.

**Comment by Aishwarya-J-S** [comment]
How to give capability value for WEBDRIVERIO_OPENBOT in Botium Box Enterprise Edition

I have to automate a bot embedded in a website as in the below steps
1. Connect to Web Site
2. Click the bot icon to open the chat Window
3. Make conversation with the bot

How to proceed with the 2nd Step because in the WebdriverIO Connector, only input element selector and output element selector are asked.

In the other capabilities how to add the capability for clicking the bot icon and also what should be capability value.

For the WEBDRIVERIO_OPTIONS what should be the type selected. When I gave it as JSON Structure and value as {"desiredCapabilities": {
"browserName": "chrome",
"platformName": "Windows 10"
}
}, the chatbot connection failed.

**Comment by codeforequity-at** [comment]
1. Are you using a cloud provider for Selenium ? If not, documentation on how to use Botium Box itself as selenium server is coming very soon.

2. For step 2. you will have to write a small Selenium script, place it in the "resources" folder and link to it in the capabilities configuration - documentation will be there very soon, again.

**Comment by Aishwarya-J-S** [comment]
Yes, I am using the Cloud Provider as Local Selenium Server and provided the URL of Selenium Grid.

Can you tell me how to proceed?

**Comment by codeforequity-at** [comment]
Please wait for the documentation.

**Comment by codeforequity-at** [comment]
I extended the Botium in a nutshell article with section on how to register your custom code with Botium Box: https://medium.com/@floriantreml/botium-in-a-nutshell-part-6-e2e-testing-with-botium-box-9bd8acdf5a70

**Comment by codeforequity-at** [comment]
Also, there is an article available on how to setup your own Selenium Grid and connect it to Botium Box: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/32145510/Run+Selenium+Grid+and+Connect+to+Botium+Box

**Comment by Aishwarya-J-S** [comment]
As in the document, I have setup the Selenium grid https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/32145510/Run+Selenium+Grid+and+Connect+to+Botium+Box
But it is not running in the grid currently after doing the following steps
1. Started Selenium grid
2. Verified Selenium Grid Status
3. The resources folder of the Botium Box distribution donot have the files  as EXPERITEST.json, INTEGRATED.json and LOCALSELENIUM.json
4. Manually created LOCALSELENIUM.json in the resources folder
5. Connected to botium box by adding the /wd/hub path to the URL.
6. Registered Device Set as in the screenshot, but able to add the chrome device as only Google Chrome(Headless) ( Can it be headless?)
7. Using the Webdriver connector, tried to test the website

But no logs coming up in the UI. Also can I view the logs on whether it is able to connect to the url or where errors are logged.

**Comment by codeforequity-at** [comment]
There definitly should be some files in the resources folder. What version of the box do you have installed ?

**Comment by Aishwarya-J-S** [comment]
Enterprise Edition

**Comment by codeforequity-at** [comment]
You need at least Botium Box 1.5 - you will have to upgrade your Botium Box to the latest version.

**Comment by Aishwarya-J-S** [comment]
Is that Only in botium box 1.5 , I would be able to connect to the Selenium Grid and will not work in Premium 1.4.0 version?

**Comment by codeforequity-at** [comment]
yes, using custom selenium grid doesn't work with prior versions.

**Comment by Aishwarya-J-S** [comment]
While trying to install the 1.5. the installation stopped here and returned a non-zero code: 1

Step 10/14 : RUN curl -Ls "https://github.com/dustinblackman/phantomized/releases/download/${PHANTOMJS_VERSION}/dockerized-phantomjs.tar.gz" | tar xz -C / && curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2 | tar -jxvf - -C ./ && cp phantomjs-${PHANTOMJS_VERSION}-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs && rm -fR phantomjs-${PHANTOMJS_VERSION}-linux-x86_64
 ---> Running in 0853612d9e19


tar: invalid magic
tar: short read
The command '/bin/sh -c curl -Ls "https://github.com/dustinblackman/phantomized/releases/download/${PHANTOMJS_VERSION}/dockerized-phantomjs.tar.gz" | tar xz -C / && curl -k -Ls https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2 | tar -jxvf - -C ./ && cp phantomjs-${PHANTOMJS_VERSION}-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs && rm -fR phantomjs-${PHANTOMJS_VERSION}-linux-x86_64' returned a non-zero code: 1

Can you help please?

**Comment by codeforequity-at** [comment]
My first guess is that there a firewall blocking access to github.com or bitbucket.org

**Comment by Aishwarya-J-S** [comment]
Is there any other alternative to install this?

**Comment by codeforequity-at** [comment]
We could build the docker images for you and provide you with a download link.

**Comment by Aishwarya-J-S** [comment]
After installing the latest version 1.6.0 , I am getting the following message in all the pages 

Error :-( - Unauthorized, missing permission

Please help

**Comment by codeforequity-at** [comment]
pls log out and log in again

Aishwarya-J-S <notifications@github.com> schrieb am Fr., 24. Mai 2019,
08:08:

**Comment by Aishwarya-J-S** [comment]
Thank you. Installed 1.6 successfully

**Comment by Aishwarya-J-S** [comment]
In latest version 1.6.0, I have added a new capability WEBDRIVERIO_OPENBOT. I have added the openbot.js script into the resources folder where the other three files EXPERITEST.json, INTEGRATED.json and LOCALSELENIUM.json are already present. And after restarting when I tried to run the job, I got the message as 
Job queued for execution
Job failed: ReferenceError: resources is not defined

Is there anything else to be done after adding the js file in the resources folder

**Comment by codeforequity-at** [comment]
What is the value of the WEBDRIVERIO_OPENBOT capability ? is it "resources/openbot.js" ?
We can get more insights by enabling the Agent logging (https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/29360129/Enable+Diagnostics+and+Inspect+Logs#Inspect-Logs-from-Botium-Agents).

**Comment by Aishwarya-J-S** [comment]
Yeah, I have the set the value incorrect. I have enabled the logging.
Can you tell me how this steps are working in order with the capabilities

1. Open the Start Url as given in the Botium configuration
2. Do some clicks to open the chatbot window (if it is not opened automatically)
3. Use the Input Element Selector to send some text to the chatbot
4. Use the Output Element Selector to detect the responses of the chatbot

Will it work in an order with the list we mention in the Capabilities
 
I am able to open the url but getting an error as 
**Capability WEBDRIVERIO_OPENBOT not a function, trying to load as function from NPM package**

Also getting an error as " Error: An element could not be located on the page using the given search parameters". Is it because it is trying to locate the selector before executing the Openbot.js file.

**Comment by codeforequity-at** [comment]
The warning message is ignorable (added to the backlog to make better logging in this section). Actually, if there is no more output here it means that your script has been found and loaded.

The selector is only done AFTER the openbot code. What does your openbot.js look like ?

**Comment by Aishwarya-J-S** [comment]
This is how js file looks like

result = browser.waitForVisible('.XXXX-widget', 20000)
 .click('.XXXX-widget')
 .pause(2000)
 .waitForVisible('.chat-room', 20000)
 .waitForVisible('.input-message', 10000)
 .waitForVisible('.send-button', 10000)

![inputselector](https://user-images.githubusercontent.com/49233293/58475863-bb47b280-816c-11e9-83c3-f86f16ca2508.png)

Once after the the bot has opened by clicking and viewing the selectors, I want to give the input from the test set provided.

It is not taking my input selector but giving an error as "An element could not be located on the page using the given search parameters"

Should there be any standard way of selectors that only id/class/xpath has to be provided for the input/output selector.


Also when i tried to do live chat, getting an error as 
![image](https://user-images.githubusercontent.com/49233293/58476137-8d16a280-816d-11e9-9005-e5e590519b54.png)

But I have not provided that url but only the url of my selenium grid, with the server host name

**Comment by codeforequity-at** [comment]
When placing code in a file, the file should export a single function. This is different from what you did. It is described in the Botium in a nutshell article, and I added it to the [Github documentation as well now](https://github.com/codeforequity-at/botium-connector-webdriverio/blob/master/README.md#placing-code-in-a-javascript-file).

The openbot.js file should start with _module.exports =..._

Live Chat is not yet possible with the webdriver connector (it's in the backlog).

**Comment by Aishwarya-J-S** [comment]
Can you tell me what kind of error is below

2019-05-29T09:18:34.461Z: 2019-05-29T09:18:34.441Z botium-box-worker-runtestcases Test Session Run failed (Error: ESOCKETTIMEDOUT), doing additional BotDriver Clean.

2019-05-29T09:18:34.461Z: 2019-05-29T09:18:34.442Z botium-connector-webdriverio Clean called

2019-05-29T09:18:36.460Z: 2019-05-29T09:18:36.445Z botium-BaseContainer Cleanup rimrafing temp dir /app/agent/botiumwork/Test-Project-wSID8-Initial-Test-Session-20190529-091233-kAIog

2019-05-29T09:18:36.569Z: Job failed: Error: ESOCKETTIMEDOUT

**Comment by Aishwarya-J-S** [comment]
I am getting this error when i try to run the Test with Webdriverio Chatbot technology

**Comment by codeforequity-at** [comment]
I would say, the connection to the Selenium hub is not possible. do you have more logs ? (it's just the end of the log output I guess)

**Comment by Aishwarya-J-S** [comment]
While trying to connect to Selenium Grid with WebdriverIO Chatbot Technology , it is stuck with the following logs and not proceeding further, Could you tell where it is stuck

2019-05-31T07:26:46.280Z: Job queued for execution
2019-05-31T07:26:47.108Z: 2019-05-31T07:26:46.134Z botium-BotDriver BuildCompiler: Capabilites: { PROJECTNAME: 'Test Project - TLXjQ - Initial Test Session',
  TEMPDIR: 'botiumwork',
  CLEANUPTEMPDIR: true,
  WAITFORBOTTIMEOUT: 10000,
  SIMULATE_WRITING_SPEED: false,
  DOCKERCOMPOSEPATH: 'docker-compose',
  DOCKERMACHINEPATH: 'docker-machine',
  DOCKERMACHINE: false,
  DOCKERIMAGE: 'node:boron',
  DOCKERUNIQUECONTAINERNAMES: false,
  DOCKERSYSLOGPORT_RANGE: '47100-47299',
  BOT_HEALTH_STATUS: 200,
  SLACK_PUBLISHPORT_RANGE: '46100-46299',
  FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  SIMPLEREST_PING_RETRIES: 6,
  SIMPLEREST_PING_TIMEOUT: 10000,
  SIMPLEREST_PING_VERB: 'GET',
  SIMPLEREST_METHOD: 'GET',
  WEBSPEECH_SERVER_PORT: 46050,
  WEBSPEECH_LANGUAGE: 'en-US',
  WEBSPEECH_CLOSEBROWSER: true,
  SCRIPTING_TXT_EOL: '\n',
  SCRIPTING_XLSX_EOL_SPLIT: '\r',
  SCRIPTING_XLSX_EOL_WRITE: '\r\n',
  SCRIPTING_XLSX_STARTROW: 2,
  SCRIPTING_XLSX_STARTCOL: 1,
  SCRIPTING_NORMALIZE_TEXT: false,
  SCRIPTING_ENABLE_MEMORY: false,
  SCRIPTING_MATCHING_MODE: 'includeLowerCase',
  SCRIPTING_UTTEXPANSION_MODE: 'all',
  SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
  SCRIPTING_MEMORYEXPANSION_KEEP_ORIG: false,
  RETRY_USERSAYS_ONERROR_REGEXP: [],
  RETRY_USERSAYS_NUMRETRIES: 1,
  RETRY_USERSAYS_FACTOR: 1,
  RETRY_USERSAYS_MINTIMEOUT: 1000,
  ASSERTERS:
   [ { ref: 'HASLINK',
       src: 'botium-asserter-basiclink',
       global: false,
       args: {} },
     { ref: 'CHECKLINK',
       src: 'botium-asserter-hyperlink',
       global: true,
       args: {} },
     { ref: 'HTTP',
       src: 'botium-asserter-http',
       global: false,
       args: {} } ],
  LOGIC_HOOKS: [],
  USER_INPUTS: [],
  CONTAINERMODE: 'webdriverio',
  WEBDRIVERIO_URL: 'https://XXXXXX/XXXX/',
  WEBDRIVERIO_PROFILE: '',
  WEBDRIVERIO_INPUT_ELEMENT: '.input-message',
  WEBDRIVERIO_INPUT_ELEMENT_VISIBLE_TIMEOUT: 10000,
  WEBDRIVERIO_OUTPUT_ELEMENT: '.send-button',
  WEBDRIVERIO_IGNOREUPFRONTMESSAGES: false,
  WEBDRIVERIO_USERNAME: '',
  WEBDRIVERIO_PASSWORD: '',
  WEBDRIVERIO_SCREENSHOTS: 'onbotsays',
  WEBDRIVERIO_OPTIONS:
   { desiredCapabilities:
      { browserName: 'chrome',
        name: 'Test Project - TLXjQ - Initial Test Session' },
     protocol: 'http',
     host: '10.235.112.39',
     port: '4444',
     path: '/wd/hub' },
  FBPAGERECEIVER_REDISURL: { port: '6379', host: 'redis', db: 0, options: {} } }

2019-05-31T07:26:47.109Z: 2019-05-31T07:26:46.126Z botium-box-worker-runtestcases Started processing, JobId #10.

2019-05-31T07:26:47.110Z: 2019-05-31T07:26:46.129Z botium-BotDriver Loaded Botium configuration file ./botium.json

2019-05-31T07:26:47.113Z: 2019-05-31T07:26:47.035Z botium-asserterUtils Loaded HTTP SUCCESSFULLY

2019-05-31T07:26:47.125Z: 2019-05-31T07:26:46.525Z botium-ScriptingProvider Using matching mode: includeLowerCase

2019-05-31T07:26:47.126Z: 2019-05-31T07:26:46.526Z botium-asserterUtils Loaded Default asserter - [ 'BUTTONS',
  'MEDIA',
  'PAUSE_ASSERTER',
  'ENTITIES',
  'ENTITY_VALUES',
  'INTENT',
  'INTENT_CONFIDENCE' ]

2019-05-31T07:26:47.127Z: 2019-05-31T07:26:46.526Z botium-asserterUtils Loaded Default logic hook - [ 'PAUSE',
  'WAITFORBOT',
  'SET_SCRIPTING_MEMORY',
  'CLEAR_SCRIPTING_MEMORY',
  'INCLUDE' ]

2019-05-31T07:26:47.127Z: 2019-05-31T07:26:46.527Z botium-asserterUtils Loaded Default user input - [ 'BUTTON', 'MEDIA', 'FORM' ]

2019-05-31T07:26:47.128Z: 2019-05-31T07:26:46.527Z botium-asserterUtils Trying to load HASLINK asserter from botium-asserter-basiclink

2019-05-31T07:26:47.128Z: 2019-05-31T07:26:46.606Z botium-asserterUtils Loaded HASLINK SUCCESSFULLY

2019-05-31T07:26:47.128Z: 2019-05-31T07:26:46.606Z botium-asserterUtils Trying to load CHECKLINK asserter from botium-asserter-hyperlink

2019-05-31T07:26:47.129Z: 2019-05-31T07:26:46.643Z botium-asserterUtils Loaded CHECKLINK SUCCESSFULLY

2019-05-31T07:26:47.129Z: 2019-05-31T07:26:46.643Z botium-asserterUtils global asserter: CHECKLINK was set and will be executed in every convo

2019-05-31T07:26:47.129Z: 2019-05-31T07:26:46.643Z botium-asserterUtils Trying to load HTTP asserter from botium-asserter-http

2019-05-31T07:26:47.568Z: 2019-05-31T07:26:47.061Z botium-box-worker-runtestcases expanding convos ...

2019-05-31T07:26:47.568Z: 2019-05-31T07:26:47.061Z botium-ScriptingProvider ExpandConvos - Using utterances expansion mode: all

2019-05-31T07:26:47.569Z: 2019-05-31T07:26:47.062Z botium-box-worker-runtestcases found 1 convos ...

2019-05-31T07:26:47.587Z: 2019-05-31T07:26:47.065Z botium-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true }

2019-05-31T07:26:47.588Z: 2019-05-31T07:26:47.453Z botium-PluginConnectorContainer Invalid Botium plugin loaded from webdriverio, expected PluginVersion, PluginClass fields

2019-05-31T07:26:47.588Z: 2019-05-31T07:26:47.515Z botium-PluginConnectorContainer Botium plugin botium-connector-webdriverio loaded

2019-05-31T07:26:47.589Z: 2019-05-31T07:26:47.516Z botium-connector-webdriverio Validate called

2019-05-31T07:26:47.589Z: 2019-05-31T07:26:47.517Z botium-connector-webdriverio Build called

2019-05-31T07:26:47.590Z: 2019-05-31T07:26:47.519Z botium-connector-webdriverio Start called

2019-05-31T07:26:47.587Z: 2019-05-31T07:26:47.063Z botium-box-worker-runtestcases batchNum: 1 batchCount: 1 convosPerBatch: 1 batchStart: 0 batchEnd: 0 batchLength: 1

2019-05-31T07:26:47.587Z: 2019-05-31T07:26:47.064Z botium-BotDriver Build - Botium Core Version: 1.4.14

2019-05-31T07:26:47.588Z: 2019-05-31T07:26:47.064Z botium-BotDriver Build - Capabilites: { PROJECTNAME: 'Test Project - TLXjQ - Initial Test Session',
  TEMPDIR: 'botiumwork',
  CLEANUPTEMPDIR: true,
  WAITFORBOTTIMEOUT: 10000,
  SIMULATE_WRITING_SPEED: false,
  DOCKERCOMPOSEPATH: 'docker-compose',
  DOCKERMACHINEPATH: 'docker-machine',
  DOCKERMACHINE: false,
  DOCKERIMAGE: 'node:boron',
  DOCKERUNIQUECONTAINERNAMES: false,
  DOCKERSYSLOGPORT_RANGE: '47100-47299',
  BOT_HEALTH_STATUS: 200,
  SLACK_PUBLISHPORT_RANGE: '46100-46299',
  FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  SIMPLEREST_PING_RETRIES: 6,
  SIMPLEREST_PING_TIMEOUT: 10000,
  SIMPLEREST_PING_VERB: 'GET',
  SIMPLEREST_METHOD: 'GET',
  WEBSPEECH_SERVER_PORT: 46050,
  WEBSPEECH_LANGUAGE: 'en-US',
  WEBSPEECH_CLOSEBROWSER: true,
  SCRIPTING_TXT_EOL: '\n',
  SCRIPTING_XLSX_EOL_SPLIT: '\r',
  SCRIPTING_XLSX_EOL_WRITE: '\r\n',
  SCRIPTING_XLSX_STARTROW: 2,
  SCRIPTING_XLSX_STARTCOL: 1,
  SCRIPTING_NORMALIZE_TEXT: false,
  SCRIPTING_ENABLE_MEMORY: false,
  SCRIPTING_MATCHING_MODE: 'includeLowerCase',
  SCRIPTING_UTTEXPANSION_MODE: 'all',
  SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
  SCRIPTING_MEMORYEXPANSION_KEEP_ORIG: false,
  RETRY_USERSAYS_ONERROR_REGEXP: [],
  RETRY_USERSAYS_NUMRETRIES: 1,
  RETRY_USERSAYS_FACTOR: 1,
  RETRY_USERSAYS_MINTIMEOUT: 1000,
  ASSERTERS:
   [ { ref: 'HASLINK',
       src: 'botium-asserter-basiclink',
       global: false,
       args: {} },
     { ref: 'CHECKLINK',
       src: 'botium-asserter-hyperlink',
       global: true,
       args: {} },
     { ref: 'HTTP',
       src: 'botium-asserter-http',
       global: false,
       args: {} } ],
  LOGIC_HOOKS: [],
  USER_INPUTS: [],
  CONTAINERMODE: 'webdriverio',
  WEBDRIVERIO_URL: 'https://azsg-d-bot-dev7.wipro.com:445/livechat/',
  WEBDRIVERIO_PROFILE: '',
  WEBDRIVERIO_INPUT_ELEMENT: '.input-message',
  WEBDRIVERIO_INPUT_ELEMENT_VISIBLE_TIMEOUT: 10000,
  WEBDRIVERIO_OUTPUT_ELEMENT: '.send-button',
  WEBDRIVERIO_IGNOREUPFRONTMESSAGES: false,
  WEBDRIVERIO_USERNAME: '',
  WEBDRIVERIO_PASSWORD: '',
  WEBDRIVERIO_SCREENSHOTS: 'onbotsays',
  WEBDRIVERIO_OPTIONS:
   { desiredCapabilities:
      { browserName: 'chrome',
        name: 'Test Project - TLXjQ - Initial Test Session' },
     protocol: 'http',
     host: '10.235.112.39',
     port: '4444',
     path: '/wd/hub' },
  FBPAGERECEIVER_REDISURL: { port: '6379', host: 'redis', db: 0, options: {} } }

2019-05-31T07:26:47.588Z: 2019-05-31T07:26:47.065Z botium-BotDriver Build - Sources : { LOCALPATH: '.',
  GITPATH: 'git',
  GITBRANCH: 'master',
  GITDIR: '.' }

2019-05-31T07:27:29.485Z: 2019-05-31T07:27:29.466Z botium-box-worker sending heartbeat ...

**Comment by codeforequity-at** [comment]
It is hanging when it tries to connect to the Selenium hub. There are a lots of possible reasons, maybe Firewall ? Maybe Selenium Hub listening on wrong interface ? When Selenium running in docker, maybe port not published ?

**Comment by Aishwarya-J-S** [comment]
In the Selenium grid running in docker, we see the following logs

> chrome_1        | 09:02:57.406 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
chrome_1        | Starting ChromeDriver 73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72) on port 8697
chrome_1        | Only local connections are allowed.
chrome_1        | Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
chrome_1        | [1559293377.435][SEVERE]: bind() failed: Cannot assign requested address (99)
chrome_1        | 09:02:59.094 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
chrome_1        | 09:02:59.425 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 22f9ee842489d01552ce1d06afe9278f (org.openqa.selenium.chrome.ChromeDriverService)


After referring to https://github.com/RobCherry/docker-chromedriver/issues/15#issuecomment-446366892, I assume that I get the bind error because docker does not support IPV6 binding and the only way to avoid seems to be setting the white listed IP option for chromedriver. 

So, How do we add the Whitelisted IP Configuration in the WEBDRIVERIO_OPTIONS

**Comment by codeforequity-at** [comment]
I had no troubles with installing on IPV4 network only. Anyway, with Selenium Hub, settings such configuration is not possible from the Selenium client. My first guess would be that there is another selenium server listening on the same port (4444). Anyway, my suggestion is to ask those questions in Selenium specific forums, as I consider it to be a Selenium problem, not a Botium problem (and I am by far not a Selenium expert ...).

**Comment by Aishwarya-J-S** [comment]
Is any other capabilities that needs to be added to the botium for the Webdriver Chatbot technology to connect with selenium grid

![image](https://user-images.githubusercontent.com/49233293/58799941-45d45a00-8624-11e9-8220-86a7e2fd098c.png)

Also getting this error in the logs of botium

![image](https://user-images.githubusercontent.com/49233293/58801297-bc268b80-8627-11e9-9042-f41bc991ed7f.png)

**Comment by codeforequity-at** [comment]
The capabilities look good. Selenium server is not reachable. Firewalls, Portmappings, hostmappings - there are several things that can go wrong here. If you have troubles making your own Selenium server work, I suggest starting with a cloud provider setup, Botium Box supports saucelabs and experitest.

**Comment by Aishwarya-J-S** [comment]
We are able to run other scripts through the same selenium grid, but when we are stuck as the capabilities are missing in the botium settings 
```
selenium-hub    | 12:47:47.758 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, version: }
selenium-hub    | 12:47:47.758 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=41732597-a1e8-4b93-b662-b1fcf70d7be2, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=1, platformName=LINUX, version=74.0.3729.169, applicationName=, platform=LINUX}
chrome_1        | 12:47:47.773 INFO [ActiveSessionFactory.apply] - Capabilities are: {
chrome_1        |   "browserName": "chrome",
chrome_1        |   "goog:chromeOptions": {
chrome_1        |   },
chrome_1        |   "version": ""
chrome_1        | }

```

**Comment by codeforequity-at** [comment]
OK, to wrap it up and to get an overview: can you please provide (by email!) the following:
* a screenshot of the device provider view where you registered your selenium server
* a screenshot of the device set you are using for the tests
* a screenshot of the chatbot & capabilities view 
* the log output from the agent when running a simple test case with this configuration (https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/29360129/Enable+Diagnostics+and+Inspect+Logs#Inspect-Logs-from-Botium-Agents)

**Comment by Aishwarya-J-S** [comment]
In the latest 1.7.3 EE, Is it possible to add the js code as a `WEBDRIVERIO_OPENBOT` capability.

When I try to add the js code in the capability value with the type as `Javascript code`  and run it, it still throws an error as Error: unknown command: Cannot call non W3C standard command while in W3C mode

**Comment by codeforequity-at** [comment]
this is a selenium problem, not a botium problem. the openbot javascript seemed to work. i guess you are using your own selenium server ? maybe you have to upgrade or downgradr, please google for this error message.

**Comment by codeforequity-at** [comment]
In the log output I can spot the console.log-statements from your capability ("detail-form loading" ...).

The text area for entering the user input cannot be found by the given Selenium selector.
