### ISSUE TITLE
using get method in simplerest mode

### ISSUE THREAD

**Issue by dShreya1701** [codeforequity-at/botium-core#285]
I am using bot Api for testing 
capabilities set are:
SIMPLEREST_URL: api
SIMPLEREST_METHOD: GET
CONTAINERMODE: simplerest

but what do I need to set in "SIMPLEREST_RESPONSE_JSONPATH"???

**Comment by ujja** [comment]
Simple rest is a synchron connector. You send to it the question, it sends back the answer. You have to convert the body (JSON) to text(s) using JSONPath feature.

There is an online tool to play with it: https://jsonpath.com/

**Comment by dShreya1701** [comment]
actually my bor response is a card (including all the details) for eg. I want to know the time of a flight so my bot will respond with a card which has flight arrrival time departure time destination name etc on it.....so how can I deal with this?

**Comment by ujja** [comment]
other ticket please
