### ISSUE TITLE
DirectLine3 Card click 

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-core#288]
Botium chatBot emulator cmd console:
In UI it appears as Buttons : Delete PO and Close PO.
But actual when i opend in cmd :botium-cli emulator/browser

#bot:Do you want to close purchase order?,Delete PO,Close PO

Here if we select Delete Po,then we have xxx reponse
Or if selected Close PO we have yyy reponse.

**I want to know how to handle in excel sheet for select Delete PO as option .**

Screenshot Of UI:
![image](https://user-images.githubusercontent.com/30192609/57758194-c0d8dd80-7714-11e9-9fd8-da722b4b17fd.png)

In console :
#me: Delete PO
BOT SAYS (default): Do you want to delete purchase order permanently from xxx?
 or
 Do you want to close purchase order?
BOT SENDS CARDS (default):
 ***********************************************
 * Do you want to delete purchase order permanently from xxx?
 or
 Do you want to close purchase order?,Delete PO,Close PO
 ***********************************************

**Comment by vijaysimh** [comment]
Also please provide information at India what is the price of Botium Box(Indian Rupees) as seen in botium site its available in Euro

**Comment by codeforequity-at** [comment]
> Also please provide information at India what is the price of Botium Box(Indian Rupees) as seen in botium site its available in Euro

please contact us at our website

**Comment by codeforequity-at** [comment]
For simulation of button clicks, use the BUTTON tag - see https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/491664/Botium+Scripting+-+BotiumScript#User-Input-Methods

**Comment by vijaysimh** [comment]
Am sharing screenshot of excel ,please provide example on how to reply on previous Bot response.
Example - me:Delete PO
                 bot:xxxxx
Again i typed:
                 me:Delete PO
                 bot expected as yyy but iam getting  xxxxx of previous reponse,.
Here for same Utterance we require to different reponses ,the second response will change based on first reponse.

![image](https://user-images.githubusercontent.com/30192609/57763280-b4598280-771e-11e9-85f9-fcc3c18dcb13.png)

**Comment by codeforequity-at** [comment]
The format of your Excel file is not correct. Please see here: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/491664/Botium+Scripting+-+BotiumScript#Composing-in-Excel-files

For simulating button clicks in an excel file, you can just write "BUTTON Delete PO" in the Bot column.

**Comment by vijaysimh** [comment]
Hello i have rectified the excel format and i want to know like using command : botium-cli emulator
- had  received the response in the  format as BOT SAYS and BOT SENDS CARDS(default):
As am checking using: botium-cli run mochawesome --convos=./spec/convo --config=./spec/botium.json
How to capture BOT SENDS CARDS(default) as i could see only BOT SAYS:

Here is the format of excel used:

HelloUtt-
![image](https://user-images.githubusercontent.com/30192609/57836476-6efc8a00-77de-11e9-845c-b52544f6f9f2.png)
Utterances:
![image](https://user-images.githubusercontent.com/30192609/57836523-863b7780-77de-11e9-8ae6-9b0871080079.png)

From the below screenshot for reference:
Can you please send me guidelines on how to pass BOT SENDS CARD under excel file as it follows water fall dialog.

![image](https://user-images.githubusercontent.com/30192609/57831663-66eb1d00-77d3-11e9-9b31-ddfbfa51aa9c.png)

**Comment by codeforequity-at** [comment]
Now I see what the problem is: currently, the Directline connector doesn't recognize buttons on adaptive card content type. This is a small fix required to the Diretline connector - I added it to our backlog and it will be fixed in this sprint (by next thursday).

**Comment by vijaysimh** [comment]
Thankyou please intimate us once the fix is available as its on High priority for our Current project.

**Comment by codeforequity-at** [comment]
Our team is not able to track notifications for invidiual features. Please follow the Botium release notes to get updates.

**Comment by vijaysimh** [comment]
> Now I see what the problem is: currently, the Directline connector doesn't recognize buttons on adaptive card content type. This is a small fix required to the Diretline connector - I added it to our backlog and it will be fixed in this sprint (by next **thursday**).

Adaptive card type: Can we expect update on tomorrow i,e, Thursday for fix on Adaptive card content type by using command Line: npm install -g botium-connector-directline3

**Comment by codeforequity-at** [comment]
yes

**Comment by vijaysimh** [comment]
> yes

Thanks Team, tomorrow shall check for the adaptive card type fix and shall close the discussion.

**Comment by vijaysimh** [comment]
Updated  npm botium directLine3 for latest version-0.0.13.
Adaptive card types using water fall dialog.
![image](https://user-images.githubusercontent.com/30192609/58245984-a4bbe880-7d73-11e9-9b19-ef3e057a8711.png)
In the below screenshot -Which tool is used to Procure enclosed with buttons is verified in Botium but post update of botium drectline3 connector today,had verified for below screenshot which has Cards.Its failing what is the reason?
![image](https://user-images.githubusercontent.com/30192609/58246156-fa909080-7d73-11e9-9d20-59933cec857f.png)

**Comment by codeforequity-at** [comment]
The pull request is still open (https://github.com/codeforequity-at/botium-connector-directline3/pull/23).

**Comment by vijaysimh** [comment]
For reference am attaching my excel sheet screesnhot,please have a look on it and suggest whether this has to be rectified by me(Adaptive card)
![image](https://user-images.githubusercontent.com/30192609/58248477-dafc6680-7d79-11e9-9b48-931e4bbdfe29.png)

**Comment by codeforequity-at** [comment]
What I can spot in the Excel is that currently simulation of button clicks is not supported in utterances. You will have to include the button click in the convo, not in the utterances list.

**Comment by vijaysimh** [comment]
Resolved by adaptive.convo.txt instead of excel as not working as expected (excel) and prerequisite of update npm (cmd) for botium cli and botium connector directline3 .
