### ISSUE TITLE
[SimpleRestContainer] Remove body encoding

### ISSUE THREAD

**Issue by BreadAndRoses95** [codeforequity-at/botium-core#29]
Hey,

Using your project I noticed that the SimpleRestContainer (src/containers/SimpleRestContainer.js) had a strange behavior building the request : the message was encoded using the encodeURIComponent()  method for both the URI and the body, which is not useful and led all my tests to fail. I have modified the container to avoid this on a fork, should I ask for a pull request ? 

Thanks,

**Comment by codeforequity-at** [comment]
You are right, this is generally dumb, but not in all cases (if the user input is part of a HTTP GET Parameter, for example). I will take care of it myself, because I need this to work for one of my own use cases.

**Comment by BreadAndRoses95** [comment]
Have a look here  [](https://github.com/codeforequity-at/botium-core/compare/master...BreadAndRoses95:master), changed it to encode for the URI only.

**Comment by codeforequity-at** [comment]
thanks. merged your fork and published new npm 1.3.8.
