### ISSUE TITLE
While trying to run a chatbot, previously executed chatbot is get executed.

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#299]
In the Enterprise version 1.6.0 , After executing a particular chatbot with webdriverio technology and intermittently while trying to execute a Generic HTTP/JSON Interface Chatbot, the previously executed WebdriverIO is getting executed again.

Also unless the page is completely refreshed, execution status is not reflecting in the page

**Comment by codeforequity-at** [comment]
Pls be more specific

**Comment by Aishwarya-J-S** [comment]
I was executing a project with Chatbot Technology as WebdriverIO for more than 10 times repeatedly. 

After some time I was trying to execute a project with Chatbot Technology as Generic HTTP/JSON Interface, At that point , it executed the project with WebdriverIO Chatbot technology which was executed earlier

This problem persists for some time and works as expected after refreshing or by itself.

**Comment by codeforequity-at** [comment]
still happening with the latest Botium Box ?

**Comment by Aishwarya-J-S** [comment]
Currently I am not running that. So I am not aware whether it is still happening. We will close this issue as of now. If it persists in the future, will raise the concern. Thank you.
