### ISSUE TITLE
BaseContainer missing Clear method

### ISSUE THREAD

**Issue by BreadAndRoses95** [codeforequity-at/botium-core#30]
Hey,

I think BaseContainer.js misses Clear() method, that's why after() method leads to the following error while running the tests : " 

"after all" hook:
     TypeError: botiumContext.container.Clear is not a function
"

**Comment by codeforequity-at** [comment]
Thanks, this was a typographic error in the source code, the method is named "Clean", not "Clear". New npm botium-cli@0.0.5 is available.
