### ISSUE TITLE
Verify Http URL is clickable and lands to expected Page

### ISSUE THREAD

**Issue by vijaysimh** [codeforequity-at/botium-core#303]
Hi in the application ,the response is as follows.

For Example: Click on this URL(http://google.com) -Here we need to verify it leads to page not found (404) or landed as expected page.As iknow its available only in enterprise edition ,as we are not using enterprise/community  and only basic version .Is there a way to click URL and verify the URL status.

**Comment by ujja** [comment]
https://stackoverflow.com/questions/56222058/how-can-i-use-hyperlink-assertion-using-botium-asserter-for-chatbot-developed-us

**Comment by ujja** [comment]
Did it worked before you added asserer? It looks to me not an asserter related problem.

Check please https://github.com/codeforequity-at/botium-core/issues/301

If it does not help you because you have other connector, open other issue please (with verbose logs, described in ticket)

**Comment by vijaysimh** [comment]
Please find the Error :As i tried to add HASLINK before URL which has text response as: #bot - Here you go, Click on the 'Order' link to access details [Order](http://intranet.xyz.com/functions/O.pptx)

For this i have added HASLINK before the URL starts.Please correct if the syntax is wrong and provide example for the same response..
Botium Test-Suite
    1) adaptive
  0 passing (6s)
  1 failing

  1) Botium Test-Suite
       adaptive:
     TranscriptError: Error: adaptive/Line 12: Expected bot response (on Line 9: #me - Delete Order) "Here you go, Click on the 'Order' link to access details [Order](http://intranet.xyz.com/functions/O.pptx)" to match one of "Here you go, Click on the 'Order' link to access details [Order](**HASLINK** http://intranet.xyz.com/functions/O.pptx)"

**Comment by codeforequity-at** [comment]
HASLINK has to start the line for Botium to recognize it. 

```
#bot
Here you go, Click on the 'Order' link to access details
HASLINK http://intranet.xyz.com/functions/O.pptx

```

**Comment by vijaysimh** [comment]
Hi Botium Team,

As observed the response is of single Line ,adding URL separately to next Line yields to error "bot says nothing".Please have a Look exactly on bot response as added HASLINK it gives "transcript error as it matching with expected"

Single Line response.
Here you go, Click on the 'Order' link to access details [Order] (http://intranet.xyz.com/functions/O.pptx)

As suggested tried with above syntax:
Here you go, Click on the 'Order' link to access details [Order] 
HASLINK (http://intranet.xyz.com/functions/O.pptx)

**Comment by ujja** [comment]
It not easy to follow this problem. Pease use formatting, and be more specific.

(1) bot says nothing
I suppose your test looks like this:

`
#bot
How was my XYZ?

#bot
HASLINK www.google.com | http://intranet.xyz.com
`

So you expect two separate responses from Bot, and i suppose it sends just one, so you got this "bot says nothing".

(2) matching with expected

If bot answer is this: 
`
Here you go, Click on the 'Order' link to access details [Order] (http://intranet.xyz.com/functions/O.pptx)
`

And you are testing it this way:

`
Here you go, Click on the 'Order' link to access details [Order]
HASLINK (http://intranet.xyz.com/functions/O.pptx)
`

(and botium.json has asserter)
`
"ASSERTERS": [
            {
              "ref": "HASLINK",
              "src": "botium-asserter-basiclink"
            }
          ]
`
(and you did not change the default matching mode (SCRIPTING_MATCHING_MODE capability includeLowerCase)

Then it must work well

**Comment by vijaysimh** [comment]
#me
Delete Order

#bot(SINGLE LINE RESPONSE) 
**HASLINK** Here you go, Click on the link to get details [Order] (http://xyz.com/workingtogether/functions/Source**%20to%20Pay/P%**20User%20Guide/How2PO.pptx)

1.Here HASLINK is added at beginning of the sentence.  I observed (%)symbol is coming in between every url as response.
2. As suggested  by you (post running command prompt: npm botium-asserter) ASSERTERS is been added in Botium.json and  SCRIPT_MATCHING_NODE to includeLowerCase and regex (Botium.json) .

If any changes are to be made ,please suggest as its on high priority.

**Comment by ujja** [comment]
'''HASLINK Here you go, ...''' is not good. We suggested checking this way:
```
#bot
Here you go, Click on the 'Order' link to access details [Order]
HASLINK (http://intranet.xyz.com/functions/O.pptx)
```

This means two checks against response:
1) Does the response contains all the words 'Here you go, Click on the 'Order' link to access details [Order]'? If it has more words, like the URL, it is ok. (thats why is SCRIPT_MATCHING_NODE .includeLowerCase important)
2) Does the response cointains the 'http://intranet.xyz.com/functions/O.pptx' link, and is it active?

You can think them as two function calls. This is not the right format, just a human readable:
```
#bot
CHECK_WORDS_IN_RESPONSE(Here you go, Click on the 'Order' link to access details [Order])
HAS_RESPONSE_LINK(http://intranet.xyz.com/functions/O.pptx)
```

**Comment by vijaysimh** [comment]
Entire Response what am specifying along with URL must come as single row in Excel or in.convo.txt file ,if splitted response to next Line it fails.Please provide solution without splitting to next Line or ROW.

As suggested tried with below syntax:

#bot
CHECK_WORDS_IN_RESPONSE(Here you go, Click on the 'Order' link to access details [Order])
HAS_RESPONSE_LINK(http://intranet.xyz.com/functions/O.pptx

In convo.txt file ,

#bot
CHECK_WORDS_IN_RESPONSE(Here you go, Click on the 'Order' link to access details [Order])
HAS_RESPONSE_LINK(http://intranet.xyz.com/%20Documents/Source%20to%20Pay/STP%20User%20Guides/How%20PO.pptx)

**Gives Error in CMD as :**
TranscriptError: Error: adaptive/Line 12: Expected bot response (on Line 9: #me - Delete PO) "Here you go, Click on the 'Order' link to  get details [Order](http://intranet.xyz.com/%20Documents/Source%20to%20Pay/STP%/How%20PO.pptx)" to match one of "CHECK_WORDS_IN_RESPONSE(Here you go, Click on the 'Order' link to access details [Order]) HAS_RESPONSE_LINKhttp://intranet.xyz.com/%20Documents/Source%20to%20Pay/STP%How%20PO.pptx)"

**Comment by codeforequity-at** [comment]
there is no way to do it in one line. as ujja wrote above, this is the way to do it in botium:

```
#bot
Here you go, Click on the 'Order' link to access details [Order]
HASLINK http://intranet.xyz.com/functions
```

as ujja wrote, the human readable sample was to make clear whatd going on in botium, actual syntax is different.

the sample in this post is how to do it in botium.
