### ISSUE TITLE
Cannot read property of 'Recognise' in botium-connector-alexa-avs after amazon-transcribe

### ISSUE THREAD

**Issue by StoutyAlex** [codeforequity-at/botium-core#304]
**Describe the bug**
When I run the tests using the botium-cli in debug mode all seems fine and after the transcribe is completed the job is downloaded and the response is recognised. However after this the program crashes out due to a type error;

```
 botium-connector-alexa-avs-stt-amazon-transcribe S3 download transcribe succesfull { Deleted:
  botium-connector-alexa-avs-stt-amazon-transcribe    [ { Key: 'to-transcribe-job-ool6sbbzho.json' },
  botium-connector-alexa-avs-stt-amazon-transcribe      { Key: 'to-transcribe-source-ool6sbbzho' } ],
  botium-connector-alexa-avs-stt-amazon-transcribe   Errors: [] } +185ms
  botium-connector-alexa-avs-stt-amazon-transcribe Recognize finished: BBC. +4ms
  botium-connector-alexa-avs-main Answer converted to text "BBC." succeeded +1m
  botium-connector-alexa-avs-main Answer converting to text, format "AUDIO_MPEG", size 26545... +0ms
(node:44959) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Recognize' of null
    at processingPromise.then (/usr/local/lib/node_modules/botium-cli/node_modules/botium-connector-alexa-avs/index.js:68:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:44959) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44959) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
DEBUG=botium* botium-cli run --config ./botium.json --convos ./spec/convo/

**Expected behavior**
Tests to pass and audio to be transcribed

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Version (botium-connector-avs-alexa: 0.0.4, botium-bindings: 2.0.13)

**Comment by ujja** [comment]
Yes, it looks text is converted to speech well with transcribe, Alexa answered to text, but Connector was not able to convert the answer back to text.

Speech to text is not configured well.

What is the value of ALEXA_AVS_STT Capability? (It must be GOOGLE_CLOUD_SPEECH or AMAZON_TRANSCRIBE)

**Comment by StoutyAlex** [comment]
It was set at 'AMAZON_TRANSCRIBE'
Here is the full json file: 

```
"Capabilities": {
      "PROJECTNAME": "Botium Project Alexa AVS",
      "CONTAINERMODE": "alexa-avs",
      "ALEXA_AVS_AVS_CLIENT_ID": "amzn1.application-oa2-client.1xxx",
      "ALEXA_AVS_AVS_CLIENT_SECRET": "xxx",
      "ALEXA_AVS_AVS_REFRESH_TOKEN": "xxx",
      "ALEXA_AVS_AVS_LANGUAGE_CODE": "en-GB",
      "ALEXA_AVS_TTS": "AMAZON_POLLY",
      "ALEXA_AVS_TTS_AMAZON_POLLY_REGION": "eu-west-1",
      "ALEXA_AVS_TTS_AMAZON_POLLY_ACCESS_KEY_ID": "xxx",
      "ALEXA_AVS_TTS_AMAZON_POLLY_SECRET_ACCESS_KEY": "xxx",
      "ALEXA_AVS_TTS_AMAZON_POLLY_LANGUAGE_CODE": "en-GB",
      "ALEXA_AVS_STT": "AMAZON_TRANSCRIBE",
      "ALEXA_AVS_STT_AMAZON_TRANSCRIBE_REGION": "eu-west-1",
      "ALEXA_AVS_STT_AMAZON_TRANSCRIBE_ACCESS_KEY_ID": "xxx",
      "ALEXA_AVS_STT_AMAZON_TRANSCRIBE_SECRET_ACCESS_KEY": "xxx",
      "ALEXA_AVS_STT_AMAZON_TRANSCRIBE_LANGUAGE_CODE": "en-GB",
      "ALEXA_AVS_STT_AMAZON_TRANSCRIBE_BUCKET_NAME": "xxx"
    }
```

**Comment by ujja** [comment]
Caps are good. Could you send all logs?

**Comment by StoutyAlex** [comment]
The log was quite long so attached it to a pastebin

https://pastebin.com/8ZCYNcXV

**Comment by ujja** [comment]
I dont know what is the response from Alexa. But Transcribe says it is "BBC.". And this answer is coming very slow. You got a timeout, and your test is failed after 60 000 ms.

You should not got this exception, just a failed test. We will fix it, but it does not help you.

You can increase timeout (WAITFORBOTTIMEOUT Capability), or use Google speech to text (it is mutch faster).

**Comment by codeforequity-at** [comment]
The Amazon Transcribe service is rather slow, compared to Google Speech, so the Botium timeouts are easily reached. We recommend switching to Google Speech.
