### ISSUE TITLE
Support AudioPlayer Directive

### ISSUE THREAD

**Issue by StoutyAlex** [codeforequity-at/botium-core#313]
**Is your feature request related to a problem? Please describe.**
Recently opened a issue regarding adding capabilities to support audio responses on Alexa (https://github.com/codeforequity-at/botium-core/issues/312).I cloned the botium-connecta-alexa-smapi and hard-coded the device capbilities to see if it would work and realises that the connector wont support directives and will only work when SSML is passed into the response.

Here is the response the skill gives back 
```{
  "version": "1.0",
  "response": {
    "directives": [
      {
        "type": "AudioPlayer.Play",
        "playBehavior": "REPLACE_ALL",
        "audioItem": {
          "stream": {
            "url": "https://open.test.bbc.co.uk/mediaselector/6/redir/version/2.0/vpid/p01lxqsn/mediaset/voice-hls/proto/https",
            "token": "urn:news:48468780-8df0-11e9-9f2f-691a46689800:Xzxlh.9MphIbmNxI9nSKYl1_MzE6HokY:p01lxqsn",
            "offsetInMilliseconds": 0
          },
          "metadata": {
            "title": "Welcome to BBC News",
            "art": {
              "sources": [
                {
                  "url": "https://ichef.test.bbci.co.uk/images/ic/480x480/p01m4h78.jpg"
                }
              ]
            }
          }
        }
      }
    ],
    "shouldEndSession": true
  },
  "userAgent": "ask-node/2.6.0 Node/v10.11.0",
  "sessionAttributes": {}
}
```

There is no outputSpeech object on the response causing an error to be thrown on botium saying `Uncaught TypeError: Cannot read property 'text' of undefined`

**Describe the solution you'd like**
The ability to use the MEDIA *url* syntax in the #bot step of a conv to result to the url given from the audioItem.stream.url

Example:
```
#bot 
MEDIA https://open.test.bbc.co.uk/mediaselector/6/redir/version/2.0/vpid/p01lxqsn/mediaset/voice-hls/proto/https
```

**Describe alternatives you've considered**
Not looked into many alternatives as this is close to a bug and not really an option

**Additional context**
One possible feature could be the ability to check the metadata an audioObject passes back using the same syntax as MEDIA 

example: `TITLE Welcome to BBC News` but this isnt major

**Comment by codeforequity-at** [comment]
This is closely related to #312 - when we add support for audio capabilities, we will have to adapt the response assertions as well.

**Comment by codeforequity-at** [comment]
Part of latest connector build
https://github.com/codeforequity-at/botium-connector-alexa-smapi
