### ISSUE TITLE
How can Voice be tested through the HTTP/JSON Interface

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#322]
Can API Level testing be done with Voice?

I am passing a speak tag along with the text tag. So when some text is added to voice tag, it voice outs the response.

How can it be tested through Botium?

**Comment by codeforequity-at** [comment]
Botium will always be based on text. When you have the "speak" tags in the text, as with Alexa for example, Botium will do just text comparisions (when using the "normalize" feature, the speak-tags are removed from the Alexa response before doing the assertions).

So, from Botium point of view, there is nothing special to test a voice bot.
