### ISSUE TITLE
How to import the test set in the latest Botium EE

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#324]
There is an option provided to export the test sets in zip format from the local repository

Where is the option to import the test sets?

**Comment by codeforequity-at** [comment]
Not yet existing. It is in our backlog, but up to now we don't saw much need for this.
The recommended development process for test sets is described in the Botium Wiki: 
https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/33234/Best+Practice+Test+Case+Development

**Comment by codeforequity-at** [comment]
Part of Botium Box 1.7.4.
