### ISSUE TITLE
How to delete a Test project in the Botium latest EE

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#325]
I am using the latest botium EE. 

Can test project be created only if required ? 

Every time when I run a test session, along with the session, a test project is getting created.
Can it be run only if required?

I could clear only the test sessions but not the test projects. How can I clear the existing test projects?

**Comment by codeforequity-at** [comment]
A test project should only created once (with the Quickstart menu item), and then it can be started over and over again. And of course, you can delete a test project in the "Danger Zone" section.

**Comment by Aishwarya-J-S** [comment]
How can I delete a test project. I am not able to find the Danger Zone in a test project
![image](https://user-images.githubusercontent.com/49233293/61022059-bf006300-a3c1-11e9-8785-659e69a45660.png)

**Comment by Aishwarya-J-S** [comment]
Also I tried deleting the project from back end by deleting my projects in the botiumworks folder.

Test Projects and test sessions were deleted from the Test projects and test results page but in the dashboard it is still displaying all the deleted projects in the project filter option with empty details
![image](https://user-images.githubusercontent.com/49233293/61025355-16a4cb80-a3ce-11e9-92e6-1ce95a2e794d.png)

How can I remove this?

**Comment by codeforequity-at** [comment]
The screen resolution is too low, please increase (or decrease browser zoom) to make the Danger Zone visible:
![image](https://user-images.githubusercontent.com/26287439/61026738-7d1cf000-a3b4-11e9-90ae-0d2003978bd4.png)

Cleaning the botiumworks folder doesn't help, it's just a temporary directory.
