### ISSUE TITLE
Lodash security vulnerability

### ISSUE THREAD

**Issue by alopix** [codeforequity-at/botium-core#326]
A security vulnerability was found in [lodash](https://snyk.io/vuln/npm:lodash).
I saw it's a dependency in a few of the botium projects. Would be great if you could release updates.

**Comment by codeforequity-at** [comment]
Will take care at the next build. Noticed it as well in our continuous builds.

**Comment by alopix** [comment]
Some more vulnerabilities. Are you gonna release updates to fix them?

**Comment by codeforequity-at** [comment]
of course.
