### ISSUE TITLE
uploading custom JS script onto Botium Box ? 

### ISSUE THREAD

**Issue by siliconberry** [codeforequity-at/botium-core#327]
Hi, 

Is there a way to upload a custom JS file along with botium.json script onto Botium Box ? 

Thanks

**Comment by siliconberry** [comment]
Nevermind. Found a way in [https://medium.com/@floriantreml/botium-in-a-nutshell-part-6-e2e-testing-with-botium-box-9bd8acdf5a70] here. Thanks much for the tool !

**Comment by codeforequity-at** [comment]
Although you found a solution, it's good input to make this easier. Added to our backlog to add a script/file upload form to the box.

**Comment by codeforequity-at** [comment]
This is part of the current sprint.
