### ISSUE TITLE
Can utterances file be used globally across the test sets

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#328]
Currently we have to create utterance file for every test set. Can it be used globally across all the test sets. Is there any option to create utterance file which can be used in all the test sets?

**Comment by ujja** [comment]
Everything is global to TestProject. How to use them, is up to you. You can
dedicate a TestSet as global (name or tag it as global) and use
"namespaces", so they will look as local.

example (jut for humans, botium does not understand this format):
```
Testsets [{
  name: global
  tags:[global]
  utterances: [
    "greeting"
   ]
},
{
  name: uk
  utterances: [
    "uk.greeting"
   ]
}
```

Aishwarya-J-S <notifications@github.com> ezt írta (időpont: 2019. júl. 12.,
P, 8:52):

**Comment by ujja** [comment]
Everything is global to TestProject. How to use them, is up to you. You can dedicate a TestSet as global (name or tag it as global) and use "namespaces", so they will look as local.

example (jut for humans, botium does not understand this format):
```
Testsets [{
  name: global
  tags:[global]
  utterances: [
    "greeting"
   ] 
},
{
  name: uk
  utterances: [
    "uk.greeting"
   ] 
}
```

**Comment by codeforequity-at** [comment]
Another option is to use "Test Set Dependencies" - you can have one shared test set with all your utterances, and define this as dependency in your other test sets ...


![image](https://user-images.githubusercontent.com/26287439/61116468-ccd2e880-a494-11e9-8fa5-21ab550c60f0.png)
