### ISSUE TITLE
hyperlink asserter is not working.

### ISSUE THREAD

**Issue by radhabasida** [codeforequity-at/botium-core#331]
hyperlink assertion is not working.

In basic asserter js file while accessing botmsg, b.payload is written while in webdrivoerio index file botmsg json is created with button.payload attribute.

basic asserterjs file need to be changed, in if(botmsg.buttons) condition, b.payload needs to be written instead of b.imageuri

same would apply form media condtion.

after above changes hyperlink asserter is worked. attaching the screenshot for ref
![Screenshot from 2019-07-22 19-41-43](https://user-images.githubusercontent.com/48954471/61639982-2370cb80-acba-11e9-882f-a5fd88b82455.png)

**Comment by codeforequity-at** [comment]
@radhabasida thanks for the analysis

@stefan-sev please add the "payload" (for buttons) and the "mediaUri" to the asserter
