### ISSUE TITLE
How can we validate variations in the responses of bot?

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#335]
For few scenarios, the bot is expected to respond with multiple responses for the same user input

For example, When the user input is "How are you" then the bot will respond with variation in the responses (by providing weightage to the bot responses)

How can I customize the bot response with multiple replies in the way that the test case should get passed when the bot reply matches with any of the variations

**Comment by ujja** [comment]
Yes with Utterances

Example: create a file howareyouanswer.txt for your project.

```
HOW_ARE_YOU_ANSWER
Fine
ok
```

And use HOW_ARE_YOU_ANSWER in the bot section of convo. So all alternatives are accepted.

Complete example see [here for text](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/48922633/Composing+in+Text+files#Utterances-Syntax) and [here for Excell](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/48922649/Composing+in+Excel+files#Utterances-Syntax)
