### ISSUE TITLE
Capability/Source configuration should be possible via environment variables

### ISSUE THREAD

**Issue by codeforequity-at** [codeforequity-at/botium-core#34]
Overwrite configuration file

**Comment by BreadAndRoses95** [comment]
Hey,

Have a look here, [https://github.com/BreadAndRoses95/botium-core/commit/53ec9117a8f8bc9f7ca836a6c05c04367aca39af](https://github.com/BreadAndRoses95/botium-core/commit/53ec9117a8f8bc9f7ca836a6c05c04367aca39af)
Let me know if it suits you or not

**Comment by BreadAndRoses95** [comment]
Hej,

Do you mean be able to set capabilities other than the ones given inside the Capabilies.js module? In this case, how would you know which one has to be set as a capabilities or a source? Otherwise you could just check for capabilities inside the Capabilities module for the name.

**Comment by codeforequity-at** [comment]
Well, my idea was that in CI environments, it is typically very easy to hand over configuration to the build process by setting environment variables than doing it by configuration files or by code. And moreover, it is generally not a good idea to store secret data (like user credentials) in configuration files - better hand it over to the programs with environment variables.

So, my goal is that this should be possible:

```
const driver = new BotDriver()
driver.BuildFluent()
  .Start()
  .UserSaysText('hi bot')
...
```

No configuration in code, everything read from environment variables. Typically, for each possible capability (in Capabilities.js), the resolution order should be:

1. If it is set with setCapabilities/setCapability, use it
2. Else if an environment variable BOTIUM_<capability_name_in_uppercase> is available, use it
3. Else take value from Default.js

Same applies for sources of course.

**By the way: it's awesome that you are contributing code to this project! many thanks!!!!!**

**Comment by BreadAndRoses95** [comment]
Ok, will have a look tonight or tomorrow morning and will come back to you, this will have impacts on the botium-cli I think, will check this out too.

**Comment by codeforequity-at** [comment]
This is pretty close to my intentions - spotted 2 issues: 
* with this code, the env variable has higher prio than capability in code. I am not sure if this is a good thing or not - maybe yes.
* the code should be placed in the "Build" and "BuildCompiler", function so that just before everything is evaluated the replacement is done

the reason for the setCapabilities/setSources function is to provide a "fluent" api to the user, or to give the user the possibility to do it so. it doesn't make much effort to provide this fluent api and makes client code readable.

**Comment by BreadAndRoses95** [comment]
- If we do check for env variables inside Build and BuildCompiler, this will make the env having an higher prioriy than the setCapabilities I think right now this is the good order. Let me explain my point with an example 
```
driver = new BotDriver()
driver.setCapabilities(caps)
driver.BuildFluent().Start()
.UserSaysText("hi")
....
```
This would lead the env variables to overwrite the capabilities set by the code, which is not what you wanted I think?

I was speaking about the botium-cli package, not the botium-core, because you said you wanted 

> No configuration in code, everything read from environment variables.

So no testmybot.json or other, or did I missed something?

**Comment by codeforequity-at** [comment]
I got it. I suggest to leave it in the constructor, but do it like so:

```
constructor (caps = {}, sources = {}, env = {}) {
    this.caps = Object.assign({}, Defaults.Capabilities)
    this.sources = Object.assign({}, Defaults.Sources)

    ... do the stuff with the environmen variables

    this.caps = Object.assign(this.caps, caps)
    this.sources = Object.assign(this.sources , sources )
  }
```

So, what happens:
* first, the defaults are inserted
* then, the environment variables
* finally, the caps/sources set programmatic are used to overwrite the previous
* every subsequent calls to setCapabilites / setCapability etc will overwrite the previous again

This is exactly how I wanted it to work.

With Botium-CLI, the configuration file should still be used if present, but it should not reject if no configuration file is given - in this case it should just assume that environment variables are present, and botium will fail anyway if not given.

Most common use case is a mixture of configuration from file and from environment variables. This way, you are open to configure settings shared in different environments (dev/staging/production) in configuration files (can be versioned just like source code itself), and hand over environment specific settings in env variables.

**Comment by codeforequity-at** [comment]
I created a feature branch for this change: ENH_34_settings_from_env_variables

**Comment by BreadAndRoses95** [comment]
I added what you asked for on my fork, can have a look there cause I don't know exactly how to commit/push on your branch ?

**Comment by codeforequity-at** [comment]
I noticed that you were able to merge into the feature branch. Actually, I don't know yet how it would work best in future - to do it with forks or to make feature branches - there is nothing like a "contribution guide" right now.
I will merge it into master and publish a new package out of the feature branch later this day.

**Comment by codeforequity-at** [comment]
Closing this. thanks for your help on this enhancement.
