### ISSUE TITLE
synchronized from a convo file

### ISSUE THREAD

**Issue by hunkim** [codeforequity-at/botium-core#340]
**Describe the bug**
When botium-cli sens messages to a chatbot, it seems it send two (or messages) simultaneously. (or send the next message before it gets a message from a bot.)

As a result, the bot is not working properly.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/901975/62255937-665d3c80-b43a-11e9-805e-c02018c18a12.png)

This is a history using botium-cli. (It seems it sends Sung, k12345, ok simultaneously.)

This a manual testing which works properly.
![image](https://user-images.githubusercontent.com/901975/62255977-8a208280-b43a-11e9-91c9-0fb71fd6c16d.png)

**Desktop (please complete the following information):**

**Additional context**
Not sure it's a problem of Dialogflow. 

Or simply can we add sleep between two messages?

**Comment by codeforequity-at** [comment]
what does your convo file look like ?

**Comment by hunkim** [comment]
Here we are:

```txt
Test
#me
what is my mid-term score?
#bot
#me
Sung
#bot
OK, Sung, what is your id?
#me
k12345
#me
ok
```

**Comment by hunkim** [comment]
Here we are:

```
Test
#me
what is my mid-term score?
#me
Sung
#me
k12345
#me
ok
```

**Comment by hunkim** [comment]
Or this:

```
Test
#me
what is my mid-term score?

#bot

#me
Sung

#bot

#me
k12345

#bot

#me
ok

#bot
```

**Comment by codeforequity-at** [comment]
Depending on the convo structure, Botium sends to the bot or waits for the bot's answer. Your convo files are fine.
Can you please enable the --verbose switch and attach the log output here (mask your api keys in the log output please).

**Comment by hunkim** [comment]
I will post the log soon.

BTW is there any way to force botium to waits for the bot's answer?

Thanks.

**Comment by codeforequity-at** [comment]
For dialogflow, it is a synchronous API call to the Dialogflow API, so Botium implicitly waits for the bot's answer - there is no such thing as a bot-triggered message with Dialogflow.

**Comment by hunkim** [comment]
Hmm.

>  Botium implicitly waits for the bot's answer

Then, it does not make sense in my case. I'll post the log soon.

Sung

**Comment by codeforequity-at** [comment]
> Then, it does not make sense in my case. I'll post the log soon. Sung

I think the problem in your case is related to context handling - the logs will help me in analyzing this ...

**Comment by hunkim** [comment]
Attached!

Thanks for your help.

[debug.log](https://github.com/codeforequity-at/botium-core/files/3456546/debug.log)

**Comment by codeforequity-at** [comment]
Cannot spot anything unusual from the logfile. When sending the "k12345" id, in dialogflow again triggers the "exam_score_enquery - ask_name" intent, replacing the name slot with the id.
Would it be possible to export your dialogflow agent and send it to me ? (if not here on github, then by email florian.treml "at" botium.at).
