### ISSUE TITLE
Can we use wildcard in bot response to test?

### ISSUE THREAD

**Issue by hunkim** [codeforequity-at/botium-core#341]
**Is your feature request related to a problem? Please describe.**
It seems the current testing only supports exact matching.

For example, see the test error log message:

```bash
1) Botium Test-Suite
       Test:
     TranscriptError: BotiumError: Test/Line 5: Expected bot response (on Line 2: #me - what is my mid-term score?) "What is your name?" to match one of "What's your name?"
```

Since the bot's output will vary, I just want to check if bot's message includes "name".

My current conv file is:
```
Test
#me
what is my mid-term score?

#bot
What's your name?
```

But I want to write something like:
```
Test
#me
what is my mid-term score?

#bot
*name*
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ujja** [comment]
wildcards are not supported

Write just "name" please. As default botium does not check exact match, but contains match. See: [matching mode](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360603/Botium+Configuration+-+Capabilities#SCRIPTING_MATCHING_MODE)

(Other way to tune matching, are the [Utterances](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/491664/Botium+Scripting+-+BotiumScript#Utterances))
