### ISSUE TITLE
Empower bot-side utterances

### ISSUE THREAD

**Issue by xmichele** [codeforequity-at/botium-core#342]
Hello,

for utterance file bot-side: on each row there is an alternative that will be considered as test passed after comparison with bot textual answer. 
My questions:
- can we put the keyword #begin on only some rows of utterance file bot side?
- can we mark the test passed if a text comparison is verified OR a button is displayed

Thanks

**Comment by ujja** [comment]
utterance file is bot-side if it is used just from #bot section of the conversation. But utterance itself is not dedicated to it.

They are just key->values mapping. Can be used optionally to extend the functionality of the Conversation.  #begin, and buttons belongs to the [Conversation](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/491664/Botium+Scripting+-+BotiumScript#Convos).

**Comment by ujja** [comment]
Any news?
