### ISSUE TITLE
Scheduling Test Run and Sending Mail from Botium Box

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#344]
I was trying to run the script to schedule the test run and to send mail from botium by referring the following link:
https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/37584901/Schedule+Test+Runs+and+Send+Email+Notification

While executing the Command Line Script provided, I am getting the mail soon after the trigger is initiated. It is not waiting for the status of the Test Project to complete. It is sending the mail when the status is Pending/before it is ready before the test cases are completely executed. As a result, whenever I trigger that script I am getting a mail that the build has failed.

Also the pdf is not getting downloaded when that script is run. I am getting the following result
Calling http://host:port/api/triggerbuild/Test Project?APIKEY=XXXXXXXXXX&REPORTER=json to run build ...
Build returned response code PENDING
Calling http://host:port/api/build/Test Project?APIKEY=XXXXXXXXXX&REPORTER=pdf to download PDF report ...
PDF report returned response code 404
Email sent.

Is there any references to get the API Details?

**Comment by codeforequity-at** [comment]
you should add the WAIT=1 parameter to the webhook call

Aishwarya-J-S <notifications@github.com> schrieb am Do., 1. Aug. 2019,
16:26:

**Comment by Aishwarya-J-S** [comment]
But still it gives 404 error to download pdf report

Calling  http://host:port/api/triggerbuild/Test Project?APIKEY=XXXXXXXXXXXX&REPORTER=json&WAIT=1 to run build ...
Build returned response code READY
Calling  http://host:port/api/triggerbuild/Test Project?APIKEY=XXXXXXXXXXXX&REPORTER=pdf to download PDF report ...
**PDF report returned response code 404**
Email sent.

**Comment by codeforequity-at** [comment]
did you generate the webhook link in botium box ?

**Comment by Aishwarya-J-S** [comment]
I have followed the instructions as on the link https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/37584901/Schedule+Test+Runs+and+Send+Email+Notification

How is the webhook link generated in botium box

**Comment by codeforequity-at** [comment]
![image](https://user-images.githubusercontent.com/26287439/62353596-421d6080-b50b-11e9-8455-4cafc1194834.png)

**Comment by Aishwarya-J-S** [comment]
Yeah, We have configured that Test Project code in the BOTIUM_PROJECT_CODE of the script.

We have configured the BOTIUM_URL, BOTIUM_API_KEY and BOTIUM_PROJECT_CODE  in that script

Is there anything else to be done?

**Comment by codeforequity-at** [comment]
The url to download the PDF Is different from the url to trigger the build. You can see this in the mentioned article:

![image](https://user-images.githubusercontent.com/26287439/62363402-8e729b80-b51f-11e9-9275-7d48bc1a864b.png)

**Comment by Aishwarya-J-S** [comment]
Yeah, when it was not working, we just tried to give that triggerbuildAPI.

We have tried with the same script as provided but still unable to get the pdf

Calling http://host:port/api/triggerbuild/TestProject?APIKEY=XX&REPORTER=json&WAIT=1 to run build ...
Build returned response code READY
Calling http://host:port/api/build/TestProject?APIKEY=XX&REPORTER=pdf to download PDF report ...
PDF report returned response code 404
Email sent.

Please help. What can be the possibility that it is not working?

**Comment by codeforequity-at** [comment]
you have to hand over the build id to the pdf endpoint, not the project code

**Comment by Aishwarya-J-S** [comment]
You were right, I have changed it and still facing that issue

 http://host:port/api/triggerbuild/TestProject?APIKEY=XXX&REPORTER=json&WAIT=1 to run build ...
Build returned response code READY
Calling http://host:port/api/build/BUILD_20190802110534?APIKEY=XXX&REPORTER=pdf to download PDF report ...
PDF report returned response code 404
Email sent.

**Comment by codeforequity-at** [comment]
The build id has to be part of the first call as well

**Comment by Aishwarya-J-S** [comment]
Yeah, it worked. Thank you so much
