### ISSUE TITLE
Bot says nothing (botium-connector-google-assistant)

### ISSUE THREAD

**Issue by honkeat** [codeforequity-at/botium-core#346]
**Describe the bug**
Bot says nothing error appear randomly when bot actually replies (when i checked the history of my bot it shows the bot did replied)

**To Reproduce**
Run tests that are long enough (50 tests with bot) and tests will fail at random points with error "bot says nothing"

**Expected behavior**
Test to pass

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by codeforequity-at** [comment]
Pls attach log file
