### ISSUE TITLE
How to schedule the test run with the details of the test cases

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#347]
Currently while scheduling the test run and sending the mail, it is sending only the overview of the test session as follows
- Test Project
- Chat bot Under Test
- Total Test cases
- Succeeded Test cases
- Failed Test cases (If Failed, the Error is shown)
- Status of Test Session - FAILED/OK

But How can I view the Detailed Test Report which includes the name of the passed Test cases and Failed Test Cases.(Probably in a table format)

Also I could see that in a mail report, it is sending the details of previous execution results along with the last executed result. Is it expected or a bug?

**Comment by codeforequity-at** [comment]
The current PDF export contains only a part of the information. To see the details, you have to navigate to the Botium Box. The PDF export can be customized on individual request.

I don't know what your script is actually doing, so I don't know if it is expected or a bug. Can you please attach your script here, and maybe forward one of the generated mail reports to florian.treml at botium.at

**Comment by Aishwarya-J-S** [comment]
Please find the script below

#!/bin/bash

BOTIUM_URL=http://hostname:port
BOTIUM_API_KEY=APIKey
BOTIUM_BUILD_ID=BUILD_$(date +%Y%m%d%H%M%S)
BOTIUM_PROJECT_CODE=XXXXXXX
TEMP_DIR=/tmp


URL_TRIGGER=${BOTIUM_URL}/api/triggerbuild/${BOTIUM_PROJECT_CODE}?APIKEY=${BOTIUM_API_KEY}\&BUILDID=${BOTIUM_BUILD_ID}\&WAIT=1\&REPORTER=json
URL_PDF=${BOTIUM_URL}/api/build/${BOTIUM_BUILD_ID}?APIKEY=${BOTIUM_API_KEY}\&REPORTER=pdf
URL_CSV=${BOTIUM_URL}/api/build/${BOTIUM_BUILD_ID}?APIKEY=${BOTIUM_API_KEY}\&REPORTER=csv

echo Calling ${URL_TRIGGER} to run build ...
RESPONSE_TRIGGER=$(curl ${URL_TRIGGER} 2>/dev/null | jq -r '.status')
echo Build returned response code ${RESPONSE_TRIGGER}

echo Calling ${URL_PDF} to download PDF report ...
RESPONSE_PDF=$(curl --write-out %{http_code} --silent --output ${TEMP_DIR}/${BOTIUM_PROJECT_CODE}.pdf ${URL_PDF})
echo PDF report returned response code ${RESPONSE_PDF}

if [ ${RESPONSE_TRIGGER} = READY ] ; then
        MAIL_SUBJECT="SUCCESS: Botium Test Session ${BOTIUM_PROJECT_CODE}"
        echo "Botium Test Session ${BOTIUM_PROJECT_CODE} OK" >> ${TEMP_DIR}/${BOTIUM_PROJECT_CODE}.txt
else
        MAIL_SUBJECT="FAILED: Botium Test Session ${BOTIUM_PROJECT_CODE}"
        echo "Botium Test Session ${BOTIUM_PROJECT_CODE} FAILED" >> ${TEMP_DIR}/${BOTIUM_PROJECT_CODE}.txt
fi
echo "Download CSV Result: ${URL_CSV}" >> ${TEMP_DIR}/${BOTIUM_PROJECT_CODE}.txt

cat ${TEMP_DIR}/${BOTIUM_BUILD_ID}.txt | ./mailer-v1.6-linux-x86_64 \
  --host <smtp host> \
  --user <smtp user> \
  --pass <smtp password> \
  --from <mail sender> \
  --to <mail receiver> \
  --subject "${MAIL_SUBJECT}" \
  --file ${TEMP_DIR}/${BOTIUM_BUILD_ID}.pdf

echo Email sent.

rm -f ${TEMP_DIR}/${BOTIUM_BUILD_ID}.txt
rm -f ${TEMP_DIR}/${BOTIUM_BUILD_ID}.pdf


When I run the script, I am getting some of the previous results(older) along with the latest result.

Do you have any idea?

**Comment by codeforequity-at** [comment]
What do you mean with "getting some of the previous results" ? Do you receive multiple reports ? Or do the test reports contain data which should not be part of the current test run ?

**Comment by Aishwarya-J-S** [comment]
The test reports contain data which should not be part of the current test run as follows

Botium Test Session SampleTestProject OK
Download CSV Result: http://host:port/api/build/BUILD_20190805134310?APIKEY=XXXXXX&REPORTER=csv
Botium Test Session SampleTestProject OK
Download CSV Result: http://host:port/api/build/BUILD_20190805232008?APIKEY=XXXXXX&REPORTER=csv
Botium Test Session SampleTestProject OK
**Download CSV Result: http://host:port/api/build/BUILD_20190806232012?APIKEY=XXXXXX&REPORTER=csv**


This is the body of the mail which I am getting, where I get the current test run result in pdf but has multiple reports of csv containing data which should not be part of the current test run

The highlighted one is the current test run result

**Comment by codeforequity-at** [comment]
You should write the mail text to send into the file ${TEMP_DIR}/${BOTIUM_BUILD_ID}.txt instead of 
${TEMP_DIR}/${BOTIUM_PROJECT_CODE}.txt, so that it contains the text for the current build only (or you remove the file ${TEMP_DIR}/${BOTIUM_PROJECT_CODE}.txt on starting the script.

**Comment by Aishwarya-J-S** [comment]
Thank you. I added the project code so that i can get the project details in the mail.
