### ISSUE TITLE
Allow context info to be used in utterances sent to Watson Assistant

### ISSUE THREAD

**Issue by troyibm** [codeforequity-at/botium-core#349]
**Is your feature request related to a problem? Please describe.**
Info is sent into the request to Watson Assistant via context.  We need this to be able to test different scenarios involving different front-end clients that send text and data to our assistant.

**Describe the solution you'd like**
Allow a bit of JSON to be provided in convo text files that will be added to the "context" object of the request.  Like...
```
#me
i need something
{ "blahkey": "blahvalue", "blahobj" : { "blahblahkey" : 2 }}

#bot 
here is your answer
```

**Describe alternatives you've considered**
https://github.com/codeforequity-at/botium-core/issues/62 provides an alternative, but that's a work around.  This issue is for context to be fully featured in botium.

**Additional context**
I'm inclined to supply a PR with this functionality.  I just don't know where to do it.  I'd want it for botium-cli.

**Comment by codeforequity-at** [comment]
we are actually working on this right now

**Comment by troyibm** [comment]
I'm willing to test anything out when ready.
Is there another github issue that tracks this work?

**Comment by codeforequity-at** [comment]
We currently don't use Github issue tracker to organize our work, it's too far away from what we need in agile development.

**Comment by codeforequity-at** [comment]
@troyibm Botium Box 1.7.5 is out, with this feature enabled
https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/20807681/Botium+Box+Release+Notes

**Comment by troyibm** [comment]
Will check it out.. thanks
