### ISSUE TITLE
How can I test the asynchronous responses from the third party integration in the latest EE botium box

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#350]
How can the Asynchronous responses (Callback messages) from the third party API be tested in the latest EE Botium Box 1.7.3 through the Chatbot Technology Generic HTTP/JSON

**Comment by codeforequity-at** [comment]
The Generic HTTP/JSON connector is only working for synchronous messaging.

You have a chatbot API which asynchronously makes HTTP/JSON requests to a callback endpoint ?

**Comment by Aishwarya-J-S** [comment]
Chat bot will call the API of external systems which would make asynchronous call to Chat Bot API

For example:

While sending a request to an API for a solution like system related issues, We will receive notifications from that API on the status/Progress of the issue asynchronously.

**Comment by codeforequity-at** [comment]
Currently Botium doesn't support inbound endpoints. The scenario you are describing seems like an implementation detail very special to the chatbot you are developing. Very likely you will need a custom connector for this case.

**Comment by codeforequity-at** [comment]
We scheduled support for inbound endpoint in the Generic HTTP/JSON connector for the october release.

**Comment by Sid962** [comment]
Can asynchronous responses be tested with the Wipro Holmes Connector?

**Comment by codeforequity-at** [comment]
A generic HTTP/JSON inbound connctor is part of Botium Box 2.0 - see https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/24510469/Generic+HTTP+S+JSON+Connector#Capabilities-for-Async-Mode

If you could tell me more how this should work, I can propose a configuration.
