### ISSUE TITLE
Test Session Job doesn't have any logs in every test session

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#352]
After every test session, in the test session jobs there is no log recorded

![image](https://user-images.githubusercontent.com/49233293/63022135-dc908300-bebf-11e9-8f10-821635883700.png)

It just shows the following data for all the jobs

2019-08-14T09:13:28.921Z: Job queued for execution
2019-08-14T09:13:38.759Z: Job completed

**Comment by codeforequity-at** [comment]
https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/29360129/Enable+Diagnostics+and+Inspect+Logs#Inspect-Logs-from-Botium-Agents

**Comment by Aishwarya-J-S** [comment]
Thanks. It worked
