### ISSUE TITLE
Humanification is not working when the utterance file is not in the same test set but added as an dependency

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#353]
I have created a test set[**Testset1**] which has all the utterance file. For **Testset2**(All convo files are added), I have added the Testset1 as a dependecy file.

![image](https://user-images.githubusercontent.com/49233293/63022548-ca631480-bec0-11e9-9a34-82a2ff40c244.png)

When I cloned the **Testset2** for adding the Humanfication layer, it is not adding the humanification algorithm in the dependency utterance file

Is it the requirement that the utterance file should be available in the same test set for the Humanification to work?

**Comment by codeforequity-at** [comment]
it would be hard to manage otherwise - dependencies are copied, but humanification only applies to current test set. added to backlog to optionally humanify dependencies as well.
