### ISSUE TITLE
How can GDPR be tested in the EE Edition?

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#355]
How can GDPR be tested in the EE Edition? Is there any documentation available to explore more on this feature in Botium.

**Comment by grisuBotium** [comment]
GDPR testing is available in the Ultimate Edition only. Please check the Botium wiki: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360471/Botium+Platform
