### ISSUE TITLE
Unable to do security testing in the Botium EE Edition 1.7.3

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#356]
In the EE Edition, by default ZAProxy configurations is added in the docker-compose files.

I have started the testing after enabling the security check button in the Test Project.

But I am not getting any updates in the Security Scan Page.

Is there anything else to be configured to run this?

**Comment by stefan-sev** [comment]
I just linked to this repo because it is not related to botium-core. I will try to help you there
