### ISSUE TITLE
issues installing Botium community version

### ISSUE THREAD

**Issue by sangurocactus** [codeforequity-at/botium-core#358]
Hello, 

I want to download the Botium community version by following the quick install guide here: https://www.npmjs.com/package/botium-box
I was able to download the `docker-compose-all.yml` file but received an error message `ERROR: In file './docker-compose-all.yml', the service name 404 must be a quoted string, i.e. '404'.` when I tried to run the second commands `docker-compose -f docker-compose-all.yml up -d`. What am I doing wrong? 

Thank you for your help.

**Comment by codeforequity-at** [comment]
NPM installation is deprecated and not supported anymore (since two days). Only supported way is to run Botium Box with Docker. Please see https://github.com/codeforequity-at/botium-box-basic-dist
