### ISSUE TITLE
Loading Botium plugin failed

### ISSUE THREAD

**Issue by zanstro** [codeforequity-at/botium-core#359]
**Describe the bug**
I have a fresh installation of Botium Core 1.5.3 with Dialogflow Connector 0.0.9. I use the Botium API following the swagger definition you provide. Although the endpoint /api/status is working, /api/build gives me the error "Loading Botium plugin failed". I tried to downgrade Dialogflow Connector to version 0.0.8 but the problem remained. However, when I downgraded to version 0.0.7 the problem solved and I was able to run the test script.

**To Reproduce**
- Clone botium-core (1.5.3)
- Run npm install
- Run npm install botium-connector-dialogflow
- Run npm run agent

**Botium Version**
 - botium-core 1.5.3
 - botium-connector-dialogflow 0.0.9 or 0.0.8

**Comment by codeforequity-at** [comment]
Can you please enable debug mode (export DEBUG=botium*) and attach the logfile here, thanks

**Comment by zanstro** [comment]
Logfile attached, I just removed the Dialogflow private key. Thank you

[logfile.txt](https://github.com/codeforequity-at/botium-core/files/3519458/logfile.txt)

**Comment by codeforequity-at** [comment]
You should use botium-cli (https://github.com/codeforequity-at/botium-cli) to run Botium in agent mode, not botium-core directly.

**Comment by zanstro** [comment]
I am not quite sure I understand. Do you mean that Botium HTTP API is not supported in the new version of botium-core and/or botium-connector-dialogflow?

Is there any way to use Botium Agent through the Botium HTTP API as described here? https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/491671/Botium+Grid

This is something that used to work and as I already mentioned downgrading to a previous botium-connector-dialogflow solves the problem.

**Comment by codeforequity-at** [comment]
botium-core is just a library. Please use Botium-CLI to run it from the command line. I added this hint to the Wiki page now. 

There may be a reason why you want to use it from botium-core library (the only one I can mention is that you are a developer and are working on new botium-core features), but for this to work you will have to register global npm links for botium-core.

For Botium users, Botium CLI is the way to go.
