### ISSUE TITLE
 Error: Cannot build docker containers: 'Cannot build docker containers: 

### ISSUE THREAD

**Issue by stephenws** [codeforequity-at/botium-core#36]
Hi I am new in Botium

I am running sample project

const BotDriver = require('botium-core').BotDriver
const Capabilities = require('botium-core').Capabilities
const Source = require('botium-core').Source

function assert (expected, actual) {
  if (!actual || actual.indexOf(expected) < 0) {
    console.log(`ERROR: Expected <${expected}>, got <${actual}>`)
  } else {
    console.log(`SUCCESS: Got Expected <${expected}>`)
  }
}
const driver = new BotDriver()
  .setCapability(Capabilities.PROJECTNAME, 'Testmybot Sample Calculator')
  .setCapability(Capabilities.FACEBOOK_API, true)
  .setCapability(Capabilities.FACEBOOK_WEBHOOK_PORT, 3000)
  .setCapability(Capabilities.FACEBOOK_WEBHOOK_PATH, 'facebook/receive')
  .setCapability(Capabilities.FACEBOOK_SEND_DELIVERY_CONFIRMATION, false)
  .setCapability(Capabilities.CLEANUPTEMPDIR, false)
  .setSource(Source.GITURL, 'https://github.com/codeforequity-at/testmybot-sample-calculator.git')
  .setSource(Source.GITPREPARECMD, 'npm install')
  .setCapability(Capabilities.STARTCMD, 'node index.js')
  .setEnv('NODE_TLS_REJECT_UNAUTHORIZED', 0)
  .setEnv('NODE_ENV', 'dev')
  .setEnv('page_token', 'sample')
  .setEnv('verify_token', 'sample')

driver.BuildFluent()
  .Start()
  .UserSaysText('start')
  .WaitBotSaysText((text) => assert('I can do a very advanced scientific calculations for you ("Addition").', text))
  .WaitBotSaysText((text) => assert('Please tell me the first number!', text))
  .UserSaysText('1')
  .WaitBotSaysText((text) => assert('Please tell me the second number!', text))
  .UserSaysText('1')
  .WaitBotSaysText((text) => assert('1 + 1 = 2', text))
  .WaitBotSaysText((text) => assert('Is this correct ?', text))
  .UserSaysText('yes')
  .WaitBotSaysText((text) => assert('I know.', text))
  .Stop()
  .Clean()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })

When In run using command prompt through :node botiumFluent.js
I Got below Error 

ERROR:  Error: Cannot build docker containers: 'Cannot build docker containers: Error: docker-compose failed: { Error: spawn docker-compose ENOENT\n    at exports._errnoException (util.js:1018:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)\n    at onErrorNT (internal/child_process.js:367:16)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)\n  code: \'ENOENT\',\n  errno: \'ENOENT\',\n  syscall: \'spawn docker-compose\',\n  path: \'docker-compose\',\n  spawnargs: \n   [ \'-p\',\n     \'Testmybot-Sample-Calculator\',\n     \'-f\',\n     \'/Users/Mukesh/botium/botiumwork/Testmybot-Sample-Calculator-20180410-193501-PTf3w/docker-compose.botium.yml\',\n     \'-f\',\n     \'/Users/Mukesh/botium/botiumwork/Testmybot-Sample-Calculator-20180410-193501-PTf3w/fbmock/docker-compose.fbmock.yml\',\n     \'-f\',\n     \'/Users/Mukesh/botium/botiumwork/Testmybot-Sample-Calculator-20180410-193501-PTf3w/docker-env.yml\',\n     \'build\' ] }\n    at ChildProcess.<anonymous> (/Users/Mukesh/botium/node_modules/botium-core/dist/botium-cjs.js:1338:18)\n    at emitOne (events.js:96:13)\n    at ChildProcess.emit (events.js:188:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)\n    at onErrorNT (internal/child_process.js:367:16)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickCallback (internal/process/next_tick.js:104:9)'
    at /Users/Mukesh/botium/node_modules/botium-core/dist/botium-cjs.js:2867:25
    at /Users/Mukesh/botium/node_modules/async/dist/async.js:3874:9
    at /Users/Mukesh/botium/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/Users/Mukesh/botium/node_modules/async/dist/async.js:976:17)
    at /Users/Mukesh/botium/node_modules/async/dist/async.js:958:16
    at /Users/Mukesh/botium/node_modules/async/dist/async.js:3871:13
    at /Users/Mukesh/botium/node_modules/botium-core/dist/botium-cjs.js:2861:15
    at process._tickCallback (internal/process/next_tick.js:109:7)

does Docker required to run Botium?

**Comment by codeforequity-at** [comment]
It depends what you are doing with Botium if Docker is required. This sample requires docker, right.

https://github.com/codeforequity-at/botium-core/wiki/Botium-Configuration#capabilities-for-operation-mode-docker
