### ISSUE TITLE
Scripting Memory.

### ISSUE THREAD

**Issue by sapinedamo** [codeforequity-at/botium-core#360]
Hi.

How to setup the variables in Botium Box? For example, We have the following convo file:
![Captura](https://user-images.githubusercontent.com/36140138/63379870-d6385600-c35a-11e9-9efb-baf2af9b5322.PNG)
Where BOT_CONTACT_YES is 
![Captura1](https://user-images.githubusercontent.com/36140138/63380047-4941cc80-c35b-11e9-91c4-42d541bcb792.PNG)
We need to setup values for the variable $month. To achieve this we have tried the following:

1. We have the file month.txt

![Captura2](https://user-images.githubusercontent.com/36140138/63380301-d553f400-c35b-11e9-9acf-ed87ec3be7aa.PNG)

2. On Botium Box we have the following configuration
![Captura3](https://user-images.githubusercontent.com/36140138/63380592-8195da80-c35c-11e9-8604-1c7cf51f46fc.PNG)
![Captura4](https://user-images.githubusercontent.com/36140138/63380597-85296180-c35c-11e9-8d09-d162b3cf4005.PNG)

Best regards,

Santiago.

**Comment by codeforequity-at** [comment]
Using scripting memory files makes only sense for values used in the #me sections, not in the #bot sections. I think what you want is to switch the Text Matching Mode to regular expressions and write your BOT_CONTACT_YES utterances as regular expression to match all valid texts.

**Comment by sapinedamo** [comment]
Yes, because we get the error:
![Captura5](https://user-images.githubusercontent.com/36140138/63449392-a98d4880-c405-11e9-9081-018dcf00a016.PNG)
Any idea how to fix the error?

**Comment by codeforequity-at** [comment]
$product is not a regular expression. You should change it to \w+ to make the regular expression matcher working

**Comment by codeforequity-at** [comment]
success ?

**Comment by codeforequity-at** [comment]
Please re-open if new data available.

**Comment by sapinedamo** [comment]
Hi! 

Sorry, I have solved the problem in another way.

Thanks!
