### ISSUE TITLE
bot message step getting failed though having expected and actual value are same due to scripting memory

### ISSUE THREAD

**Issue by radhabasida** [codeforequity-at/botium-core#363]
**Describe the bug**
In my botium script, I have bot message like below and I have specified in script file as below
#bot 
Here's the breakdown of your salary:
▪ Basics - $5,750.00
▪ House Rent Allowance - $650.00
▪ Professional Tax - $1,120.00
▪ Provident Fund - $2,000.00
▪ Net Salary Payable - $6,520.00

But while executing test script, test case gets failed, due to below error
TranscriptError: BotiumError: employee salary conversation flow/Line 98: Expected bot response (on Line 95: #me - Salary Structure BUTTON(Salary Structure)) "Here's the breakdown of your salary: ▪ **Basics - $5,750.00 ▪ House Rent Allowance - $650.00** ▪ Professional Tax - $1,120.00 ▪ Provident Fund - $2,000.00 ▪ Net Salary Payable - $6,520.00" to match one of "Here's the breakdown of your salary: ▪ **Basics - $650,750.00 ▪ House Rent Allowance - $5.00** ▪ Professional Tax - $1,120.00 ▪ Provident Fund - $2,000.00 ▪ Net Salary Payable - $6,520.00"

**To Reproduce**
Steps to reproduce the behaviour.

**Expected behaviour**

**Screenshots and Log files**
[verbose log](https://github.com/codeforequity-at/botium-core/files/3545082/verbose.log)

**Botium Flavour:**
 - Botium Bindings 

I think problem is due to scripting memory. Could you please check

**Comment by ujja** [comment]
Yes, thats right. I create a ticket for it in our backlog.

**Comment by ujja** [comment]
Could you send your capabilities please? (botium.json)

**Comment by radhabasida** [comment]
I have done some customisation by adding custom asserters and inputs. Here sending botium.json file having core capabilities of botium

[botium.txt](https://github.com/codeforequity-at/botium-core/files/3549201/botium.txt)

**Comment by codeforequity-at** [comment]
The reason for this problem is that all the currency dollar signs are intermixing with the scripting memory placeholders. We will have to introduce an escaping mechanism.

**Comment by radhabasida** [comment]
We can have variable name starting with '_' character as there are very rare changes that bot contains any words starting with '_' character in bot message.

**Comment by codeforequity-at** [comment]
The bugfix is to only allow scripting variable names starting with a letter

**Comment by codeforequity-at** [comment]
fixed with latest build
