### ISSUE TITLE
allow for a single convo file as parameter to botium-cli

### ISSUE THREAD

**Issue by troyibm** [codeforequity-at/botium-core#372]
**Is your feature request related to a problem? Please describe.**
Sometimes you just want to run a single test and to do that you have to copy the file to an empty directory.  Please allow for `botium-cli --convos somefile.convo.txt`

**Describe the solution you'd like**
I hope the two sentences I wrote above covers it.

**Describe alternatives you've considered**
make an empty directory, copy test file to it, then use the directory as the --convos value

**Comment by codeforequity-at** [comment]
heard this several times now. I added it to our backlog, it will be covered in the upcoming sprint.

**Comment by codeforequity-at** [comment]
Already fixed some weeks ago.
