### ISSUE TITLE
How can I add NLP Asserter in the Generic HTTP/JSON Chatbot Technology

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#376]
How can I test the NLP Asserter in the Generic HTTP/JSON Chatbot Technology. Can this chatbot technology exposes the asserter information to Botium through its capability?

**Comment by codeforequity-at** [comment]
If your endpoint exposes this information as part of the JSON response, you can use a response hook with your own code snippet to extract the NLP information:

https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/24510469/Generic+HTTP+S+JSON+Connector#SIMPLEREST_RESPONSE_HOOK

**Comment by codeforequity-at** [comment]
any success here ?

**Comment by codeforequity-at** [comment]
The Botium Wiki page linked above includes a sample for how to extract the NLP intent from the HTTP/JSON response - this is a small javascript snippet in the SIMPLEREST_RESPONSE_HOOK capability:

    ...
    "SIMPLEREST_RESPONSE_HOOK": "botMsg.nlp = {intent: {name: botMsg.sourceData.intent}};"
    ...

Now that the NLP intent is part of the Botium internal message representation, the [Botium NLP asserters](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/17334319/NLP+Asserter+Intents+Entities+Confidence) can be used - like this in a convo file:

    #me
    say something

    #bot
    INTENT expectedintent
