### ISSUE TITLE
Call an asserter from another asserter

### ISSUE THREAD

**Issue by xmichele** [codeforequity-at/botium-core#378]
Hello,

is there a way to call an asserter from another asserter? In my case I would like to call botium-asserter-basiclink only if I don't find a "filterString" in the chatbot text otherwise return true. Maybe there is already something dealing with "assertConvoStep" . 
Sorry for my very basic javaScript understanding

Thanks

**Comment by codeforequity-at** [comment]
No reason why not. Just instantiate the other asserter (with same args as yours), and call the assertConvoStep function, again with the same args as yours ...

**Comment by xmichele** [comment]
I started with a new basic asserter but " Failed to fetch CUST_ASS asserter, no idea how to load  " Adding under Capabilities in botium.json
   "ASSERTERS": [
{
"ref": "CUST_ASS",
"src": "/app/custAsserter.js"
}
]
--
So tried to call with CUST_ASS myText in #bot section . I have already created in /app/custAsserter.js:
 
const _ = require('lodash')
const { BotiumError } = require('botium-core')
//const { BotiumError } = require('../../BotiumError')
///usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/BotiumError.js

module.exports = class custAsserter {
  constructor (context, caps = {}) {
    this.context = context
    this.caps = caps
  }

  assertConvoStep ({ convo, convoStep, args, botMsg }) {
    if (!args || args.length < 1) {
      return Promise.reject(new BotiumError(`${convoStep.stepTag}: custAsserter Missing argument`,
        {
          type: 'asserter',
          subtype: 'wrong parameters',
          source: 'custAsserter',
          cause: { args }
        }
      ))
    }
 ////botMsg.messageText botMsg.buttons ||  _.isString(shallContained)
    if (args.length >= 1) {
		if(botMsg.messageText.includes("Do you find any of the options") && !botMsg.messageText.includes(args[0]))
      return Promise.reject(new BotiumError(`${convoStep.stepTag}: custAsserter Alternative Button not found "${args}"`,
        {
          type: 'asserter',
          subtype: 'wrong parameters',
          source: 'custAsserter',
          cause: { args }
        }
      ))
    }

    return Promise.resolve()
  } //END assertConvoStep
}

----------
Error:
Failed to fetch CUST_ASS asserter, no idea how to load ...
    at LogicHookUtils._loadClass (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/logichook/LogicHookUtils.js:263:11)
    at caps.(anonymous function).map.asserter (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/logichook/LogicHookUtils.js:96:45)
    at Array.map (<anonymous>)
    at LogicHookUtils._fetchAsserters (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/logichook/LogicHookUtils.js:92:8)
    at new LogicHookUtils (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/logichook/LogicHookUtils.js:63:10)
    at ScriptingProvider.Build (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:259:28)
    at BotDriver.BuildCompiler (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/BotDriver.js:164:16)
    at handler (/usr/local/lib/node_modules/botium-cli/src/run/index.js:79:27)
    at Object.builder.handler (/usr/local/lib/node_modules/botium-cli/bin/botium-cli.js:34:7)
    at Object.runCommand (/usr/local/lib/node_modules/botium-cli/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/botium-cli/node_modules/yargs/yargs.js:1078:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/botium-cli/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/botium-cli/bin/botium-cli.js:74:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)

**Comment by codeforequity-at** [comment]
Pls enable debug mode, should get more details then

**Comment by xmichele** [comment]
In debug mode the problem show is code: 'MODULE_NOT_FOUND' related to const { BotiumError } = require('botium-core')

**Comment by codeforequity-at** [comment]
Can you try to install botium-core into the global npm cache (npm install -g botium-core)

**Comment by xmichele** [comment]
Still error also after explicit global install

root@567ac8c17f9a:/app# npm list -g | grep botium
+-- botium-cli@0.0.55
| +-- botium-asserter-basiclink@0.0.6
| +-- botium-connector-alexa-avs@0.0.6
| +-- botium-connector-alexa-smapi@0.0.7
| +-- botium-connector-botkit@0.0.4
| +-- botium-connector-botkit-websocket@0.1.1
| +-- botium-connector-botpress@0.0.4
| +-- botium-connector-dialogflow@0.0.9
| +-- botium-connector-directline3@0.0.14
| +-- UNMET PEER DEPENDENCY botium-connector-echo@0.0.4
| +-- botium-connector-fbpagereceiver@0.0.2
| +-- botium-connector-google-assistant@0.0.3
| +-- botium-connector-koreai-webhook@0.0.2
| +-- botium-connector-lex@0.0.2
| +-- botium-connector-luis@0.0.1
| +-- botium-connector-rasa@0.0.1
| +-- botium-connector-sapcai@0.0.1
| +-- botium-connector-watson@0.0.9
| +-- botium-connector-webdriverio@0.1.3
| +-- botium-connector-wechat@0.0.1
| +-- botium-core@1.5.4
npm ERR! peer dep missing: botium-connector-echo@^0.0.1, required by botium-connector-dialogflow@0.0.9
+-- botium-connector-webdriverio@0.1.3
+-- botium-core@1.5.4

**Comment by codeforequity-at** [comment]
ok I will try to reproduce this on a new machine

**Comment by codeforequity-at** [comment]
one thing you can try: in /app, run "npm init -y" and "npm install botium-core" to install botium-core locally to your asserter

**Comment by xmichele** [comment]
with npm init -y" and "npm install botium-core seems to work. 
So calling in my custom asserter the button asserter how can be made?

**Comment by codeforequity-at** [comment]
something like this:

    const ButtonsAsserter = require('botium-core/src/scripting/logichook/asserter/ButtonsAsserter')
    ....
    constructor (context, caps = {}) {
        this.context = context
        this.caps = caps
        this.defaultButtonsAsserter = new ButtonsAsserter(context, caps)
    }
    ...
    ...
    assertConvoStep ({ convo, convoStep, args, botMsg }) {
        ....
        return this.defaultButtonsAsserter.assertConvoStep({convo, convoStep, args, botMsg})

**Comment by xmichele** [comment]
It's ok, thanks : )
