### ISSUE TITLE
Adding place holders to a part of the string 

### ISSUE THREAD

**Issue by Sid962** [codeforequity-at/botium-core#381]
Can I know how can I add place holders to a part of a string? Because there is a possibility for the portion of that string to change in each test case. So it is not possible to keep place holders to each word.

**Comment by codeforequity-at** [comment]
an example please

Sid962 <notifications@github.com> schrieb am Mo., 23. Sep. 2019, 14:46:

**Comment by Sid962** [comment]
Currently we have a table in which there are many values that keeps changing in each test case. In a particular column the value has more than one word. How can I keep place holders to that column that have more than one word?

**Comment by codeforequity-at** [comment]
Still not getting it. Can you please post a concrete example what your plan is.

**Comment by Sid962** [comment]
![image](https://user-images.githubusercontent.com/55440140/65744363-c52af380-e115-11e9-88a1-04101fec4831.png)


Suppose this is the bot response and the "Name" column generates random names like shown above, how can i keep place holders to the values in the "Name" column?

**Comment by Sid962** [comment]
![image](https://user-images.githubusercontent.com/55440140/65744503-2783f400-e116-11e9-96c3-5c078e73c87c.png)

Suppose this is the bot response and the "Name" column generates random names like shown above. How can I keep place holder in the "Name" column ?

**Comment by codeforequity-at** [comment]
you mean, the chatbot responds with a table structure, as html ?

**Comment by Sid962** [comment]
yes it is

**Comment by codeforequity-at** [comment]
By default, before doing any matching, Botium will apply some _normalization_ to the returned text, to make it easier to compose the matching rules. Read about it here:

https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/60817419/What+are+the+Advanced+Scripting+Settings+in+Botium+Box

You could do a matching with regular expressions here, by setting the matching mode to "regexp". 

As we know that writing full-blown regular expressions is rather complicated, with Botium Box 1.8 we will introduce a matching mode "wildcard" where you can use an asterisk as placeholder, which is feasible for simple matching cases.

How to apply that in your special case, depends on how the HTML response actually looks like. I would guess that after doing the normalization, the text will be something like this:

    Sl.No Name Spend amount 1 Bryant Byun James 1000 2 Cortez Jamerson 1500 ...
 
A regular expression for matching this would be:

    Sl\.No Name Spend amount 1 .+ 1000 2 .+ 1500

**Comment by codeforequity-at** [comment]
With Botium 1.8, the "wildcard" matching mode is now available: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360603/Botium+Configuration+-+Capabilities#SCRIPTING_MATCHING_MODE

**Comment by Sid962** [comment]
Yes, problem solved, thank you :)
