### ISSUE TITLE
How can I create a user who cannot view the chatbots and test sets which is created by admin

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#382]
I am trying to create a user who cannot view or edit the chatbots/testsets created by admin.
How can I do that? 
I tried to give the tester/guest role to a new user but the user still able to view the test sets and chatbots created by the admin

**Comment by codeforequity-at** [comment]
The user roles are there for controlling the actions allowed for a user.
For restricting the visibility of records, Botium Box Ultimate supports multi tenancy

**Comment by Aishwarya-J-S** [comment]
Will it be coming in any of the upcoming Enterprise Edition.

**Comment by codeforequity-at** [comment]
It is already part of the Botium Box Ultimate Edition
