### ISSUE TITLE
Cannot display response in Dialogflow simulator. Please test on the Google Assistant simulator instead.

### ISSUE THREAD

**Issue by kshitij9969** [codeforequity-at/botium-core#385]
I am using dialog flow to create an agent. When I try to embed it in my website, it gives me following error, "Cannot display response in Dialogflow simulator. Please test on the Google Assistant simulator instead.". It works perfectly fine in Google Assistant Simulator. I have seen people embed in their websites, but I don't know what I did different.

Any help would be appreciated.

The expected output is a conversation between user and agent

**Comment by codeforequity-at** [comment]
This is not the right forum to ask dialogflow/google assistant questions, this is Botium.
