### ISSUE TITLE
how to use resular expression in botium box?

### ISSUE THREAD

**Issue by abhinav2019** [codeforequity-at/botium-core#387]
I want to use regular expression in my test script.

i followed the wiki and created the script.

**************************************
Script:
001

#bot default
Hi John Doe! I'm a abc Chatbot. I can help you with finding documents
BUTTONS Search Documents|HR Queries

#me
001_ME_1

#bot default
I found [0-9]+ documents matching your criteria.

********************************************

In Advanced Settings :

kept Text Matching mode as "Regular Expression"

I have used the regular expression in second response from bot and getting this error.

![error](https://user-images.githubusercontent.com/46926479/65673772-1204c080-e069-11e9-8f43-a1cc25189486.PNG)

**Comment by abhinav2019** [comment]
The Scenario is : 
today we have 1 document in this category.
tomorrow if the document are updated suppose 3 documents are there in that category
then our script will fail because we hard coded to 1.
i want to verify the text is coming "I found  XX documents matching your criteria."

XX today is 1
tomorrow is 2

In place of XX , can i use regular expression that verify the rest text and leave that XX

**Comment by codeforequity-at** [comment]
What version of Botium Box or Botium core are you using ? I am not able to reproduce on the latest version. Can you build a showcase`of this problem in our online trial box.botium.at ?

**Comment by abhinav2019** [comment]
Currently i am using Version : 1.7.4
Edition :  community
Sorry I cannot integrate the chatbot on trial version because of security reasons as it is open for all to use.

I am attaching the zipped file of my test Set and as well as attaching the step i followed to perform this scenario.
**Step 1 :**  Created botium.json and added a capability SCRIPTING_MATCHING_MODE and kept it as "regex" for using regular expression

**************************************************
Botium.json : 

{
  "botium": {
    "Capabilities": {
      "CONTAINERMODE": "directline3",
      "DIRECTLINE3_SECRET": "**************************************************",
      "DIRECTLINE3_WEBSOCKET": false,
      "DIRECTLINE3_POLLINGINTERVAL": 1000,
      "DIRECTLINE3_GENERATE_USERNAME": false,
      "DIRECTLINE3_BUTTON_TYPE": "message",
      "DIRECTLINE3_BUTTON_VALUE_FIELD": "text",
      "SCRIPTING_MATCHING_MODE": "regexp"
    },
    "Sources": {},
    "Envs": {}
  }
}

*************************************************


step 2: 

created this test script

*************************
001

#bot default
Hi John Doe! I'm a CMS Chatbot. I can help you with finding documents based on desired type and answer your policy related queries. Type **Help** for sample queries.
BUTTONS Search Documents|HR Queries

#me
001_ME_1

#bot default
I found [0-9]+ documents matching your criteria.


****************************
Currently in bot response , it coming "I found 1 documents matching your criteria."

I want to make it generic . I want to verify the text and not the count of documents  . i.e used [0-9]

******************************************

Step 3 👍 
In advanced setting of test set .

kept Text Matching mode as "Regular Expression"


Can you please help.

if i am doing something wrong over here.


getting this error : 

Error: 001/001_ME_1-L1/Line 3: error waiting for bot SyntaxError: Invalid regular expression: /Hi John Doe! I'm a CMS Chatbot. I can help you with finding documents based on desired type and answer your policy related queries. Type **Help** for sample queries./: Nothing to repeat at String.match (<anonymous>) at utterances.forEach.expected (/app/agent/node_modules/botium-core/src/scripting/ScriptingMemory.js:181:36) at Array.forEach (<anonymous>) at Object.fill (/app/agent/node_modules/botium-core/src/scripting/ScriptingMemory.js:172:16) at scriptingEvents.onBotStart.then.then (/app/agent/node_modules/botium-core/src/scripting/Convo.js:336:33)
[dummy_substring.zip](https://github.com/codeforequity-at/botium-core/files/3657529/dummy_substring.zip)

**Comment by codeforequity-at** [comment]
Ah, now I can see it.
When using the regexp-mode, all your asserters have to be valid regular expressions.

You have this in your convo file:
```
#bot default
Hi John Doe! I'm a CMS Chatbot. I can help you with finding documents based on desired type and answer your policy related queries. Type **Help** for sample queries.
```

This is not a valid regular expression, you have to quote the asterisks and the dots, if you expect the literal character:

```
#bot default
Hi John Doe! I'm a CMS Chatbot\. I can help you with finding documents based on desired type and answer your policy related queries\. Type \*\*Help\*\* for sample queries\.
```

You can use a tool like https://regex101.com/ to check your regular expressions.

As regular expressions can be rather complex, with the next Botium build, there will be a simplified regexp mode called **wildcard**, where you can just use **\*** as wildcard for everything - so this section:

```
#bot default
I found [0-9]+ documents matching your criteria.
```
will then look like this:
```
#bot default
I found * documents matching your criteria.
```

far more user friendly than to deal with regular expression syntax for simple cases.

**Comment by abhinav2019** [comment]
Hi ,

Thanks for the explanation of regexp-mode.
Now able to put regex for both numeric and alphabets . :)

Please notify when this new feature wildcard will come

**Comment by codeforequity-at** [comment]
Wildcard mode is default since Botium Box 1.8.
