### ISSUE TITLE
Unable to fetch the response from the chatbot

### ISSUE THREAD

**Issue by Sid962** [codeforequity-at/botium-core#390]
I have registered a chatbot and have added the capability "SIMPLEREST_RESPONSE_JSONPATH" and have provided the expression for fetching the response. But in some use cases, the required response is in different json expression and hence I am not getting the response for these cases(It is showing blank). Hence I added one more capability "SIMPLEREST_RESPONSE_JSONPATH1" and have added the new expression. But still I am not getting the response. The path expression is correct and I had verified it.  There is no error in the logs.

**Comment by codeforequity-at** [comment]
can you pls provide the jsonpath expressions (or the botium.json file) and a sample response

**Comment by codeforequity-at** [comment]
also, log file in DEBUG mode would help

**Comment by Sid962** [comment]
I had used the jsonpath expression on the botium code from the live chat to fetch the response. But when I applied the same with Postman, I am able to fetch the required response. Sorry, it was a mistake from my side. I am closing this issue.
