### ISSUE TITLE
Custom Logic Hooks broken with latest update

### ISSUE THREAD

**Issue by alopix** [codeforequity-at/botium-core#394]
**Describe the bug**
Not sure what exactly changed in the code base but since the last 1 or 2 updates custom logic hooks are broken.
Setting a new messageText on the convoStep does not work as before.

**To Reproduce**
See the attached project and `README.md` on how to test.
[custom_hooks_stop_working.zip](https://github.com/codeforequity-at/botium-core/files/3671631/custom_hooks_stop_working.zip)

**Expected behavior**
In `onMeStart` a simple `convoStep.messageText = 'message';` worked to just update what is being send to the bot. Now a combination of `meMsg.messageText = 'same message';` is necessary.

**Screenshots and Log files**
See example project.

**Botium Flavour:**
 - Botium Box -
 - Botium CLI -
 - Botium Bindings 2.0.17

**Botium Version**
1.5.4 - could be as early as 1.5.3

**Additional context**
-

**Comment by codeforequity-at** [comment]
It was actually not broken, but an incomplete bugfix.
The field to use for changing the conversation in the logic hooks is _meMsg_.
_convoStep_ holds the conversation step template, _meMsg_ the actual conversation step as sent to the Botium connector.

**Comment by codeforequity-at** [comment]
PR #395 on the way.

**Comment by alopix** [comment]
I would argue that the released version is broken if setting  meMsg.messageText alone does not work. But thanks for the hopefully soon released fix.

Some better way of communicating breaking changes would be really nice as well. :D 
This in addition to the change in `PAUSE` in the middle of a patch version update (which is in your wiki hidden far in the documentation but no changelog file).

**Comment by codeforequity-at** [comment]
critis accepted, we will start keeping a changelog
