### ISSUE TITLE
Botium box - test results 

### ISSUE THREAD

**Issue by nk009** [codeforequity-at/botium-core#398]
I am not getting any results after starting test (0 jobs running, 0 jobs failed).
I just started using Botium box, so I cannot guarantee that everything is setup correctly or If anything has been missed to be setup.

1, go to quickstart
2, select created chatbot
3, select test set
4, select device set
5, click on "Save and start testing"

On the attached screenshot you can see the results:

<img width="282" alt="Capture" src="https://user-images.githubusercontent.com/56115480/66121848-687c7c80-e5de-11e9-9290-3436af78e397.PNG">

id: "ck1al1m0600va0871avqdmvvb"

2019-10-03T10:51:47.220Z: Job queued for execution
2019-10-03T10:51:48.726Z: Job completed

2019-10-03T10:51:47.302Z: Job queued for execution
2019-10-03T10:51:50.113Z: Job completed

Below is a Botium version:

Build Target: basic
Build Branch: release/1.7.5
Build Revision: 2aedecaec6ded8bcb689ba8e4db67f7374467ffb
Build Date: 2019-09-06T19:59:48+02:00
Licensed Edition: community
License Validity: no restrictions
License Operability: no restrictions

**Comment by codeforequity-at** [comment]
What test set and what chatbot are you using ?

**Comment by nk009** [comment]
Do you need details, how is the Test set I am using, setup?

I am using a ChatBot where is necessary to click on a button to start a conversation. Which leads me to question, If Botium supports this possibility? Or If it is only for Chatbots with already opened conversation.

I attached a screenshot how I setup the Chatbot

<img width="359" alt="Capture" src="https://user-images.githubusercontent.com/56115480/66191955-bef5c380-e68f-11e9-9870-824da4ae8182.PNG">

**Comment by codeforequity-at** [comment]
Well, in theory, this is supported, but E2E Testing is the hardest way to start, as it requires at least writing Selenium selectors, and nearly everytime involves writing some Webdriver javascript code - you can read about it here: https://github.com/codeforequity-at/botium-connector-webdriverio

Typically, you start testing with Botium on API level and connect to the Chatbot backend to exchange messages.

Furthermore, I think your test set has some flaws, as Botium didn't recognize any test cases. [This repository](https://github.com/codeforequity-at/botium-box-samples) has a webdriver sample for Botium Box, please check if this is working for you.

**Comment by nk009** [comment]
hi all,

would anyone here be able to send me some examples what you are using here, see screenshot below

<img width="341" alt="Capture" src="https://user-images.githubusercontent.com/56115480/66566099-6711fd80-eb64-11e9-9fcd-a819906b1c10.PNG">

**Comment by nk009** [comment]
hi all,

would anyone here be able to send me some examples what you are using here, see screenshot below

<img width="341" alt="Capture" src="https://user-images.githubusercontent.com/56115480/66571766-21f3c880-eb70-11e9-977b-82313265c75d.PNG">


I am not sure If these elements are correctly insterted

**Comment by codeforequity-at** [comment]
it looks reasonable, but without knowing anything about structure of the DOM tree it is impossible to say if the selectors are correct.

Let me point you to a repository with some Botium samples: https://github.com/codeforequity-at/botium-box-samples 

There you can find some examples for the botium webdriver connector as well (using PhantomJS)

**Comment by codeforequity-at** [comment]
Please re-open if new data available.
