### ISSUE TITLE
Unable to edit the convo files in the "Shared Folder" in UI

### ISSUE THREAD

**Issue by Sid962** [codeforequity-at/botium-core#399]
I have shared a folder in botium consisting of more than 500 convo files. But if I want to edit the convo files in UI, I haven't seen such a provision there. Is there some other way to edit the convo files in UI?
![testcase](https://user-images.githubusercontent.com/55440140/66128921-777a2380-e60c-11e9-88a8-cebe27101cb7.png)

**Comment by codeforequity-at** [comment]
currently there is no way to edit the files within the botium box.
