### ISSUE TITLE
Unable to see the summary result and chart in the "Test Result" page

### ISSUE THREAD

**Issue by Sid962** [codeforequity-at/botium-core#400]
I have ran a test with 600+ convo files, but I am not able to obtain the summary result and chart in the "Test Results" page after the test is finished.
![testresult1](https://user-images.githubusercontent.com/55440140/66129454-90cf9f80-e60d-11e9-8fe9-41c07f6f184d.png)

**Comment by codeforequity-at** [comment]
hi, we have done tests with thousands of convo files without any trouble, so I think the size of your test set is not the problem. Can you see anything in the logs ? the test run started, but in between somewhen the job crashed.

**Comment by Sid962** [comment]
I am getting this error. 
![screenshot](https://user-images.githubusercontent.com/55440140/66200118-f713fb00-e6bd-11e9-8786-618be5a0eb22.png)
But I am able to obtain the pdf of the test result with all the details mentioned.

**Comment by codeforequity-at** [comment]
Please update to the latest Botium Box 1.8 version.
It was a known bug with the HTTP Hyperlink asserter that caused these kind of problems with the 1.7 versions.

**Comment by Sid962** [comment]
As we don't want to validate the hyperlinks present in the test sets, we have disabled the hyperlink asserter to run this test session.
