### ISSUE TITLE
Getting error while executing any botium-cli command.

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#403]
>botium-cli -Version

<code>
module.js:515
    throw err;
    ^

Error: Cannot find module 'unicode/category/So'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at symbols (..\AppData\Roaming\npm\node_modules\botium-cli\node_modules\slug\slug.js:6:16)
    at ..\AppData\Roaming\npm\node_modules\botium-cli\node_modules\slug\slug.js:204:5
    at Object.<anonymous> (..\AppData\Roaming\npm\node_modules\botium-cli\node_modules\slug\slug.js:217:2)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
</code.

**Comment by codeforequity-at** [comment]
can you please try to re-install botium-cli - remove directory ..\AppData\Roaming\npm\node_modules\botium-cli and install again.
It seems that a dependency of a dependency has not been installed correctly.
Or you can use the docker image for botium-cli

**Comment by DipaliK9** [comment]
I reinstalled botium-cli, still getting the same error. Can you please suggest any alternate solution.

**Comment by codeforequity-at** [comment]
maybe this helps:

> npm install -g unicode

**Comment by DipaliK9** [comment]
I tryied to install unicode and then I again installed botium-cli. I am still getting the same error.
Please see the log below when I install botium-cli and let me know if I am missing something

<code>
npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated joi@9.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated items@2.1.2: This module has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version of hapi to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> typechecker@2.0.8 preinstall ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\watchr\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\extendr\node_modules\typechecker
> node ./cyclic.js

..\AppData\Roaming\npm\botium-cli -> ..\AppData\Roaming\npm\node_modules\botium-cli\bin\botium-cli.js

> dtrace-provider@0.8.8 install ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\dtrace-provider
> node-gyp rebuild || node suppress-error.js


..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\dtrace-provider>if not defined npm_config_node_gyp (node "..\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "..\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.

> speaker@0.3.1 install ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker
> node-gyp rebuild


..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker>if not defined npm_config_node_gyp (node "..\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "..\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win32.c
  win_delay_load_hook.cc
  output.vcxproj -> ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\Release\\liboutput.lib
  binding.cc
  win_delay_load_hook.cc
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(80): warning C4996: 'Nan::Callback::Call': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan.h(1740): note: see declaration of 'Nan::Callback::Call'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(106): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(109): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(112): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(115): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(126): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(136): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(137): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(138): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(139): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(140): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(141): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(142): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(143): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(144): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\src\binding.cc(145): warning C4996: 'Nan::ForceSet': was declared deprecated [..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\binding.vcxproj]
  ..\....\.. chatbot\botium-connector-directline3\botium-cli\node_modules\nan\nan_maybe_43_inl.h(117): note: see declaration of 'Nan::ForceSet'
     Creating library ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\Release\binding.lib and object ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\Release\binding.exp
  Generating code
  Finished generating code
  binding.vcxproj -> ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\speaker\build\Release\\binding.node

> grpc@1.24.0 install ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\grpc\src\node\extension_binary\node-v57-win32-x64-unknown\grpc_node.node" is installed via remote

> websocket@1.0.30 install ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket>if not defined npm_config_node_gyp (node "..\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "..\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
     Creating library ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket\build\Release\bufferutil.lib and object ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket\build\Release\\bufferutil.node
  validation.cc
  win_delay_load_hook.cc
     Creating library ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket\build\Release\validation.lib and object ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket\build\Release\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\websocket\build\Release\\validation.node

> phantomjs-prebuilt@2.1.16 install ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\..~1.\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\..~1.\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1570609280064\phantomjs-2.1.1-windows -> ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at ..\....Chatbot\botium-connector-directline3\botium-cli\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> core-js@2.6.9 postinstall ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> protobufjs@6.8.8 postinstall ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\protobufjs
> node scripts/postinstall


> jsonpath@1.0.2 postinstall ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js


> core-js@3.2.1 postinstall ..\....\.. Chatbot\botium-connector-directline3\botium-cli\node_modules\z-schema\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

+ botium-cli@0.0.56
added 1143 packages from 1319 contributors in 779.775s

</code>

**Comment by codeforequity-at** [comment]
One last thing you can try is to clean your local NPM cache

    > npm cache clean

**Comment by DipaliK9** [comment]
I tried cache clean, still getting the same error, I am using Node 8.8. Is it compatible with latest version of Botium-cli. 
Please help resolving this issue.

**Comment by codeforequity-at** [comment]
The module causing this is the node-slug module. there are other users having the same problem: https://github.com/dodo/node-slug/issues/58, maybe one of the proposed solutions help.

**Comment by DipaliK9** [comment]
I installed Node 10 and then installed botium-cli. It worked for me. 
Thanks. :)

**Comment by codeforequity-at** [comment]
Good to know that upgrading Node helped in your case - may be useful for others as well.

**Comment by sspeterfernandez** [comment]
Hi @codeforequity-at , I am trying to connect to a bot service like chat gpt , that used a api over https, but I am getting 403/forbidden error may be my botium.json file is not configured properly is there any template to write botium.json file for apis, in the doc they use "SIMPLEREST_BODY_TEMPLATE" is it a template or should I use the exact same thing in my file as well? and one more thing I don't understand is how will the botium comunicate with a api that is streaming events will it establish a connection and send the prompts or will it send a https request each time?

**Comment by ujja** [comment]
It is nothing to do with the original ticket, and anyway it is closed. please open different ticket in those cases.

We use the following config for chatgpt:
```
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "ChatGPT",
      "CONTAINERMODE": "simplerest",
      "SIMPLEREST_URL": "https://api.openai.com/v1/chat/completions",
      "SIMPLEREST_METHOD": "POST",
      "SIMPLEREST_RESPONSE_JSONPATH": "$.choices[0].message.content",
      "SIMPLEREST_BODY_TEMPLATE": {
        "model": "gpt-4",
        "messages": [
          {
            "role": "user",
            "content": "{{msg.messageText}}"
          }
        ],
        "max_tokens": 100
      },
      "SIMPLEREST_HEADERS_TEMPLATE": {
        "Content-Type": "application/json",
        "Authorization": "Bearer sk-xxx"
      }
    },
    "Sources": {},
    "Envs": {}
  }
}
```
communication is connector specific. in case of simplerest connector we are making separate rest request via nodejs.fetch .
