### ISSUE TITLE
Send parameters to webhook on dialogflow via payload

### ISSUE THREAD

**Issue by SpyrosPac** [codeforequity-at/botium-core#406]
**Is your feature request related to a problem? Please describe.**
For my dialogflow fulfillment I pass some custom values which I retrieve through original detect intent request. Currently I cannot simulate this for my automation tests.

**Describe the solution you'd like**
I would like to simulate parameter addition through payload for automation tests. 

**Describe alternatives you've considered**
It can be done via queryParams.payload. https://cloud.google.com/dialogflow/docs/reference/rest/v2beta1/QueryParameters

More specifically, we could use the UPDATE_CUSTOM poweful featuew and pass a json object as payload

e.g. in dialogflow connector code -> index.js -> UserSays() :
```
if (msg.SET_DIALOGFLOW_PAYLOAD) {
  this.queryParams.payload = structjson.jsonToStructProto(msg.SET_DIALOGFLOW_PAYLOAD)
}
```

and use it like this

```
#me
hello
UPDATE_CUSTOM SET_DIALOGFLOW_PAYLOAD|{"data":"test"}
```

**Additional context**
Not relevant,but locally I trigger custom events through BUTTON. Botium is really great guys!

**Comment by codeforequity-at** [comment]
Good point. Added to backlog, will be part of the October build.

**Comment by codeforequity-at** [comment]
PR is on the way: https://github.com/codeforequity-at/botium-connector-dialogflow/pull/17

**Comment by codeforequity-at** [comment]
Part of the latest Botium build.
https://github.com/codeforequity-at/botium-connector-dialogflow#dialogflow-query-parameters
