### ISSUE TITLE
Retry on Asserter failure

### ISSUE THREAD

**Issue by Bibz87-CG** [codeforequity-at/botium-core#408]
**Is your feature request related to a problem? Please describe.**
We're having issues with our Dialogflow bot where some convo asserters might fail for different reasons, such as webhook timeouts or wrong expected intents. We've explored the RETRY options but found out they seemed to only validate failures on User Says and not on asserter validations.

**Describe the solution you'd like**
Is it possible to have a RETRY functionality for asserter failures?

**Describe alternatives you've considered**
The other option we have is to re-run the complete test package when a test fails but we'd prefer each convo to be able to retry by itself, as it would save on test time and resources.

**Additional context**
Not much else to add.

**Comment by codeforequity-at** [comment]
Makes sense. I added it to our backlog. October release is full, but scheduled for the November release.

**Comment by Bibz87-CG** [comment]
Any update on this issue's backlog status? Is it still scheduled for the November release?

Thanks!

**Comment by codeforequity-at** [comment]
yes

Bibz87-CG <notifications@github.com> schrieb am Mi., 13. Nov. 2019, 19:21:
