### ISSUE TITLE
Suggestion Chips / Link Out Suggestions Asserter

### ISSUE THREAD

**Issue by Bibz87-CG** [codeforequity-at/botium-core#409]
**Is your feature request related to a problem? Please describe.**
We haven't found a way to validate suggestion chips' presence in Google Assistant response without altering the Google Assistant connector.

**Describe the solution you'd like**
We'd like to validate if Google Assistant's response has the specified suggestion chips and/or link out suggestion.

**Describe alternatives you've considered**
Besides not validating suggestions at all, we don't really have alternatives.

**Additional context**
Nothing else to add.

**Comment by Bibz87-CG** [comment]
While investigating we were able to make our custom Suggestion asserter work by adding a `suggestions` property to the response queued by the Google Assistant connector but we're not 100% sure if that's the right way to do it.

Any suggestions on how to proceed?

**Comment by codeforequity-at** [comment]
The Google Assistant connector currently doesn't support anything else but plain text - it is in our backlog though. If you think you found a solution for your exact issue, we are happy to merge in any pull requests.

**Comment by Bibz87-CG** [comment]
Thanks, I'll send a pull request your when we'll have something solid.

**Comment by codeforequity-at** [comment]
Did you have any success yet on this ?

**Comment by Bibz87-CG** [comment]
We haven't been able to work a lot on this but I've created a [Pull Request](https://github.com/codeforequity-at/botium-connector-google-assistant/pull/3) with the related changes.

Once the connector exposes the required properties we'll then be able to make an asserter to check for suggestion chips / link out suggestions in botium-core.

**Comment by codeforequity-at** [comment]
As it is implemented now, it would allow to use the JSONPATH-asserter for doing this. 
But maybe it would be a good idea to map these suggestions to buttons - should be roughly the same as a quick link, I guess.
