### ISSUE TITLE
Unable to identify button click and card using directline 3

### ISSUE THREAD

**Issue by DipaliK9** [codeforequity-at/botium-core#410]
Hi,

I am using botium-cli version :0.0.56 and botium-directline3 version: 0.0.15. Still when I execute >botium-cli emulator browser
to save convo files, it does not identify button click.
On button click, it shows {"val":"ShowBalance"}. and does not give proper bot response.
Please help and let me know if I am using best connector for creating chatbot script using events like button click and form submit.

**Comment by codeforequity-at** [comment]
the emulators in botium cli are mainly for checking connectivity and dont support lots of interactive elements. there are no plans to amend it as well, botium box is the better choice to create chatbot scripts

**Comment by DipaliK9** [comment]
Thanks :)
I tried to use Botium box with directline3. However, It did not support form submit either. It behaves same as Botium-cli emulator browser.
Mybot shows card to select start date /enddate and submit. But when I was connected to botium box, I didnt get any option to select start and end date.

Am I missing anything?

**Comment by codeforequity-at** [comment]
No, you are not missing anything. Botium is not a form renderer, and it is currently not planned to extend this functionality. But anyway, you can use Directline3 Forms input in your BotiumScript files, you have to write the convo files yourself. There is a sample convo file available how to simulate form input: https://github.com/codeforequity-at/botium-connector-directline3/blob/master/samples/convo/spec/convo/form.convo.txt
