### ISSUE TITLE
Wipro Holmes Connector is not working as the payload validation fails

### ISSUE THREAD

**Issue by Aishwarya-J-S** [codeforequity-at/botium-core#414]
We are unable to connect with the Wipro Holmes Connector as the payload validation fails with the time stamp parameter as below

`ValueError: time data '16.10.2019, 05:17:57' does not match format '%Y-%m-%d %H:%M:%S' 
`

Wipro Holmes expects the time stamp to be in the format '%Y-%m-%d %H:%M:%S' but getting it as %d.%m.%Y, %H:%M:%S

**Comment by codeforequity-at** [comment]
Waiting for the development endpoint ...

**Comment by codeforequity-at** [comment]
Fixed with the latest changes in the connector.
