### ISSUE TITLE
Unable to see the test results from the pdf downloaded

### ISSUE THREAD

**Issue by Sid962** [codeforequity-at/botium-core#418]
Hi, I am now using the 1.8 version. After completing the testing, I have downloaded the test results as a pdf . But when I open the pdf report, I couldn't see any test reports, instead it is showing a link to go to the botium box. When I click on the link, it is showing error. I am currently facing a license issue, is it because of that I am facing the issue.

**Comment by codeforequity-at** [comment]
When license is not suitable for Botium Box 1.8, it will fall back to Community Edition, which doesn't include the detailed test reporting.
