### ISSUE TITLE
Botium emulator browser/console not able to capture button and cards from from fb

### ISSUE THREAD

**Issue by jawad360** [codeforequity-at/botium-core#42]
Hi,

I'm trying to use botium cli to record new conversations for my bot which replied back with fb buttons but emulator is not able to recognize this buttons.
In screenshots for botium-cli its shows that they are able recognize buttons and also in console screenshot shows a payload that is returned but for me its not coming.
![image](https://user-images.githubusercontent.com/12952209/38767340-f2efe9ee-3ffc-11e8-909d-a17b04f86512.png)

**Comment by codeforequity-at** [comment]
Currently, the emulators support text messages only (with some exceptions - picture attachments are shown, for example).
