### ISSUE TITLE
Use test case metadata as scripting variables

### ISSUE THREAD

**Issue by troyibm** [codeforequity-at/botium-core#431]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I want to be able to pull the entire conversation log from the NLP service (in this case Watson Assistant) when a test fails.  To do this, I was thinking if I could say to the bot "starting-test {test_name_at_top_of_test_file}" then I could look through the log soon after failure for that utterance and get the log of the conversation to help with debugging.  Is the test name at the top of the .convo.txt file in some env var that I could get and use in a me request?

**Describe alternatives you've considered**
instead of providing botium-cli a folder of test, tell it to do a single test and then I would know the file used and therefore the test name.  But this would make the tests longer to run, I suspect.

**Additional context**
None.

**Comment by codeforequity-at** [comment]
interesting ... could be a problem with watson assistant v2, api doesnt
support downloading the conversation log to ky knowledge. will look into
this.

Troy Dugger <notifications@github.com> schrieb am Mo., 11. Nov. 2019, 16:33:

**Comment by troyibm** [comment]
> interesting ... could be a problem with watson assistant v2, api doesnt support downloading the conversation log to ky knowledge. will look into this.

I don't need botium to download the log.  It is a v1 api btw.  I just need to put something in the log (through #me utterance) that indicates the test name so that if a test fails, we can pull the log and search through it for that test name.

**Comment by codeforequity-at** [comment]
Do you mean something like this ? A logic hook sending the test case name to stdout on each convo begin ?


```
{
  "botium": {
    "Capabilities": {
      ...
      "LOGIC_HOOKS": [
        {
          "ref": "MY-TESTCASE-LOGGER",
          "src": {
            "onConvoBegin": "console.log(convo.header.name)"
          },
          "global": true
        }
      ]
      ...
    }
  }
}
```

**Comment by troyibm** [comment]
> Do you mean something like this ? A logic hook sending the test case name to stdout on each convo begin ?

No, I need the test header name to go to the Watson Assistant log, so I was planning to have special intent that would handle an utterance like "starting-test TEST1", where TEST1 is the string that is in the first line of the convo.txt file (the header name as you call it).

so I need a variable (set by botium-cli) that I can use in the convo.txt file that will resolve the the convo header name so that it is sent to WA.

Example convo.txt file with this ability:

```
TEST1

#me
start-test {{convo.header.name}}

#bot
ok, proceed with test
```

**Comment by codeforequity-at** [comment]
I think I got it. This could work:

```
{
  "botium": {
    "Capabilities": {
      ...
      "LOGIC_HOOKS": [
        {
          "ref": "START-TEST",
          "src": {
            "onMeStart": "result = container.UserSaysText(convo.header.name)"
          },
          "global": true
        }
      ]
      ...
    }
  }
}
```

```
TEST1

#me
START-TEST

#bot
ok, proceed with test
```

Changing the issue title, as I consider this a workaround, and it is a good idea to add test case meta data to the scripting variable environment.

**Comment by troyibm** [comment]
as long as I can add something more to the #me line cause I need to have an intent for it.
so something like

```
TEST1

#me 
start-test TEST_HEADER_NAME
```
 and have this in the config

```
{
  "botium": {
    "Capabilities": {
      ...
      "LOGIC_HOOKS": [
        {
          "ref": "TEST_HEADER_NAME",
          "src": {
            "onMeStart": "result = container.UserSaysText(convo.header.name)"
          },
          "global": true
        }
      ]
      ...
    }
  }
}
```

all valid stuff??

**Comment by codeforequity-at** [comment]
You can use logic hook parameters as well, yes:

```
TEST1

#me 
SEND_HEADER_NAME some-awesome-parameter
```

So in this case, the text _TEST1/some-awesome-parameter_ would be sent to Watson.

```
{
  "botium": {
    "Capabilities": {
      ...
      "LOGIC_HOOKS": [
        {
          "ref": "`SEND_HEADER_NAME",
          "src": {
            "onMeStart": "result = container.UserSaysText(convo.header.name + '/' + args[0])"
          },
          "global": true
        }
      ]
      ...
    }
  }
}
```
