### ISSUE TITLE
Botium login issue - {type: "connection_error", payload: {message: "Missing auth token!"}}

### ISSUE THREAD

**Issue by tvsselva** [codeforequity-at/botium-core#440]
Please get a Botium Box Community Edition License by finishing registration! 

Getting this information and not getting the actual left pane menu in botium tool. Please help.

when click on login icon getting the below error in browser backend-Network>Messages in developer mode.

**{type: "connection_error", payload: {message: "Missing auth token!"}}**

![Botium_Login_Issue](https://user-images.githubusercontent.com/47594181/70713579-5b7db700-1d0c-11ea-9992-fc2c86c98da5.jpg)

**Comment by codeforequity-at** [comment]
click on the "finish registration" link to get your license key. see
installation instructions.

tvsselva <notifications@github.com> schrieb am Do., 12. Dez. 2019, 13:55:

**Comment by tvsselva** [comment]
This is an issue with installation as the installation not happened in the master folder.
after installing Botium it works fine.
