### ISSUE TITLE
HTTP headers and custom data added in Custom Asserters not cleaned up

### ISSUE THREAD

**Issue by piotrjak** [codeforequity-at/botium-core#443]
**Describe the bug**
I use Custom Asserter to add a header/custom data to an HTTP Request for some tests. I use `AssertConvoBegin` to attach it and `AssertConvoEnd` to remove it after the test. The problem is that if a test fails then `AssertConvoEnd` method isn't triggered and the header/data isn't removed - it is persistent in next convo tests and it makes them fail, because the handler method depends on the existence of this particular header/data.

**To Reproduce**
It's easier to show it.
![image](https://user-images.githubusercontent.com/45995385/71000563-d1eb3200-20db-11ea-82fe-2bc558b5fc7b.png)

**Expected behavior**
I expect the header/data to be removed even if the test fails. 
Maybe you have a different idea how to attach custom headers/data to some tests?  Only to some, I don't want them in all tests (I set the header Authorization in requestHook.js), but this is the only thing I want in all tests!

**Botium Flavour:**
 - Botium Box not used
 - Botium CLI not used
 - Botium Bindings 2.0.16

**Comment by piotrjak** [comment]
The problem is:
* requestHook executes after my custom asserter (LOCATION). I would be able to clean it using ` delete requestOptions.body.data` if it was the other way around (I could see if any the data or headers persisted from previous requests and delete them - then custom asserter would add only the correct one. If I did it now it would delete what I set in my customAsserter in # begin. 
* I can't get requestOptions in RESPONSE_HOOK. only the response data is there.

I just found a way to reproduce the scenario:
![image](https://user-images.githubusercontent.com/45995385/71009464-8d1ac780-20ea-11ea-8c81-80a2768e8e16.png)

I changed the message in convo file to the one that fails the test -> assertConvoStep doesn't execute, assertConvoEnd doesn't execute. the header/data set before in assertConvoBegin is persisted and available in next requests - I don't want that.

**Comment by piotrjak** [comment]
this is the only way I found to do this. first the header is attached, then the request is sent, then process.nextTick is executed and the request is still sent with the data I set.
![image](https://user-images.githubusercontent.com/45995385/71009923-5db88a80-20eb-11ea-8a2e-f067ff0a1895.png)

**Comment by codeforequity-at** [comment]
Hi, you invested quite some work in this issue, and you were on the right track.

First, you can use a logic hook (not an asserter) to attach a piece of information to the current session context of the HTTP connector:

    ....
    "LOGIC_HOOKS": [
        {
          "ref": "LOCATION",
          "src": {
            "onConvoBegin": "container.pluginInstance.view.location = { long: args[0], lat: args[1] }'"
          }
        }
      ]
    ....

The _view_ is used as Mustache view object in the HTTP connector, so you can now do something like this to manipulate the HTTP header - same for the body template:

    ...
    "SIMPLEREST_HEADERS_TEMPLATE": "{  {{#location}}\"X-HEADER-LOCATION\": \"{{long}}/{{lat}}\"{{/location}}  }",
    ...

Didn't try it, but it should work, if I made no typos ...

**Comment by piotrjak** [comment]
Hi!
Thanks for the response.
![image](https://user-images.githubusercontent.com/45995385/71092961-88b4e400-21a8-11ea-9976-241d2b32300a.png)
I tried using your solution, but it didn't work. is there a particular version of Botium that enabled Logic Hooks?
I also tried pointing the LogicHooks[0].src to a particular file like I did with Asserters e.g. "./botium/logichooks/latlong.js" and it didn't trigger this code. to be honest, I don't know what is the class structure (which particular methods it should have to work. I tried writing onConvoBegin method, but it wasn't executed.
![image](https://user-images.githubusercontent.com/45995385/71093232-198bbf80-21a9-11ea-89cc-f620127a1f89.png)

I can see an article for creating CUSTOM ASSERTERS https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/24477705/Developing+Custom+Asserters but I can't find one for creating CUSTOM LOGIC HOOKS. https://github.com/codeforequity-at/botium-core/tree/master/src/scripting/logichook/logichooks all have different class structures.
I would need something like this https://github.com/codeforequity-at/botium-core/blob/master/src/scripting/logichook/userinput/ButtonInput.js so I could set LOCATION long lat and it would add location field to meMsg. is it possible to do a custom one logic hook like that?

**Comment by codeforequity-at** [comment]
This one works for me. Don't know exactly what botium core version is required, but is part of botium core for a long time now. 

the classes you mentioned have different class structure because not every logic hook or asserter has to implement all hooks. user input is a good choice if you want to add this behaviour on a step-by-step base, but not when doing it in the _#begin_ section


botium.json:

```
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "experitest",
      "CONTAINERMODE": "simplerest",
      "SIMPLEREST_URL": "https://box.botium.at/iambotium/reply",
      "SIMPLEREST_METHOD": "POST",
      "SIMPLEREST_RESPONSE_JSONPATH": "$.reply",
      "SIMPLEREST_BODY_TEMPLATE": { "username": "botium", "message": "{{msg.messageText}}", "location": "{{location.long}}/{{location.lat}}"},
      "SIMPLEREST_HEADERS_TEMPLATE": "{ {{#location}}\"X-HEADER-LOCATION\": \"{{long}}/{{lat}}\"{{/location}} }",
      "LOGIC_HOOKS": [
        {
          "ref": "LATLONG",
          "src": {
            "onConvoBegin": "container.pluginInstance.view.location = { long: args[0], lat: args[1] }"
          }
        }
      ]
    },
    "Sources": {},
    "Envs": {}
  }
}
```
latlong.convo.txt:
```
latlong

#begin
LATLONG 1|2

#me
Hello, Bot!

#bot
```
log output:
```

2019-12-18T15:05:29.303Z botium-SimpleRestContainer constructed requestOptions {
"uri": "https://box.botium.at/iambotium/reply",
"method": "POST", 
"followAllRedirects": true,
"timeout": 10000,
"headers": { 
 "X-HEADER-LOCATION": "1/2"
},
"body": { 
 "username": "botium",
 "message": "Hello, Bot!",
 "location": "1/2"
},
"json": true
}
--
```

**Comment by piotrjak** [comment]
ah, ok. thanks for the snippet. I had LOGIC_HOOKS as a field under $.botium and not $.botium.capabilities. it works!
but now I would have to convert SIMPLEREST_BODY_TEMPLATE and SIMPLEREST_HEADERS_TEMPLATE values to strings and use moustache templating.

is it possible to put the { lat, long } object somewhere so I can add the location field in requestHook?
yes, there is. anything you add on container.pluginInstance.view object is added to an argument that is passed to requestHook function

![image](https://user-images.githubusercontent.com/45995385/71103396-590ed780-21ba-11ea-9958-4171c5416274.png)

**Comment by codeforequity-at** [comment]
so, this is solved for you ?
(added some items to the backlog to make such things easier in the future)

**Comment by piotrjak** [comment]
everything is solved. thanks for helping.
just one additional thing I changed.
using
`container.pluginInstance.view.context.location`
instead of 
`container.pluginInstance.view.location`
so I have all the additional fields added on the `context` object. a lil bit cleaner imo
```
module.exports = ({ requestOptions, context }) => {
  // set the authorization token for every request
  requestOptions.headers.Authorization = `Bearer ${process.env.TOKEN}`;

  if (context.location) {
    requestOptions.body.location = context.location;
  }
};
```
