### ISSUE TITLE
Unable to Assert a Media Card of Video Link in botium 

### ISSUE THREAD

**Issue by abhinav2019** [codeforequity-at/botium-core#445]
Hi ,

i am not able to assert video link in Botium
Bot is having a Video link inside it.
I am creating script using live chat but running it , it is getting failed

Version :  release/1.7.4
Licensed Edition: community
![assertion pic](https://user-images.githubusercontent.com/46926479/71352216-b086bc00-259b-11ea-97ed-42da54aa3100.PNG)
![testscriptpic](https://user-images.githubusercontent.com/46926479/71352229-bbd9e780-259b-11ea-9668-df7d679de433.PNG)

**Comment by abhinav2019** [comment]
![live chat](https://user-images.githubusercontent.com/46926479/71352969-afef2500-259d-11ea-8a32-771f0125cb63.PNG)

**Comment by abhinav2019** [comment]
Live chat It is showing blank message

**Comment by codeforequity-at** [comment]
oh, this was close ... this has been fixed with 1.7.5, the september release. You will have to upgrade your installation ...

**Comment by abhinav2019** [comment]
Hi @codeforequity-at ,

I tried to update Botium using these command.

 docker-compose -f docker-compose-all.yml stop
> docker-compose -f docker-compose-all.yml pull
> docker-compose -f docker-compose-all.yml up -d
> docker-compose -f docker-compose-all.yml logs -f

The version got updated from Version : release/1.7.4 to Version Release/1.7.5.

But still i am unable to see media card in live chat.

![upadte](https://user-images.githubusercontent.com/46926479/71464159-a4d70780-27de-11ea-9e59-151335368b45.jpg)



Can you help me here.


How to go further..

should i install community version again from latest yaml file.
from docker site i downloaded yaml it had alot of error.

Can you please send here latest yaml here where media feature will work?

**Comment by codeforequity-at** [comment]
the latest release is available for download in the github repository

Abhinav <notifications@github.com> schrieb am Do., 26. Dez. 2019, 08:24:

**Comment by codeforequity-at** [comment]
on another note, currently showing Video attachments is not possible in the Live Chat (only pictures and audio). You can use the video URLs for doing assertions with the _MEDIA_ asserter though.

I added it to our backlog to show video attachments as well. Will be part of the January release.

**Comment by abhinav2019** [comment]
Hi Upgraded to latest Botium Vesrsion. Now that media card is working fine.

But i have one issue in new community edition , It is saying maximum 6 test set are allowed not more than that. is it so ??
or i am doing something wrong here

**Comment by codeforequity-at** [comment]
community edition supports up to six test sets (test set size doesnt matter)

Abhinav <notifications@github.com> schrieb am Fr., 27. Dez. 2019, 11:11:
