### ISSUE TITLE
Testing two different watson nodes based on the quick reply selected by user in the same test

### ISSUE THREAD

**Issue by sushank-rana-a30001665** [codeforequity-at/botium-core#447]
I am trying to write a script to test watson dialog flow for update Email using convo, utterances and pconvo, such that i can validate two different conversation flows based on the quick reply selected by user (yes/no defined in _updatLoginDetails.utterances.txt_).  

When user selects "Yes" - Should validate all the JSON Asserts in the botResponse.utterances.txt.
and when the user selects "No" - should validate the text message in botResponse.utterances.txt.

[botResponse.utterances.txt](https://github.com/codeforequity-at/botium-core/files/4008954/botResponse.utterances.txt)
[updateEmail.convo.txt](https://github.com/codeforequity-at/botium-core/files/4008955/updateEmail.convo.txt)
[updatLoginDetails.utterances.txt](https://github.com/codeforequity-at/botium-core/files/4008956/updatLoginDetails.utterances.txt)

getting following error message:

![image](https://user-images.githubusercontent.com/49701699/71567908-d28dba80-2b16-11ea-9c17-34ddef9d50ca.png)

would appreciate if i could get some direction as how i could write a test to check the above if this isn't the correct approach.

**Comment by sushank-rana-a30001665** [comment]
i have even tried a few other things where i replaced the multiple asserts for "Yes" into another pconvo or utterance file but that i think an utterance file does not accept another pconvo or utterance file inside of it.

**Comment by codeforequity-at** [comment]
an utterances file is just a list of possible text paraphrases (or syonyms). nothing else is expected there. otherwise your test case looks fine on a first glance.

**Comment by codeforequity-at** [comment]
but: when there are branches in the conversation flow, i suggest to split it in two separate test cases (convos). one handles the yes, the other one the no.
the shared part of the conversation could be extracted to a partial convo.

**Comment by codeforequity-at** [comment]
any success here ?

**Comment by sushank-rana-a30001665** [comment]
I am sorry for late response was on a holiday. Thanks for your recommendation, makes more sense to just split the tests in that case.
