### ISSUE TITLE
Question: For Botium Configuration, do we need to add Capabilities and Source both or either one

### ISSUE THREAD

**Issue by stephenws** [codeforequity-at/botium-core#45]
Hi Team

I have one question related Botium configuration 
Do we need to set capabilities and Source together in setup file
OR either we can take?

Please suggest

**Comment by codeforequity-at** [comment]
Hi,
Capabilities are for letting Botium know how to connect to the chatbot. Sources are for letting Botium know where to find the chatbot source code to run (only required when using docker containers right now). 
So, in general, without setting Capabilities, nothing would happen in Botium.

**Comment by stephenws** [comment]
So how to use Source without docker container?

**Comment by codeforequity-at** [comment]
It doesn't make sense to use Source if not running Botium in "docker" mode: the source code of the chatbot is downloaded and transfered to a docker container then. This is not done for the other connector types - for example, when connecting to IBM Watson, the chatbot code itself is not relevant for testing.
