### ISSUE TITLE
Scripting variables are replaced only in the first occurrence

### ISSUE THREAD

**Issue by AliakseiBychyk** [codeforequity-at/botium-core#452]
**Is your feature request related to a problem? Please describe.**
E.g. in the utterance like "I called to **$number** and it didn't answer. Could you check the **$number** number" the only first $number will be replaced with the variable value from scripting memory.

**Describe the solution you'd like**
In the .replace() method assign /g flag for the replaced variable

**Describe alternatives you've considered**
no

**Additional context**

**Comment by AliakseiBychyk** [comment]
Can I make PR?

**Comment by codeforequity-at** [comment]
Yes, sure. I just now added you to the collaborators list!
