### ISSUE TITLE
we are trying to automate a live chatbot, unable to find docker to connect to live chatbot

### ISSUE THREAD

**Issue by SannareddySR** [codeforequity-at/botium-core#46]
Hello team, I am trying to automate a live chatbot, it can be triggered only by hitting the url in browser.
I am not able to find any sample for connecting to live chatbots.
Could you please help in providing a docker to connect to live chatbots

**Comment by codeforequity-at** [comment]
That's to less information to make a valuable suggestion. Please provide information:
* the link to the chatbot if available to public (if you don't want to share here, send email to info@botium.at)
* what kind of backend/conversation engine/bot library is the bot using ? (IBM Watson ? Bot Framework ? Botkit ? ...)
* How does the chatbot frontend in the browser connect to the chatbot backend ? HTTP/REST ? Websocket ? SOAP ? Something else ?

**Comment by SannareddySR** [comment]
Please find the details:
link is not public and hence unable to share.
It is build on botframework and uses HTTPs to connect

**Comment by codeforequity-at** [comment]
You can find some guidelines what is possible with Botium [in the Wiki](https://github.com/codeforequity-at/botium-core/wiki/What-is-Botium-%3F#supported-testing-levels---system-testing-regression-testing-continous-testing-). 

As you are using Bot Framework, continuous testing can be implemented with Botium (on API level).
And as your Bot frontend seems to run in a browser, maybe the "simplerest" connector can be leveraged to perform API testing against your live chatbot as well.

**Comment by codeforequity-at** [comment]
Any Progress ?

**Comment by SannareddySR** [comment]
We are trying to automate the API testing using directline APIs, as the endpoints APIs is not exposed for testing
Please let us know, if the following process is supported in Botium and please suggest a process to perform the same.

1. Get the Conersation Id and Token using the following URL :     var options =  { 
  url : "https://directline.botframework.com/v3/directline/conversations",
  headers : { "Authorization" : 'Secret Key '} ,
  method : 'POST' 
};
2. Post the message using the conversation ID and token generated in Step 1. with URL : 'https://directline.botframework.com/api/conversations/'+ userDetails.conversationId+'/messages using token and body 
3. Get the response using the conversation ID and token generated in Step 1. 'https://directline.botframework.com/api/conversations/'+ userDetails.conversationId+'/messages

**Comment by SannareddySR** [comment]
we have tried to update the simplerest as per our requirement. But as we are very new to node JS we could not achieve the success yet.
It will be very helpful if you can provide the enhanced container and publish it in Botium.
As similar approach for many projects in my organization.

**Comment by codeforequity-at** [comment]
Will do, added enhancement #55 for this

**Comment by SannareddySR** [comment]
Thanks for the help. Will wait for the container to get published.

Mean while I need to inform you that, In the steps 2 and 3 above , I am passing the token, message body and the content-type as header for the request but not the query strings.

**Comment by codeforequity-at** [comment]
I just published the new build 1.3.13. The Direct Line connector for Botium has to be installed separatly, see here for more information: https://github.com/codeforequity-at/botium-core/wiki/operation-mode-directline3

The repository for the Direct Line connector (https://github.com/codeforequity-at/botium-connector-directline3) contains a small sample.

**Comment by SannareddySR** [comment]
Thanks a lot for providing the quick help.

I will try to test my bot using the new API and let you know my progress soon.

**Comment by SannareddySR** [comment]
I am able to install and execute the script in command prompt by updating my secrete key botium.json file.
But when I tried to debug the same file in .vscode, it is throwing an error message "Error: Capability property STARTCMD not set". 
I am not sure what would be the reason behind this. Can we debug the code in VS code and do we need any extra configurations for this ?

**Comment by codeforequity-at** [comment]
Did you try out the sample script ?
https://github.com/codeforequity-at/botium-connector-directline3/tree/master/samples

**Comment by SannareddySR** [comment]
Yes I have tried the sample script.
Steps that I have followed.
1. Created a new folder.
2. In command prompt, navigated to the newly created folder and executed the npm install botium-core andnpm install botium-connector-directline3.
3. Opened this folder in VScode and Navigated to the \node_modules\botium-connector-directline3\samples\botium.json and updated the secrete key and saved.
4.  updated the launch program to  "\node_modules\botium-connector-directline3\samples 
\node botiumFluent.js"
5. Getting an error message "Capability property STARTCMD not set"  when I execute by pressing F5.
6. But , In command prompt navigated to the \node_modules\botium-connector-directline3\samples and executed "node botiumFluent.js", I am getting the out put.
Not sure on what I am doing wrong.

Thanks in advance.

**Comment by codeforequity-at** [comment]
botium.json has to be placed in the current directory

**Comment by SannareddySR** [comment]
I am executing directly from the below path.
C:\Users\myusername\Desktop\AITesting\node_modules\botium-connector-directline3\samples

Can you please let me know, where I need to place or move the botium.json.

**Comment by codeforequity-at** [comment]
did you succeed ?

**Comment by SannareddySR** [comment]
Hello 
apologies for late response. From VS code I still could not run that. I will try it again.

But for now **I am able to execute through Command prompt and I have extended the functionality to validate the responses and print them in to a text file.** 

Thanks a lot for all the support you have provided.

**Comment by codeforequity-at** [comment]
that's great news, thanks for the feedback.
I am curious why it doesn't work from VS Code - will try it myself.

**Comment by codeforequity-at** [comment]
OK, I succeeded in running it from the VSCode included terminal - but this is really nothing different from just running it in a shell window. So what did you try to do with VSCode ?

**Comment by mvsmurty** [comment]
Hello, we have the chatbot based on websocket protocol. we are building our own framework based on wss. Are the drivers available for wss? Please help.

Venkat
