### ISSUE TITLE
Update_custom botkit_user_id doesn't work on .pconvo.txt

### ISSUE THREAD

**Issue by lsshawn** [codeforequity-at/botium-core#461]
**Describe the bug**
This relates to #444. `UPDATE_CUSTOM BOTKIT_USER_ID` doesn't work on partial convo files (.pconvo.txt). 

**To Reproduce**

// test.convo.txt

test

#begin
UPDATE_CUSTOM BOTKIT_USER_ID|aaa

#me
hi

INCLUDE test partial

// test.pconvo.txt

test partial

#me 

second hi

**Expected behavior**
In the "second hi" the user should be 'aaa'.

**Botium Flavour:**
 - Botium Bindings 2.0.27

**Comment by codeforequity-at** [comment]
fixed with #462, will be part of february build
