### ISSUE TITLE
Issue observed while running tests on a Mac machine

### ISSUE THREAD

**Issue by sushank-rana-a30001665** [codeforequity-at/botium-core#464]
I had written some botium-watson tests on the windows machine and was trying to run them on a Mac for a different user. Observation is, lets say i changed the JSON assert value such that the tests will fail, but on the Mac the test still passes. Not really sure whats going on here. 

Below is the image of the same test run on windows and Mac [macOS Catalina], on windows it fails as expected but on the Mac it Passes

**On windows**
![image](https://user-images.githubusercontent.com/49701699/73236773-ac2b6f80-41e7-11ea-8ec6-c4b82f4e36ac.png)

**On Mac**
![image](https://user-images.githubusercontent.com/49701699/73237258-17297600-41e9-11ea-9fcf-dd5da9d20bc5.png)

**Comment by codeforequity-at** [comment]
Honestly, no idea. can you bring this down to the most easy case to reproduce ?
