### ISSUE TITLE
Generic HTTP(S)/JSON Connector: Response body is not being parsed

### ISSUE THREAD

**Issue by omoravskyi** [codeforequity-at/botium-core#465]
This issue is the copy of this #162  so I won't provide logs and steps to reproduce, as they are  identical.

Unfortunately, as you can see, it was not fixed. At that moment we decided to go with manually fixing _SimpleRestContainer.js_ file to suit our needs. 
But now the **Botium Box** is presented and we would like to use it. And with this bug we can't configure **Chatbot connector** within the **Botium Box**.

I am ready to provide additional information for debugging, like testing endpoint and the configuration we are using for tests (preferably in private).

**Comment by codeforequity-at** [comment]
Hi, please provide configuration for reproducing it to florian.treml "at" botium.at
thanks

**Comment by omoravskyi** [comment]
Thanks, the issue does not reproduce after new release of [botium-core v.1.8.2.](https://github.com/codeforequity-at/botium-core/releases/tag/1.8.2)
