### ISSUE TITLE
simplegRPC analogue to simplerest

### ISSUE THREAD

**Issue by staticdev** [codeforequity-at/botium-core#471]
**Is your feature request related to a problem? Please describe.**
For modern applications gRPC APIs are being used as a substitution for REST APIs (for much better performance, smaller network and storage requirements). It would be nice to have a gRPC server could be tested by botium with a new simplegRPC CONTAINERMODE.

**Describe the solution you'd like**
botium.json could be configured with this new container mode, a URL, and a stub generated from a .proto file.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by codeforequity-at** [comment]
added to the backlog

**Comment by staticdev** [comment]
@codeforequity-at since it is in the backlog, should this stay opened?

**Comment by staticdev** [comment]
@codeforequity-at there is a sample of loading proto [here](https://grpc.io/docs/languages/node/basics/). Hope that helps.. Dialogflow for example is deprecating REST api in favor to gRPC.

**Comment by codeforequity-at** [comment]
To get things rolling, maybe you could start a botium connector project on your own, and I will add it to the core distribution as soon as it works ? It shouldn't be too complicated to make a first usefull version, it is comparable to the websocket connector I would say - https://github.com/codeforequity-at/botium-connector-websocket

**Comment by staticdev** [comment]
@codeforequity-at I could try to help... since it is binary communication, there is no need for these JSON paths (but objects are serialized as Javascript Objects), HTTP methods or status codes.

The usual application with Botium I have uses:

```json
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "rest-bot",
      "CONTAINERMODE": "simplerest",
      "SCRIPTING_ENABLE_MEMORY": true,
      "SIMPLEREST_URL": "http://localhost:5000/reply",
      "SIMPLEREST_METHOD": "POST",
      "SIMPLEREST_HEADERS_TEMPLATE": "{ \"content-type\": \"application/json; charset=utf-8\" }",
      "SIMPLEREST_BODY_TEMPLATE": "{ \"message\": \"{{msg.messageText}}\", \"user_id\": \"botium\" }",
      "SIMPLEREST_RESPONSE_JSONPATH": "$.reply",
      "SIMPLEREST_INIT_TEXT": "reset_conversation"
    },
  }
}
```

Let's say for a simple .proto:

```proto
// botiumgrpc.proto
syntax = "proto3";

package botiumgrpcbot;

// Interface for brain.
service BotiumGrpc {
  // Gets reply from one message
  rpc GetReply(GetReplyRequest) returns (GetReplyResponse) {}
}

// Message request.
message GetReplyRequest {
  string text = 1;
  string user_name = 2;
}

// Message response.
message GetReplyResponse {
  string text = 1;
}
```

I would say an analogue botium.json would be:
```json
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "grpc-bot",
      "CONTAINERMODE": "simplegrpc",
      "SCRIPTING_ENABLE_MEMORY": true,
      "GRPC_URL": "localhost:50051",
      "GRPC_PROTO": "botiumgrpc.proto",
      "GRPC_REQUEST_METHOD": "GetReply",
      "GRPC_REQUEST_MESSAGE": "{\"text\": \"{{msg.messageText}}\", \"user_name\": \"botium\"}",
      "GRPC_RESPONSE_FIELD": "text",
      "GRPC_INIT_TEXT": "reset_conversation"
    },
  }
}
```

If you create a repo for that as a separate connector as in https://github.com/codeforequity-at/botium-connector-websocket I can also try to contribute with PRs (but I struggle a bit with Javascript).

**Comment by staticdev** [comment]
@codeforequity-at please create a project then we can try some collaboration on this if you may.

**Comment by codeforequity-at** [comment]
https://github.com/codeforequity-at/botium-connector-grpc

You should have received an invitation

**Comment by staticdev** [comment]
@codeforequity-at nice, invitation accepted! How should we proceed? Do you want a call to discuss or already have a plan?

**Comment by codeforequity-at** [comment]
not really having a plan. if you could build some minimum GRPC server and client code I can copy&paste it into the Botium connector code - but you can try yourself to do this as well. The boilerplate is there, and there are some places in the src/connector.js where the actual GRPC request has to be done ...

**Comment by szabi84** [comment]
@staticdev The 1st version of grpc connector is ready. 
You can try it out by running the samples/echoserver (grpc server), and then start the samples/echo to run a very simple test.

1. in root directory:
`npm install`

2. samples/echoserver: 
`npm install
 npm start`

3. samples/echo: 
`npm install
 npm test`

Please take a look and don't hesitate to ask. (The readme file will be written soon as well)

**Comment by staticdev** [comment]
@szabi84 sorry for the long delay, I just relocated continent and I will try ASAP. Thanks a lot.
