### ISSUE TITLE
Memory variable assignments don't work with bot CARD input

### ISSUE THREAD

**Issue by veliander** [codeforequity-at/botium-core#477]
**Describe the bug**

I can assign words from a bot utterance (messageText) to variables, and then use those values in my own utterances, as described in [the wiki.](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/48922663/Scripting+Memory+Variables) 

However, things didn't work out when I tried to do the same thing with a card value instead of messageText.  

When running a test script similar to the one below, instead of assigning the variable, Botium decided to fail the test with 'Expected: "INVOICE NUMBER,$invoiceNumber" - Actual: "INVOICE NUMBER,634633"'

Shouldn't that work, and if not, Is there another way to assign a memory variable value from botMsg fields other than mesageText?

**To Reproduce**

1. Create a bot based on the Generic HTTP(S)/JSON Interface connector.
2. Make sure its outgoing (toward Botium Core) botMsg contains several cards with fields "text" and "content" set to values extracted from bot's answer ( e.g. text:"INVOICE NUMBER" and content:"634633")
3.  Create a test script similar to this one:

<pre><code>
validate value
extract value from table and form further utterances based on that value

#me
get invoice details for customer number 435643
 
#bot
CARDS INVOICE NUMBER|$invoiceNumber
  
#me 
get invoice due date for invoice number $invoiceNumber
 
#bot
invoice due date for invoice number $invoiceNumber is 02/12/2020
</code></pre>

**Expected behavior**

I expected Botium to assign a value to the variable instead of comparing its (variable's) identifier to the actual number sent by the bot.  It works that way for words in normal bot utterances (ones contained in botMsg. messageText).

**Botium Flavour:**
 - Botium Box ?
      CE, latest version from the Docker repository

**Botium Version**

Build Branch: release/2.3.0
Build Revision: 3a579a5d3cfc02ce2851c9da9ea8ab4fafb4044c
Build Date: 2020-02-21T16:44:53+0000
Licensed Edition: community
License Validity: no restrictions
License Operability: no restrictions

**Comment by codeforequity-at** [comment]
PR #485 on the way with a new logic hook **ASSIGN_SCRIPTING_MEMORY** included, which can be used to assign part of the invoice card to a memory variable.

Your example will look like this:

```
validate value
extract value from table and form further utterances based on that value

#me
get invoice details for customer number 435643
 
#bot
CARDS INVOICE NUMBER
ASSIGN_SCRIPTING_MEMORY invoiceNumber|$.cards[0].content
  
#me 
get invoice due date for invoice number $invoiceNumber
 
#bot
invoice due date for invoice number $invoiceNumber is 02/12/2020
```
