### ISSUE TITLE
Multiple values 

### ISSUE THREAD

**Issue by akshayCha** [codeforequity-at/botium-core#48]
Is there any way I could possibly test for multiple conditions through one single "UserSaysText" or one single "WaitBotSaysText"?

I have a bot that follows a conversation tree and at each node there can be multiple inputs/outputs to the bot. If I write tests for all possible combinations, I'll easily be writing over a million different scripts. Is there a way to check for a array of string values instead of one single string in the conversation flow?

Thankyou

**Comment by codeforequity-at** [comment]
Yes, indeed there is. Please read about it [here](https://github.com/codeforequity-at/botium-core/wiki/Botium-Scripting). In short, it is possible to list all utterances for bot input and output in seperate files, and define the conversation structure just once.

**Comment by codeforequity-at** [comment]
Did you try it out ?

**Comment by akshayCha** [comment]
Hi, yes I did try it out, but I keep getting the same error  

(node:3058) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Test cases for chatbot/Line 7: error sending to bot TypeError: Cannot set property 'msg' of undefined

_This is my sample code_

const BotDriver = require('botium-core').BotDriver
const Capabilities = require('botium-core').Capabilities
const Source = require('botium-core').Source

function assert (expected, actual) {
  if (!actual || actual.indexOf(expected) < 0) {
    console.log(`ERROR: Expected <${expected}>, got <${actual}>`)
  } else {
    console.log(`SUCCESS: Got Expected <${expected}>`)
  }
}

const driver = new BotDriver()
  .setCapability(Capabilities.PROJECTNAME, 'Delta-Chatomate')
  .setCapability(Capabilities.CONTAINERMODE, 'simplerest')
  .setCapability(Capabilities.SIMPLEREST_URL, 'https://delta-chatomate.herokuapp.com/bot/')
  .setCapability(Capabilities.SIMPLEREST_METHOD, 'POST')
  .setCapability(Capabilities.SIMPLEREST_BODY_TEMPLATE, 'userUtterance={{msg.messageText}}&sender=765757765')
  .setCapability(Capabilities.SIMPLEREST_BODY_RAW, true)
  .setCapability(Capabilities.SIMPLEREST_HEADERS_TEMPLATE, '{ "Content-Type": "application/x-www-form-urlencoded" }')
  .setCapability(Capabilities.SIMPLEREST_CONTEXT_JSONPATH, '$')
  .setCapability(Capabilities.SIMPLEREST_RESPONSE_JSONPATH, '$.utterance')

driver.BuildFluent()
  .ReadScripts('convos')
  .RunScripts()
  .Exec()


I have created a folder called convos in the same directory as my test script, which contains a file called one.convo.txt

_Here are the contents of that file_

Test cases for chatbot
A simple test case

#me
Hello there 

#bot
Hello there. I am ChatomateBot.


Does this have the same problem that it does not support urlencoded formats? Thanks

**Comment by codeforequity-at** [comment]
In your code, a call to "Start" method is missing - this should definitly be catched in the Botium API.

This example works (at least for me) - I extracted the configuration from the script to an external configuration file botium.json:

File "botium.json":
```
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "Delta-Chatomate",
      "CONTAINERMODE": "simplerest",
      "SIMPLEREST_URL": "https://delta-chatomate.herokuapp.com/bot/",
      "SIMPLEREST_METHOD": "POST",
      "SIMPLEREST_BODY_TEMPLATE": "userUtterance={{msg.messageText}}&sender=765757765",
      "SIMPLEREST_BODY_RAW": true,
      "SIMPLEREST_HEADERS_TEMPLATE": "{ \"Content-Type\": \"application/x-www-form-urlencoded\" }",
      "SIMPLEREST_CONTEXT_JSONPATH": "$",
      "SIMPLEREST_RESPONSE_JSONPATH": "$.utterance"
    }
  }
}
```

File "botiumFluent.js":
```
const BotDriver = require('../../index').BotDriver
const Capabilities = require('../../index').Capabilities
const Source = require('../../index').Source

const driver = new BotDriver()

driver.BuildFluent()
  .ReadScripts('convos')
  .Start()
  .RunScripts()
  .Exec()
  .then(() => {
    console.log('READY')
  })
  .catch((err) => {
    console.log('ERROR: ', err)
  })
```

**Comment by akshayCha** [comment]
Hi, it works perfectly now, thanks a lot for the solution! The wiki page that describes Botium Scripting has an example 

`driver.BuildFluent()
  .ReadScripts('convos')
  .RunScripts()
  .Exec()`

Maybe you wanna change that as well to include the Start statement as well, thanks again!

**Comment by codeforequity-at** [comment]
Thanks for the hint. Corrected in Wiki.

**Comment by akshayCha** [comment]
Hi, sorry about bringing this up again but I would really appreciate if you could provide some description as to how I can change the settings to 'expand' to multiple user inputs with an utterance file. The default only seems to be taking the first utterance, and it isn't randomised. Thanks

**Comment by codeforequity-at** [comment]
The expansion is done automatically when using the Fluent API, like in the sample:
https://github.com/codeforequity-at/botium-core/blob/master/samples/utterances/botiumFluent.js

Currently, there is not setting to randomize the input  from utterances, as we believe that dealing with random input is not helpful in test automation in general (in special cases, yes it would be helpful, for example smoke tests or performance tests).

Are your utterances files in the same folder as the convo files ? Maybe you could prepare an example again ?

**Comment by akshayCha** [comment]
Here is a sample of my conversation and utterance file. I'm simply reading 'convos' in my test file like you mentioned. 

`Test cases for chatbot
A simple test case

#me
yes

#bot
Would you like to find your nearest bureau or want to know the documents to take to your meeting?

#me
nearest bureau

#bot
Tell me your postcode area. For example, Edinburgh, Perth, Glasgow, etc. If you are not sure, read out the first two letters in your postcode. For Glasgow, its just one letter, G.

#me
RESPONSE1

#bot
Okay, Edinburgh`



`RESPONSE1
Edinburgh
Perth
Glasgow
Aberdeen`

This input always selects Edinburgh and doesn't pick Perth, Glasgow or Aberdeen. Will I have to write more conversation files to test all cases? If so, what will they be called? Thanks

**Comment by codeforequity-at** [comment]
So, with this example, I am receiving an error:

ERROR:  Error: Test cases for chatbot/Line 10: Expected bot response "All right!" to match one of "Would you like to find your nearest bureau or want to know the documents to take to your meeting?"
    at Object.assertBotResponse (D:\dev\temp\utt_sample\node_modules\botium-core\dist\botium-cjs.js:1071:17)
    at D:\dev\temp\utt_sample\node_modules\botium-core\dist\botium-cjs.js:524:51
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)



But you can inspect yourself, just enable debug logging ("export DEBUG=botium*")

**Comment by codeforequity-at** [comment]
?

**Comment by codeforequity-at** [comment]
Closed for no feedback
