### ISSUE TITLE
Client request Error while connecting to ALEXA-SMAPI

### ISSUE THREAD

**Issue by ShivamGarg2910** [codeforequity-at/botium-core#480]
Using Botium-CLI to connect to Alexa-SMAPI.
Configured these fields in botium.json:

- "CONTAINERMODE":"alexa-smapi"

- "ALEXA_SMAPI_API":"simulation"

- "ALEXA_SMAPI_SKILLID"

- "ALEXA_SMAPI_BASE_URL":"https://api.amazonalexa.com/"

- "ALEXA_SMAPI_REFRESHTOKEN"

- "ALEXA_SMAPI_CLIENTID"

- "ALEXA_SMAPI_CLIENTSECRET"

On running command botium-cli run,
I receive the following error: Client request error: getaddrinfo ENOTFOUND api.amazon.com api.amazon.com:443.

Screenshot:
![image](https://user-images.githubusercontent.com/25713041/75513976-5b907780-5a1c-11ea-8b95-d3ebbe1bb51e.png)

 Kindly guide me on what am I missing?

**Comment by codeforequity-at** [comment]
It seems as if the host api.amazon.com is not reachable from your workstation. Maybe firewall or proxy is blocking request. Can you please try this:
    
    ping api.amazon.com

**Comment by ShivamGarg2910** [comment]
Tried that.
Proxy is blocking.

**Comment by codeforequity-at** [comment]
ok ... and how can I help you ?

**Comment by ShivamGarg2910** [comment]
Where can we configure proxies in Botium?

**Comment by codeforequity-at** [comment]
You can set the well-known environment variables HTTP_PROXY/HTTPS_PROXY/NO_PROXY to use a company proxy.

**Comment by ShivamGarg2910** [comment]
This didn't help.

**Comment by codeforequity-at** [comment]
how did you set the environment variables

**Comment by ShivamGarg2910** [comment]
Following are the commands I ran to set my environment variables:
export proxy=http://<username>:<password>@<myProxyServerIp>
export PROXY=http://<username>:<password>@<myProxyServerIp>
export http_proxy=http://<username>:<password>@<myProxyServerIp>
export HTTP_PROXY=http://<username>:<password>@<myProxyServerIp>
export https_proxy=https://<username>:<password>@<myProxyServerIp>
export HTTPS_PROXY=https://<username>:<password>@<myProxyServerIp>

**Comment by codeforequity-at** [comment]
same error message coming (ENOTFOUND) or something different ?

**Comment by ShivamGarg2910** [comment]
![image](https://user-images.githubusercontent.com/25713041/75952900-0cdc5500-5ed6-11ea-99ce-d8938b69adf0.png)
This is coming on pinging after setting proxies.

**Comment by codeforequity-at** [comment]
ping doesn't use proxies. use curl for testing this.

**Comment by ShivamGarg2910** [comment]
Used curl for testing.
It gives following error when running command "curl http://api.amazon.com"
![image](https://user-images.githubusercontent.com/25713041/76417251-92727000-63c2-11ea-8a74-30ed6f88e9fe.png)
It gives following error when running command "curl https://api.amazon.com"
![image](https://user-images.githubusercontent.com/25713041/76417338-b9c93d00-63c2-11ea-8b1a-bab4001181b3.png)
 While running "botium-cli run --verbose --convos .", it still gives same error.

**Comment by ShivamGarg2910** [comment]
Used postman for connecting to Alexa SMAPI, received 200 response code, still receiving same error in botium-cli run.

**Comment by codeforequity-at** [comment]
The proxy requires authentication. Postman is able to use the system proxy, so it works with Postman.

You can try to use a proxy url in the form http://user:password@myproxy.com

**Comment by ShivamGarg2910** [comment]
Tried proxy url in above mentioned form. Still no result. Same error:
![image](https://user-images.githubusercontent.com/25713041/76607469-01bea000-653a-11ea-9293-7d71d9babc52.png)

**Comment by codeforequity-at** [comment]
I am sorry, no idea how I could help further. On our demo site the connection is working (just tried some seconds ago).
