### ISSUE TITLE
Open/close conversation in every convo using simplerest

### ISSUE THREAD

**Issue by staticdev** [codeforequity-at/botium-core#490]
**Is your feature request related to a problem? Please describe.**
To test a chatbot, I need to call another endpoint to start the conversation and get a conversation id. After the tested dialogue (per convo file), a method call for closing the conversation is also usefull. Is it possible?

**Describe the solution you'd like**
I would like to set parameters in botium.json that enables running a REST call after and before tests.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by codeforequity-at** [comment]
Maybe the _Custom Hooks_ help here ? See [Botium Wiki](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360603/Botium+Configuration+-+Capabilities#Custom-Hooks)

**Comment by codeforequity-at** [comment]
No, custom hooks don't help, as you want to have a conversation id available in the test case.

I would say, this is doable with the Session Setup and Session Teardown calls: https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/24510469/Generic+HTTP+S+JSON+Connector

**Comment by codeforequity-at** [comment]
any success here ?
