### ISSUE TITLE
New line at the end of file in *.scriptingmemory.txt files uses the name of variable as a varibale

### ISSUE THREAD

**Issue by piotrjak** [codeforequity-at/botium-core#492]
**Describe the bug**
If you add a new line at the end of *.scriptingmemory.txt files then the name of the variable would be assigned to the variable

**To Reproduce**
Add a new line at the end of *.scriptingmemory.txt file

**Expected behavior**
The name of the variable shouldn't be assigned to the variable

**Screenshots and Log files**
![image](https://user-images.githubusercontent.com/45995385/76425442-e9b81680-63a9-11ea-8c9d-5a53ac199272.png)

If the sentence is: "Show me market snapshots in $neighborhood"
then in this case the first test would be "Show me market snapshots in $neighborhood",
but it should be "show me market snapshot in Fairfax Village"

**if I REMOVE the new line then it works as it should!!!**

**Botium Flavour:**
 - Botium Bindings

**Botium Version**
botium-bindings 2.0.29

**Additional context**

**Comment by codeforequity-at** [comment]
Thanks for the bug alert. fixed and will be part of next build.
