### ISSUE TITLE
Sample for Body Template in Botium-Box for Generic HTTP connector

### ISSUE THREAD

**Issue by ShivamGarg2910** [codeforequity-at/botium-core#495]
Hi, I am unable to understand how should I send a "Hi" message in mustache template.
In this field, "text": "{{msg.messageText}}" where should I define messageText.

Please help in this matter.
![image](https://user-images.githubusercontent.com/25713041/77161376-8461d500-6acf-11ea-9870-391e44b8d802.png)

**Comment by codeforequity-at** [comment]
messageText is coming from the BotiumScript convo
