### ISSUE TITLE
Using Environment Variables in Capability values

### ISSUE THREAD

**Issue by asonee-omnipresence** [codeforequity-at/botium-core#505]
**Is your feature request related to a problem? Please describe.**
I'm looking to use Environment Variables in capability values (**JSON structure**) under the bot advanced settings.
As per Screenshot1 below, I've a DIRECTLINE3_ACTIVITY_TEMPLATE which is required to set some additional data for every conv with the bot. It has 3 keys, accessToken, userId and userName.
These 3 values are not constant and I want use Environment Variables here so it is easier to change the Env variables.
I've created a Env variable 'ACCESS_TOKEN' but I was not able to use it in the JSON.

**Describe the solution you'd like**
Is it already possible to use this? 

**Additional context**
Screenshot 1: 
![image](https://user-images.githubusercontent.com/64209093/80213684-2b99d500-8657-11ea-8db3-b3806d68785a.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/64209093/80213534-f1303800-8656-11ea-9ed2-7954f9768b2c.png)

Please advise.

**Comment by codeforequity-at** [comment]
It's not possible to use environment variables as part of a capability.
It is possible to hand over capabilities from environment variables by using the BOTIUM_-prefix (BOTIUM_DIRECTLINE3_ACTIVITY_TEMPLATE) - see [Botium Wiki](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/360603/Botium+Configuration+-+Capabilities). 
But I don't see how using environment variables as part of a capability could make your life easier here - you would have to manage them anyhow.

**Comment by asonee-omnipresence** [comment]
Thanks for the quick response.
Yes, I was just wondering if use env variables can be used. Like you said, I'd still have to manually change it.
