### ISSUE TITLE
[Clarification]- How to create Chatbot connector for Chatbot available for webpage after login

### ISSUE THREAD

**Issue by kvenkat88** [codeforequity-at/botium-core#506]
First of all thanks for creating this wonderful solution for automating boys.

**Description**
Wanted to create Chatbot connector for Chatbot available flow for webpage after login.

**Steps to Test Chatbot**
1.Login to web portal and navigate to page having link to open chatbot.
2.Have to interact with chatbot and it is having buttons and minimal text input for interaction.

**Notes**
1.Backend of chatbot is RASA core
2.Frontend it is exposed as REST API.

**Necessary Inputs**
1.What techniques or chatbot connectors to use?
2.We have to use Webdriver io(Selenium or Appium) Or Others(Advanced) and place the custom botium connector option.
3.If custom botium connector, then please give me any reference material or suggest me ways please.
4.I have tried with custom connector with .js scripts, then it is asking WEBDRIVERIO_PROFILE and which profile we have to give to proceed.

Thanks in Advance.

**Comment by codeforequity-at** [comment]
For selecting an appropriate connector see [this](https://medium.com/@floriantreml/botium-in-a-nutshell-part-9-selecting-a-botium-connector-f27a56d55bf4) to get an overview.

* For NLP model testing, there is a [Rasa Connector](https://github.com/codeforequity-at/botium-connector-rasa) available
* For system integration testing, there is [generic HTTP/JSON connector](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/24510469/Generic+HTTP+S+JSON+Connector) available, which can be customized to match your REST API

* For E2E Tests there is the Webdriver connector available (see [here](https://medium.com/@floriantreml/botium-in-a-nutshell-part-6-e2e-testing-with-botium-box-9bd8acdf5a70)), but this is typically the most complex to setup.

**Comment by kvenkat88** [comment]
Thank you so much for replying.

It would to be nice to have if we simply the process of setting up custom Webdriver connector, so that we can cover the E2E testing in user perspective also.

**Comment by codeforequity-at** [comment]
For Botium Box, there are some [Webdriver samples available](https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/57671681/Howto+Import+Botium+Samples).

The linked blog articles and repositories are the best documentation resources currently existing. 

With the current version there is know-how in Selenium needed to specify the selectors for Botium and maybe to develop code snippets.
