### ISSUE TITLE
How to handle test in different languages ?

### ISSUE THREAD

**Issue by pybanaszak** [codeforequity-at/botium-core#51]
Hi, 

Thanks a lot for this great tool. 

We have a bot on dialogflow. The bot is setup in both french and english languages.
How to configure our botium instance in order to test all the intents in french and then all the intent in english ?
Not sure why but the first time I ran the tool, I had questions in french and responses in english....

Thanks a lot,
Pierre-Yves

**Comment by pybanaszak** [comment]
I found those config params using the verbose option and by adding them to the botium.json, it seems to do the trick ;) 

```
"DIALOGFLOW_LANGUAGE_CODE" : "fr-FR",
"WEBSPEECH_LANGUAGE": "fr-FR"
```

**Comment by codeforequity-at** [comment]
The capability in qustion is DIALOGFLOW_LANGUAGE_CODE (the other one is for speech output ...)

**Comment by pybanaszak-auchan** [comment]
Hi,

I have now an issue trying to export the conversation in dialogflow in specific language. eventhough I have the botium.json file setup with the DIALOGFLOW_LANGUAGE_CODE = 'en' when I run the command _botium-cli import dialogflow-conversations_ I get the export in french...

Any idea ?
Thanks,

**Comment by codeforequity-at** [comment]
Please run with --verbose and attach output here for investigation.

2018-05-22 14:34 GMT+02:00 pybanaszak-auchan <notifications@github.com>:

**Comment by pybanaszak-auchan** [comment]
botium-cli Loading Botium configuration file /Volumes/Data/Pro/my-tests/botium.json +0ms
  botium-cli-import command options: { _: [ 'import' ],
  botium-cli-import   help: false,
  botium-cli-import   h: false,
  botium-cli-import   version: false,
  botium-cli-import   V: false,
  botium-cli-import   verbose: true,
  botium-cli-import   v: true,
  botium-cli-import   convos: [ '/Volumes/Data/Pro/my-tests/test_files' ],
  botium-cli-import   C: [ '.' ],
  botium-cli-import   config: '/Volumes/Data/Pro/my-tests/botium.json',
  botium-cli-import   c: '/Volumes/Data/Pro/my-tests/botium.json',
  botium-cli-import   '$0': 'botium-cli',
  botium-cli-import   source: 'dialogflow-conversations',
  botium-cli-import   configJson: { botium: { Capabilities: [Object] } } } +0ms
  botium-cli-import-watson-intents {
  botium-cli-import-watson-intents   "botium": {
  botium-cli-import-watson-intents     "Capabilities": {
  botium-cli-import-watson-intents       "PROJECTNAME": "XXX",
  botium-cli-import-watson-intents       "CONTAINERMODE": "dialogflow",
  botium-cli-import-watson-intents       "DIALOGFLOW_PROJECT_ID": "lXXX",
  botium-cli-import-watson-intents       "DIALOGFLOW_CLIENT_EMAIL": "XXX",
  botium-cli-import-watson-intents       "DIALOGFLOW_PRIVATE_KEY": "XXX",
  botium-cli-import-watson-intents       "DIALOGFLOW_USE_INTENT": false,
  botium-cli-import-watson-intents       "DIALOGFLOW_LANGUAGE_CODE": "en"
  botium-cli-import-watson-intents     }
  botium-cli-import-watson-intents   }
  botium-cli-import-watson-intents } +0ms
  botium-BotDriver Build - Sources : { LOCALPATH: '.',
  botium-BotDriver   GITPATH: 'git',
  botium-BotDriver   GITBRANCH: 'master',
  botium-BotDriver   GITDIR: '.' } Capabilites: { PROJECTNAME: 'XXX',
  botium-BotDriver   TEMPDIR: 'botiumwork',
  botium-BotDriver   CLEANUPTEMPDIR: true,
  botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
  botium-BotDriver   CONTAINERMODE: 'dialogflow',
  botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
  botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
  botium-BotDriver   DOCKERMACHINE: false,
  botium-BotDriver   DOCKERIMAGE: 'node:boron',
  botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
  botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
  botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
  botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  botium-BotDriver   WATSONCONVERSATION_URL: 'https://gateway.watsonplatform.net/conversation/api',
  botium-BotDriver   WATSONCONVERSATION_VERSION_DATE: '2017-05-26',
  botium-BotDriver   WATSONCONVERSATION_COPY_WORKSPACE: false,
  botium-BotDriver   WATSONCONVERSATION_USE_INTENT: false,
  botium-BotDriver   SIMPLEREST_METHOD: 'GET',
  botium-BotDriver   DIALOGFLOW_LANGUAGE_CODE: 'en',
  botium-BotDriver   DIALOGFLOW_USE_INTENT: false,
  botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
  botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
  botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
  botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
  botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
  botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
  botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
  botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
  botium-BotDriver   DIALOGFLOW_PROJECT_ID: 'XXX',
  botium-BotDriver   DIALOGFLOW_CLIENT_EMAIL: 'XXX,
  botium-BotDriver   DIALOGFLOW_PRIVATE_KEY: 'XXX' } +0ms
  botium-BotDriver BuildCompiler: Capabilites: { PROJECTNAME: 'XXX',
  botium-BotDriver   TEMPDIR: 'botiumwork',
  botium-BotDriver   CLEANUPTEMPDIR: true,
  botium-BotDriver   WAITFORBOTTIMEOUT: 10000,
  botium-BotDriver   CONTAINERMODE: 'dialogflow',
  botium-BotDriver   DOCKERCOMPOSEPATH: 'docker-compose',
  botium-BotDriver   DOCKERMACHINEPATH: 'docker-machine',
  botium-BotDriver   DOCKERMACHINE: false,
  botium-BotDriver   DOCKERIMAGE: 'node:boron',
  botium-BotDriver   DOCKERUNIQUECONTAINERNAMES: false,
  botium-BotDriver   DOCKERSYSLOGPORT_RANGE: '47100-47299',
  botium-BotDriver   SLACK_PUBLISHPORT_RANGE: '46100-46299',
  botium-BotDriver   FACEBOOK_PUBLISHPORT_RANGE: '46300-46499',
  botium-BotDriver   FACEBOOK_SEND_DELIVERY_CONFIRMATION: true,
  botium-BotDriver   BOTFRAMEWORK_PUBLISHPORT_RANGE: '46500-46699',
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PORT: 3978,
  botium-BotDriver   BOTFRAMEWORK_WEBHOOK_PATH: 'api/messages',
  botium-BotDriver   BOTFRAMEWORK_CHANNEL_ID: 'facebook',
  botium-BotDriver   WATSONCONVERSATION_URL: 'https://gateway.watsonplatform.net/conversation/api',
  botium-BotDriver   WATSONCONVERSATION_VERSION_DATE: '2017-05-26',
  botium-BotDriver   WATSONCONVERSATION_COPY_WORKSPACE: false,
  botium-BotDriver   WATSONCONVERSATION_USE_INTENT: false,
  botium-BotDriver   SIMPLEREST_METHOD: 'GET',
  botium-BotDriver   DIALOGFLOW_LANGUAGE_CODE: 'en',
  botium-BotDriver   DIALOGFLOW_USE_INTENT: false,
  botium-BotDriver   WEBSPEECH_SERVER_PORT: 46050,
  botium-BotDriver   WEBSPEECH_LANGUAGE: 'en-US',
  botium-BotDriver   WEBSPEECH_CLOSEBROWSER: true,
  botium-BotDriver   SCRIPTING_TXT_EOL: '\n',
  botium-BotDriver   SCRIPTING_XLSX_STARTROW: 1,
  botium-BotDriver   SCRIPTING_XLSX_STARTCOL: 'A',
  botium-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
  botium-BotDriver   SCRIPTING_MATCHING_MODE: 'includeLowerCase',
  botium-BotDriver   DIALOGFLOW_PROJECT_ID: 'XXX',
  botium-BotDriver   DIALOGFLOW_CLIENT_EMAIL: 'XXX',
  botium-BotDriver   DIALOGFLOW_PRIVATE_KEY: 'XXX' } +11ms
  botium-ScriptingProvider Using matching mode: includeLowerCase +0ms
  
  botium-cli-import-watson-intents Dialogflow agent got entry: package.json +4s
  botium-cli-import-watson-intents Dialogflow agent got entry: agent.json +1ms
  botium-cli-import-watson-intents Dialogflow agent got entry: intents/00 - Un magasin.json +1ms
  ...

  botium-cli-import-watson-intents Dialogflow agent info: { description: '',
  botium-cli-import-watson-intents   language: 'fr',
  botium-cli-import-watson-intents   activeAssistantAgents: [],
  botium-cli-import-watson-intents   disableInteractionLogs: false,
  botium-cli-import-watson-intents   disableStackdriverLogs: true,
  botium-cli-import-watson-intents   googleAssistant: 
  botium-cli-import-watson-intents    { googleAssistantCompatible: false,
  botium-cli-import-watson-intents      welcomeIntentSignInRequired: false,
  botium-cli-import-watson-intents      startIntents: [],
  botium-cli-import-watson-intents      systemIntents: [],
  botium-cli-import-watson-intents      endIntentIds: 
  botium-cli-import-watson-intents       [ 'fb660189-2f95-48ba-aea7-f4644af47331',
  botium-cli-import-watson-intents         '3b9e05b7-d38f-4ee2-8c0a-adf3b65a4ff0',
  botium-cli-import-watson-intents         '694afedd-5409-45d6-a7a4-701058f449c3',
  botium-cli-import-watson-intents         'f309750d-625d-4ec5-bbfb-06886e88f15e' ],
  botium-cli-import-watson-intents      oAuthLinking: { required: false, grantType: 'AUTH_CODE_GRANT' },
  botium-cli-import-watson-intents      voiceType: 'MALE_1',
  botium-cli-import-watson-intents      capabilities: [],
  botium-cli-import-watson-intents      protocolVersion: 'V2',
  botium-cli-import-watson-intents      isDeviceAgent: false },
  botium-cli-import-watson-intents   defaultTimezone: 'Europe/Madrid',
  botium-cli-import-watson-intents   webhook: 
  botium-cli-import-watson-intents    { url: 'XXX',
  botium-cli-import-watson-intents      headers: { '': '' },
  botium-cli-import-watson-intents      available: true,
  botium-cli-import-watson-intents      useForDomains: true,
  botium-cli-import-watson-intents      cloudFunctionsEnabled: false,
  botium-cli-import-watson-intents      cloudFunctionsInitialized: false },
  botium-cli-import-watson-intents   isPrivate: true,
  botium-cli-import-watson-intents   customClassifierMode: 'use.instead',
  botium-cli-import-watson-intents   mlMinConfidence: 0.2,
  botium-cli-import-watson-intents   supportedLanguages: [ 'en' ],
  botium-cli-import-watson-intents   onePlatformApiVersion: 'v1legacy' } +11ms

**Comment by codeforequity-at** [comment]
This seems to be a bug in the Botium CLI - it always exports in the agent default language, which is not the wanted behaviour.

**Comment by codeforequity-at** [comment]
Added to internal backlog
