### ISSUE TITLE
Markdown feature - .md file extension is discovered but then dropped

### ISSUE THREAD

**Issue by nachoizquierdo** [codeforequity-at/botium-core#511]
**Describe the bug**
It seems like when using your new feature to write convos as Markdown files, Markdown extension `.md` is part of the [global file patterns](https://github.com/codeforequity-at/botium-core/blob/master/src/scripting/ScriptingProvider.js#L20), but then the file gets dropped since you are checking for files ending with `.markdown` [when reading it](https://github.com/codeforequity-at/botium-core/blob/master/src/scripting/ScriptingProvider.js#L468).

**To Reproduce**
I am using botium-bindings to run a jest test with a dummy conversation on a `.md` file.
I can see the following lines enabling `DEBUG=botium-ScriptingProvider`:

`botium-ScriptingProvider ReadConvosFromDirectory(./spec/conversations) found filenames: testing-markdown.md +102ms`
`botium-ScriptingProvider ReadScript - dropped file: testing-markdown.md +2ms`

**Expected behavior**
I would expect both `.md` and `.markdown` extensions to be usable.

**Botium Version**
 - Botium Core 1.9.2
 - Botium Bindings 2.0.31

Please, let me know if there is something else I'm missing regarding the Markdown functionality.
Thank you guys for all the hard work!

Ignacio

**Comment by codeforequity-at** [comment]
Thanks, that's a very dumb bug
