### ISSUE TITLE
Can we use conversation_id in assertConvoBegin?

### ISSUE THREAD

**Issue by javadeveloper12** [codeforequity-at/botium-core#517]

**Comment by codeforequity-at** [comment]
Usually, yes. But please be more specific what connector you are using and the use case

**Comment by javadeveloper12** [comment]
I am using Rasa Connector and I want to set some slots(my a/b version)  using assertConvoBegin.Based on my a/b version my convo file will change.


Myassrter.js
const utils = require('util')

module.exports = class MyCustomAsserter {
  constructor (context, caps, globalArgs) {
    this.context = context
    this.caps = caps
    this.globalArgs = globalArgs
    console.log(`MyCustomAsserter constructor, globalArgs: ${utils.inspect(globalArgs)}`)
  }

  assertConvoBegin ({ convo, args, isGlobal }) {
         var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest
        var xmlHttp = new XMLHttpRequest();
    xmlHttp.open( "POST", "https://myrasaurl/"conversation_id+"/execute", false ); // false for synchronous request
    xmlHttp.send( [
    {
        "event": "slot",
        "name": "ab_version",
        "value": "V1",
        "timestamp": 0
    }
] );
 
    return Promise.resolve()
  }

  assertConvoStep ({ convo, convoStep, args, isGlobal, botMsg }) {
    console.log(`MyCustomAsserter assertConvoStep ${convo.header.name}/${convoStep.stepTag}, args: ${utils.inspect(args)}, botMessage: ${botMsg}`)
    return Promise.resolve()
  }

  assertConvoEnd ({ convo, transcript, args, isGlobal }) {
    console.log(`MyCustomAsserter assertConvoEnd ${convo.header.name}, conversation length: ${transcript.steps.length} steps`)
    return Promise.resolve()
  }
}

**Comment by codeforequity-at** [comment]
The assertConvoBegin receives a container parameter as well giving access to the Botium connector data.Should work something like this then:

```
assertConvoBegin ({ convo, args, isGlobal, container }) {
  const conversationId = container.pluginInstance.view.botium.conversationId
  ... do with the conversationId what you want ...
  return Promise.resolve()
}
```

By the way, in this use case a logic hook would be a better match than an asserter - but the asserter will do as well.

**Comment by javadeveloper12** [comment]
Thank you,it is working
