### ISSUE TITLE
com.google.apps.framework.request.BadRequestException when running nlpanalytics with dialogflow

### ISSUE THREAD

**Issue by vovanec** [codeforequity-at/botium-core#521]
**Describe the bug**
I am trying to run intent analysis for my dialogflow project as described in https://medium.com/@floriantreml/tutorial-benchmark-your-chatbot-on-watson-dialogflow-wit-ai-and-more-92885b4fbd48

I was able to successfully import utterances, but when I'm running `botium-cli nlpanalytics` I am getting the following error:

```
  botium-core-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +1ms
  botium-connector-PluginConnectorContainer-helper Botium plugin loaded from /usr/local/lib/node_modules/botium-cli/node_modules/botium-connector-dialogflow/index.js +0ms
  botium-connector-dialogflow Validate called +0ms
  botium-connector-BaseContainer _RunCustomHook onBuild finished +0ms
  botium-connector-dialogflow Build called +1ms
  botium-connector-dialogflow Clean called +10s
  botium-connector-BaseContainer _RunCustomHook onClean finished +10s
  botium-connector-BaseContainer Cleanup rimrafing temp dir /Users/vovan/intent_analysis/botiumwork/intent-test 20200702 191900 sy9Ir +0ms
K-Fold training for fold 1 failed: {"code":3,"message":"com.google.apps.framework.request.BadRequestException: NLUSettings.validate() failed because of the following reasons: Cannot change read-only field NLUSettings.defaultLanguage during an update","details":[]}
```

**Expected behavior**
No errors with benchmark summary.

**Botium Flavour:**
 Botium CLI 
 

**Botium Version**
bash-3.2$ botium-cli -V
0.0.69

**Additional context**
I am using Dialogflow API v2

**Comment by vovanec** [comment]
I cannot see the issue anymore after I added the following lines to the botium.json:

      "DIALOGFLOW_LANGUAGE_CODE": "en",
      "DIALOGFLOW_NLP_LANGUAGE_CODE": "en",

**Comment by codeforequity-at** [comment]
great that you was able to overcome this problem yourself!
