### ISSUE TITLE
"Invalid agent zip. Missing required json file agent.json" error when running nlpanalytics on dialogflow

### ISSUE THREAD

**Issue by vovanec** [codeforequity-at/botium-core#522]
**Describe the bug**
I am trying to run intent analysis for my dialogflow project as described in https://medium.com/@floriantreml/tutorial-benchmark-your-chatbot-on-watson-dialogflow-wit-ai-and-more-92885b4fbd48

I was able to successfully import utterances, but when I'm running botium-cli nlpanalytics I am getting the following error:

```
  botium-connector-PluginConnectorContainer-helper Botium plugin loaded from /usr/local/lib/node_modules/botium-cli/node_modules/botium-connector-dialogflow/index.js +0ms
  botium-connector-dialogflow Validate called +0ms
  botium-connector-BaseContainer _RunCustomHook onBuild finished +0ms
  botium-connector-dialogflow Build called +2ms
  botium-connector-dialogflow-nlp Dialogflow agent created: projects/newagent-cacrnf/BotiumTrainingCopy-hfDNC +0ms
  botium-connector-dialogflow-nlp Dialogflow agent restoring intents: projects/newagent-cacrnf/BotiumTrainingCopy-hfDNC +12ms
  botium-connector-dialogflow Clean called +6s
  botium-connector-BaseContainer _RunCustomHook onClean finished +6s
  botium-connector-BaseContainer Cleanup rimrafing temp dir /Users/vovan/intent_analysis/botiumwork/intent-test 20200702 193303 KOGwz +0ms
K-Fold training for fold 1 failed: {"code":3,"message":"com.google.apps.framework.request.BadRequestException: Invalid agent zip. Missing required json file agent.json","details":[]}
```

**Expected behavior**
No errors, program exits with benchmark summary.

**Botium Flavour**
Botium CLI

**Botium Version**
bash-3.2$ botium-cli -V
0.0.69

**Additional context**
Dialogflow API v2

**Comment by codeforequity-at** [comment]
i had the same problems some weeks ago, when the Botium Dialogflow connector used AdmZip for packaging the agent files - it produced invalid ZIP files. Switched the connector then to JSZip instead, then it worked. this looks to me as if the old version of the dialogflow connector is used - should not be the case, as botium-cli is the latest one, but who knows ... can you please check the version of the botium-connector-dialogflow module in the node_modules folder

**Comment by vovanec** [comment]
```
├─┬ botium-cli@0.0.69
│ ├─┬ botium-asserter-basiclink@0.0.7
│ ├─┬ botium-asserter-watson-toneanalyzer@0.0.1
│ ├─┬ botium-connector-alexa-avs@0.0.8
│ ├─┬ botium-connector-alexa-smapi@0.0.11
│ ├─┬ botium-connector-botkit@0.0.5
│ ├─┬ botium-connector-botkit-websocket@0.2.0
│ ├─┬ botium-connector-botpress@0.0.4
│ ├─┬ botium-connector-dialogflow@0.0.21
│ ├─┬ botium-connector-directline3@0.0.22
│ ├─┬ botium-connector-echo@0.0.7
│ ├─┬ botium-connector-fbwebhook@0.0.3
│ ├─┬ botium-connector-google-assistant@0.0.6
│ ├─┬ botium-connector-koreai-webhook@0.0.2
│ ├─┬ botium-connector-lex@0.0.11
│ ├─┬ botium-connector-luis@0.0.6
│ ├─┬ botium-connector-nlpjs@0.0.2
│ ├─┬ botium-connector-pandorabots@0.0.1
│ ├─┬ botium-connector-qnamaker@0.1.1
│ ├─┬ botium-connector-rasa@0.0.5
│ ├─┬ botium-connector-sapcai@0.0.2
│ ├─┬ botium-connector-watson@0.0.18
│ ├─┬ botium-connector-webdriverio@0.3.2
│ ├─┬ botium-connector-websocket@0.0.3
│ ├─┬ botium-connector-wechat@0.0.1
│ ├─┬ botium-connector-whatsapp@0.0.1
│ ├─┬ botium-connector-witai@0.0.3
│ ├─┬ botium-core@1.9.6
├─┬ botium-connector-dialogflow@0.0.21
├── UNMET PEER DEPENDENCY botium-core@>= 1.9.0
```

**Comment by vovanec** [comment]
Hi @codeforequity-at , do you have any update on this issue?

**Comment by codeforequity-at** [comment]
Yes. The Dialogflow APIs have changed recently. I updated the Botium Connector for Dialogflow. It will be part of the next release.

**Comment by vovanec** [comment]
Hi @codeforequity-at , what's new release date? Is it possible to try fix / patch with current release?

**Comment by codeforequity-at** [comment]
sure. you have to replace the botium-connector-dialogflow module from npm with the master branch from github.

**Comment by codeforequity-at** [comment]
Fixed with latest release
