### ISSUE TITLE
Script Pre-Compiler didn't work with a txt file.

### ISSUE THREAD

**Issue by love2dishtech** [codeforequity-at/botium-core#532]
Hi,

In the wiki documentation [here[(https://botium.atlassian.net/wiki/spaces/BOTIUM/pages/218726414/Composing+in+not+standard+files+with+precompiler), it says that the scripting pre-compilers can work with any type of files and JSON file is just an example. However, I couldn't make it to work with the `txt convo files`.

Looking at the code underneath, it looks like it is designed to only work with the JSON files. Am I missing something?

https://github.com/codeforequity-at/botium-core/blob/cb412e96efc0e1e5713bb48a7696b8e152b81b58/src/scripting/precompilers/Script.js#L18

https://github.com/codeforequity-at/botium-core/blob/cb412e96efc0e1e5713bb48a7696b8e152b81b58/src/scripting/precompilers/index.js#L32

**Comment by codeforequity-at** [comment]
Works for all file types. A "precompiler" is just a piece of code that gets called from Botium when reading the file, no magic involved. Precompiler has to decide itself if it will process the file.

**Comment by love2dishtech** [comment]
Right, that makes absolute sense. Do we have an example documented for that? When I was processing the txt convo file. I replaced the content of the file into a separate txt file with something like this.

`result=scriptData.replaceAll("##MY_KEYWORD##", "MyAppKeywordValue"`

However, when getting back the result, the entire script convo file was interpreted as a single JSON string, not as a new-line parsed txt-convo. I realized it is happening because of the below lines of code.

https://github.com/codeforequity-at/botium-core/blob/cb412e96efc0e1e5713bb48a7696b8e152b81b58/src/scripting/precompilers/index.js#L36

```
const isJson = (json) => {
  if (isStringJson(json)) {
    return json
  } else if (isJsonObject(json)) {
    return JSON.stringify(json)
  }
  return null
}
```

In my particular case, the entire file was now Stringified to a "String" followed by which TXT compiler treated every file as a single string.

**Comment by ujja** [comment]
Its fixed. Will be available with the next release.

Your convo name has to end with '.convo.txt'. Otherwise it wont be processed.

**Comment by love2dishtech** [comment]
That is great. Thanks for the information. Looking for the new release.

**Comment by codeforequity-at** [comment]
Fixed with latest release
