### ISSUE TITLE
Connector plugin name breaking change

### ISSUE THREAD

**Issue by alopix** [codeforequity-at/botium-core#539]
It seems like you introduced a breaking change in v1.8.2 by changing the way connector plugins are being loaded.

The loader forces the prefix `botium-connector-` on the loaded package, which both results in not supporting `@orga/connector-name` as well as complete custom connector package names:
https://github.com/codeforequity-at/botium-core/blob/cb412e96efc0e1e5713bb48a7696b8e152b81b58/src/containers/plugins/index.js#L99

**Comment by ujja** [comment]
Next release should fix this

**Comment by alopix** [comment]
Thank you. Any indication on when the next release will be available?

**Comment by codeforequity-at** [comment]
Fixed with latest release
