### ISSUE TITLE
Allow continuation of tests when bot does not answer one testcase

### ISSUE THREAD

**Issue by jganseman** [codeforequity-at/botium-core#54]
Currently, it seems that when a script runs and the bot does not give an answer to one of the testcases ( i.e. returns "bot says nothing", see https://github.com/codeforequity-at/botium-core/blob/0778f701bd829a04e0924a223be10dcc28d5891b/src/scripting/Convo.js#L64 ), the entire testsuite is stopped . I would actually like the remaining testcases to still be executed.

It would be a nice enhancement if this behaviour could be parameterized somehow. My own effort to write a custom fail(err) handler did not really work out. I would be willing to contribute and submit a patch if someone could point me in the right direction of how to approach this (I must admit I'm not well-versed in javascript nor node.js).

**Comment by codeforequity-at** [comment]
Actually, it should only cancel the conversation under execution. The error handling needs some work though, so it's very well possible that there is a bug somewhere. 
Do you have an example showing the failure ?

**Comment by jganseman** [comment]
Hi! When using IBM Watson, this happens for example with nonsensical input, something like "qsdfyuazebrljhdfz". It does not get classified (or is classified as "irrelevant"), and probably returns no intents in the response message.

In the particular scenario I work with, question-reponse pairs are pretty independent from each other, but they're all one after the other in one big Excel sheet, so only loaded into 1 big conversation. For me, upon an empty response from the bot, it would be better if the conversation continued with the next input from the user (just like it does after an assertion failure). Would it help to put just a `convoStepDone()` after the call to `this.provider.scriptingEvents.fail` ? Or would it be better to try and create separate conversations for each question-response pair in this case?

**Comment by codeforequity-at** [comment]
Is this solved ?
