### ISSUE TITLE
Fatal error when starting botium-cli with a minimal project

### ISSUE THREAD

**Issue by fdw** [codeforequity-at/botium-core#554]
**Describe the bug**
If I start borium with `npx botium-cli run`, I get this error: `ReadScript - an error occurred at 'node_modules/@apidevtools/openapi-schemas/schemas/v3.0/README.md' file: Cannot read property 'children' of null`

**To Reproduce**
1. Start a new project.
2. Install `botium-cli`
3. Run `npx botium-cli init`.
4. Run `botium-cli init`

**Expected behavior**
No error should happen

**Botium Flavour:**
 - Botium CLI

**Botium Version**
 - `botium-cli` `0.0.74`

**Comment by codeforequity-at** [comment]
botium-cli searches for test case files in the current drectory. markdown is a supported format, but the detected file is obviously not a botium file. use the --convos arg to point botium-cli to the test case directory.

**Comment by fdw** [comment]
Ah, I see. Looks like it looks through all subfolders, too, so it also enters `node_modules`.

With the `-C` parameter in a subfolder I can get it to work. Thanks :)
