### ISSUE TITLE
Unable to login to community edition

### ISSUE THREAD

**Issue by abhinav2019** [codeforequity-at/botium-core#557]
i have successfully installing botium community edition

but on clicking on login, its not redirecting me to login page

[
![botium](https://user-images.githubusercontent.com/46926479/91422793-44203300-e875-11ea-9185-3c8d4327b924.PNG)
](url)

i have the license key but how to upload it, there is no option

**Comment by codeforequity-at** [comment]
follow the link to receive your license for the community edition

Abhinav <notifications@github.com> schrieb am Do., 27. Aug. 2020, 11:25:

**Comment by abhinav2019** [comment]
i saw the link but there steps are not mentioned. a attachment is there of  license key .

If you could provide the link here, it will be of great help

**Comment by codeforequity-at** [comment]
place the license.key file in the resources folder and restart tge botium
box service

Abhinav <notifications@github.com> schrieb am Do., 27. Aug. 2020, 15:13:
