### ISSUE TITLE
I don't see Other (Advanced Settings) under technology when registering custom chatbot

### ISSUE THREAD

**Issue by kulasangeles** [codeforequity-at/botium-core#558]
**Describe the bug**
I have created a *.js file under resources but the Other (Advanced Settings) is not showing up. 

**To Reproduce**
1. Install CE Botium Box through docker
2. Add *.js under resources folder
3. Register a new chatbot
4. Validate that there's no Other (Advanced Settings) under technology

**Expected behavior**

**Screenshots and Log files**
![image](https://user-images.githubusercontent.com/69646975/91562076-98292700-e90a-11ea-87e0-257a676b1d6c.png)

**Botium Flavour:**
 - Botium Box 

**Botium Version**
Build Branch: release/2.6.1

**Additional context**
Followed the steps here: https://medium.com/@floriantreml/botium-in-a-nutshell-part-6-e2e-testing-with-botium-box-9bd8acdf5a70

**Comment by codeforequity-at** [comment]
The "Other" option is at the very bottom of this dropdown selector, and it is only visible when the chatbot record is already created
1. register chatbot
2. open the chatbot record, and go to Settings menu - there this option is available
