### ISSUE TITLE
How to automate buttons and dynamic buttons using Botium cli, also what should be the settings in botium.json .attaching the logs which i get from botium 

### ISSUE THREAD

**Issue by testqaprj** [codeforequity-at/botium-core#568]
error sending to bot - WebDriver error on UserSays: element ("//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ','abcdefghijklmnopqrstuvwxyzäöü'),'yes')][last()] | //a[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ','abcdefghijklmnopqrstuvwxyzäöü'),'yes')][last()]") still not existing after 30000ms
my convo file is 
#me
Rerun a Job

#bot
#begin
Ok. Do you find any of the options below relevant to your query? If yes, select an option to help me understand your query better:

#me
BUTTON Rerun a Job

#bot
#begin
Please confirm if you want to retain jobName as *

#me
BUTTON Yes|*

**Comment by codeforequity-at** [comment]
the error message is just what it tells you - that Selenium was not able to find a button or a hyperlink labeled with "yes".

run it with --verbose flag to get more output.

**Comment by testqaprj** [comment]
Hi , 
I tried running in --verbose mode.
error sending to bot - WebDriver error on UserSays: element ("//button[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ','abcdefghijklmnopqrstuvwxyzäöü'),'yes')][last()] | //a[contains(translate(., 'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜ','abcdefghijklmnopqrstuvwxyzäöü'),'yes')][last()]") still not existing after 30000ms
attaching the logs below
user says (cleaned by binary and base64 data and sourceData) {
  botium-core-Convo   "sender": "me",
  botium-core-Convo   "channel": null,
  botium-core-Convo   "not": false,
  botium-core-Convo   "messageText": "Yes",
  botium-core-Convo   "media": null,
  botium-core-Convo   "buttons": [
  botium-core-Convo     {
  botium-core-Convo       "payload": "Yes",
  botium-core-Convo       "text": "Yes"
  botium-core-Convo     }
  botium-core-Convo   ],
  botium-core-Convo   "cards": null,
  botium-core-Convo   "forms": null,
  botium-core-Convo   "attachments": null,
  botium-core-Convo   "asserters": [],
  botium-core-Convo   "userInputs": [
  botium-core-Convo     {
  botium-core-Convo       "name": "BUTTON",
  botium-core-Convo       "args": [
  botium-core-Convo         "Yes",
  botium-core-Convo         "Yes"
  botium-core-Convo       ]
  botium-core-Convo     }
  botium-core-Convo   ],
  botium-core-Convo   "logicHooks": [
  botium-core-Convo     {
  botium-core-Convo       "name": "PAUSE",
  botium-core-Convo       "args": [
  botium-core-Convo         "2000"
  botium-core-Convo       ]
  botium-core-Convo     }
  botium-core-Convo   ]
  botium-core-Convo } +1ms
and in my case i am not able to click on the button named Yes.
First time I am able to click but consecutively I am not able to Click on Yes button.
I tried in convo 
BUTTON Yes|Yes but it could not solve my problem.Please advice me

**Comment by codeforequity-at** [comment]
Maybe something to do with this capability: WEBDRIVERIO_OUTPUT_ELEMENT_BUTTONS_NESTED
Depending on the structure of your DOM.
See https://github.com/codeforequity-at/botium-connector-webdriverio#webdriverio_output_element_buttons-and-webdriverio_output_element_buttons_nested
