### ISSUE TITLE
Fatal error installing botium-cli on Windows 10

### ISSUE THREAD

**Issue by textminer** [codeforequity-at/botium-core#570]
**Describe the bug**
Botium-cli tool can't be installed on Windows 10.

I also install previously node-pre-gyp, and botium-core 1.9.12

**To Reproduce**
npm install -g botium-cli

**Expected behavior**
Botium-cli tool should get installed

**Screenshots and Log files**
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@16.1.8: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/wreck@15.1.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/pinpoint@1.0.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/formula@1.2.0: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/boom@7.4.11: This version has been deprecated and is no longer supported or maintained
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > grpc@1.24.3 install C:\Users\[my user]\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c0524b33\node_modules\grpc
npm ERR! prepareGitDep > node-pre-gyp install --fallback-to-build --library=static_library
npm ERR! prepareGitDep
npm ERR! prepareGitDep [grpc] Success: "C:\Users\[my user]\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c0524b33\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-unknown\grpc_node.node" is installed via remote
npm ERR! prepareGitDep
npm ERR! prepareGitDep > core-js@2.6.11 postinstall C:\Users\[my user]\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c0524b33\node_modules\core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep
npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep
npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
npm ERR! prepareGitDep > https://opencollective.com/core-js
npm ERR! prepareGitDep > https://www.patreon.com/zloirock
npm ERR! prepareGitDep
npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > protobufjs@6.10.1 postinstall C:\Users\[my user]\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c0524b33\node_modules\protobufjs
npm ERR! prepareGitDep > node scripts/postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > actions-on-google-testing@0.4.0 prepare C:\Users\[my user]\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-c0524b33
npm ERR! prepareGitDep > tsc && cp -r ./locales ./dist
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated @types/winston@2.4.4: This is a stub types definition. winston provides its own type definitions, so you do not need this installed.
npm ERR! prepareGitDep npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! prepareGitDep npm WARN deprecated flat@4.1.0: Fixed a prototype pollution security issue in 4.1.0, please upgrade to ^4.1.1 or ^5.0.1.
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep node-pre-gyp WARN Using needle for node-pre-gyp https download
npm ERR! prepareGitDep 'cp' is not recognized as an internal or external command,
npm ERR! prepareGitDep operable program or batch file.
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! errno 1
npm ERR! prepareGitDep npm ERR! actions-on-google-testing@0.4.0 prepare: `tsc && cp -r ./locales ./dist`
npm ERR! prepareGitDep npm ERR! Exit status 1
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the actions-on-google-testing@0.4.0 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     C:\Users\[my user]\AppData\Roaming\npm-cache\_logs\2020-10-07T20_03_55_047Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

npm ERR! A complete log of this run can be found in:

**Botium Version**
 - 0.0.77 and previous ones too

**Additional context**
Using node v.14.12.0
MINGW64 is installed due to Git 

Any help would be appreciated.
Thanks.

**Comment by codeforequity-at** [comment]
i suggest using the docker build of botium cli

textminer <notifications@github.com> schrieb am Mi., 7. Okt. 2020, 22:10:

**Comment by textminer** [comment]
I see. Is there a way that the docker container runs botium-cli on tests outside of it? Or may I need to create a new docker image that contains botium-cli and the tests and botium.json config?
Thanks for the prompt response!

**Comment by codeforequity-at** [comment]
you have to map the local folder to a docker volume, see botium-cli docs

textminer <notifications@github.com> schrieb am Mi., 7. Okt. 2020, 22:20:
