### ISSUE TITLE
Watson connector documentation

### ISSUE THREAD

**Issue by rajath** [codeforequity-at/botium-core#571]
Hi,
This isn't really a bug but I struggled with connecting to Watson since the terminologies have changed in the platform and the doc seems outdated. I did finally manage to connect but a few things I noticed:

* The WATSON_ASSISTANT_VERSION flag is not being recognized by the nlpanalytics command, so I could not use V2
* WORKSPACE ID needs to be substituted by SKILL ID as the workspace concept is no longer used
* A WATSON_URL has to be set to the url shown in the skill api details page (e.g. https://api.us-east.assistant.watson.cloud.ibm.com). This is not mentioned in the docs afaik.

thanks,
Rajath

**Comment by codeforequity-at** [comment]
The Watson V2 API doesn't have the features we need for the NLPanalytics command, that's why it is based on V1 (with workspace id)

**Comment by codeforequity-at** [comment]
> * A WATSON_URL has to be set to the url shown in the skill api details page (e.g. https://api.us-east.assistant.watson.cloud.ibm.com). This is not mentioned in the docs afaik.
> 

Added it to the Github  repo, thanks for mentioning
https://github.com/codeforequity-at/botium-connector-watson/blob/master/README.md
