### ISSUE TITLE
Unable to test Alexa via botium-connector !!!!

### ISSUE THREAD

**Issue by divyakumar95** [codeforequity-at/botium-core#591]
**Describe the bug**
Hi, I am trying to test my alexa device with Botium but I am not able to run any of test commands on my terminal i am facing issue all the time I Run following botium commands -> npx botium-cli run -C ./path/to/.convo.txt  (or) npx botium-cli emulator 

Can u please help me to proceed further !!!!!

**To Reproduce**
npm install botium-cli
npm install botium-connector-alexa-avs  
npx botium-cli init-alexa-avs 
npx botium-cli run -C ./path/to/.convo.txt  (or) npx botium-cli emulator 

**Expected behavior**
Expected to initialize and able to automate voice testing of Alexa

**Screenshots and Log files**
>>issue 1
C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs>npx botium-cli emulator
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v1' is not defined by "exports" in C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\botium-connector-alexa-avs\node_modules\uuid\package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
    at resolveExports (internal/modules/cjs/loader.js:444:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:484:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\botium-connector-alexa-avs\src\avs\AVSSpeechClient.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1015:30) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

#########################################################
>> issue 2

C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs>npx botium-cli run -C ./PATH/TO/.convo.txt

  Botium Test-Suite
    1) "before all" hook for "bank1"

  0 passing (3s)
  1 failing

  1) Botium Test-Suite
       "before all" hook for "bank1":
     Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './v1' is not defined by "exports" in C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\botium-connector-alexa-avs\node_modules\uuid\package.json
      at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
      at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
      at resolveExports (internal/modules/cjs/loader.js:444:36)
      at Function.Module._findPath (internal/modules/cjs/loader.js:484:31)
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
      at Function.Module._load (internal/modules/cjs/loader.js:687:27)
      at Module.require (internal/modules/cjs/loader.js:903:19)
      at require (internal/modules/cjs/helpers.js:74:18)
      at Object.<anonymous> (node_modules\botium-connector-alexa-avs\src\avs\AVSSpeechClient.js:6:16)
      at Module._compile (internal/modules/cjs/loader.js:1015:30)

**Botium Flavour:**
 - Trying with Botium CLI 

**Additional context**

and when i was installing "npm install botium-connector-alexa-avs"
i found some errors while installing
C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win32.c
  win_delay_load_hook.cc
  output.vcxproj -> C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\Release\\liboutput.lib
  binding.cc
  win_delay_load_hook.cc
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(30): error C2660: 'v8::Value::Int32Value': f
unction does not take 0 arguments [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
  c:\users\divyakn\appdata\local\node-gyp\cache\14.15.1\include\node\v8.h(2869): note: see declaration of 'v8::Value::
  Int32Value' (compiling source file ..\src\binding.cc)
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(31): error C2660: 'v8::Value::Int32Value': f
unction does not take 0 arguments [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
  c:\users\divyakn\appdata\local\node-gyp\cache\14.15.1\include\node\v8.h(2869): note: see declaration of 'v8::Value::
  Int32Value' (compiling source file ..\src\binding.cc)
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(32): error C2660: 'v8::Value::Int32Value': f
unction does not take 0 arguments [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
  c:\users\divyakn\appdata\local\node-gyp\cache\14.15.1\include\node\v8.h(2869): note: see declaration of 'v8::Value::
  Int32Value' (compiling source file ..\src\binding.cc)
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(51): error C2660: 'v8::Value::Int32Value': f
unction does not take 0 arguments [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
  c:\users\divyakn\appdata\local\node-gyp\cache\14.15.1\include\node\v8.h(2869): note: see declaration of 'v8::Value::
  Int32Value' (compiling source file ..\src\binding.cc)
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(80): warning C4996: 'Nan::Callback::Call': w
as declared deprecated [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
  c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\nan\nan.h(1742): note: see declaration of 'Nan::Callback::Call'
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(104): error C2065: 'Handle': undeclared iden
tifier [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(104): error C2275: 'v8::Object': illegal use
 of this type as an expression [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
  c:\users\divyakn\appdata\local\node-gyp\cache\14.15.1\include\node\v8.h(3664): note: see declaration of 'v8::Object'
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(104): error C2065: 'target': undeclared iden
tifier [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(104): error C2182: 'Initialize': illegal use
 of type 'void' [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\build\binding.vcxproj]
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(104): error C2448: '`anonymous-namespace'::I
nitialize': function-style initializer appears to be a function definition [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node
_modules\speaker\build\binding.vcxproj]
c:\users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker\src\binding.cc(155): warning C4312: 'type cast': conversion
 from 'int' to 'node::addon_register_func' of greater size [C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker
\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\divyakn\Desktop\Botium\VoiceChannel\alexa-avs\node_modules\speaker
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
###############################
with these errors botium-connector-alexa-avs got installed success status.
###################################

my botium.json looks like this 

"Capabilities": {
      "PROJECTNAME": "Botium Project Alexa AVS",
      "CONTAINERMODE": "alexa-avs",
      "ALEXA_AVS_AVS_CLIENT_ID": "amzn1.application-oa2-client.1xxx",
      "ALEXA_AVS_AVS_CLIENT_SECRET": "xxx",
      "ALEXA_AVS_AVS_REFRESH_TOKEN": "xxx",
      "ALEXA_AVS_AVS_LANGUAGE_CODE": "en-US",
      "ALEXA_AVS_TTS": "AMAZON_POLLY",
      "ALEXA_AVS_TTS_AMAZON_POLLY_REGION": "eu-west-1",
      "ALEXA_AVS_TTS_AMAZON_POLLY_ACCESS_KEY_ID": "xxx",
      "ALEXA_AVS_TTS_AMAZON_POLLY_SECRET_ACCESS_KEY": "xxx",
      "ALEXA_AVS_TTS_AMAZON_POLLY_LANGUAGE_CODE": "en-US",
      "ALEXA_AVS_STT": "GOOGLE_CLOUD_SPEECH",
      "ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_PRIVATE_KEY": "xxx",
      "ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_CLIENT_EMAIL": "xxx",
      "ALEXA_AVS_STT_GOOGLE_CLOUD_SPEECH_LANGUAGE_CODE": "en-US"
    }
 }

**Comment by codeforequity-at** [comment]
this is a bug

**Comment by codeforequity-at** [comment]
Fixed with newest build 0.0.10
https://github.com/codeforequity-at/botium-connector-alexa-avs/commit/f654d7410f02b681165401ae8b99655e00538d1c
