### ISSUE TITLE
Botium-core unable to load custom asserter

### ISSUE THREAD

**Issue by monkfruit123** [codeforequity-at/botium-core#607]
**Describe the bug**
I recently updated the dependencies in my test project. After updating, botium-core is unable to load the custom asserters I had defined. I get the error 

`Error: Failed to fetch ASSERTER1 asserter, no idea how to load ...`

**To Reproduce**
package.json
`"dependencies": {
"botium-connector-dialogflow": "^0.0.25",
"botium-core": "^1.11.0",
"jsonpath": "^1.1.0",
"lodash": "^4.17.20",
"minimist": "^1.2.5",
"mocha": "^8.2.1"}`

botium.json
`{
"botium": {
    "Capabilities": {
        "PROJECTNAME": "my-project",
        "CONTAINERMODE": "dialogflow",
        "DIALOGFLOW_PROJECT_ID": "<google project id>",
        "DIALOGFLOW_CLIENT_EMAIL": "<service credentials email>",
        "DIALOGFLOW_PRIVATE_KEY": "<service credentials private key>",
        "ASSERTERS": [
            {
                "ref": "ASSERTER1",
                "src": "./src/asserter1.js"
            }
        ]
    },
    "Sources": {},
    "Envs": {}
}`

**Expected behavior**
Test case to execute without any error.

**Botium Flavour:**
Botium binding and botium dialogflow connector.

Test cases are run with npm and mocha.

**Botium Version**
 - Indicated in the package.json file

**Comment by monkfruit123** [comment]
Any help would be much appreciated!

**Comment by codeforequity-at** [comment]
Will check this and get back

**Comment by codeforequity-at** [comment]
Actually you found a bug that requires a fix.

**Comment by codeforequity-at** [comment]
Fixed. Will be part of the next release build.

In the meantime, you can install directly from the Github *develop* branch:

    npm install https://github.com/codeforequity-at/botium-core.git#master

**Comment by monkfruit123** [comment]
Thanks for the quick response!
