### ISSUE TITLE
Assert no response

### ISSUE THREAD

**Issue by dadoeyad** [codeforequity-at/botium-core#610]
Hello!

I have a Watson assistance that at some points returns no text responses or any kind of response but changes the context data that I need to assert.
It is designed that way for the user to send as many photos or texts as they want then reply with a "finished" message.

In Botium tests I'm getting `WaitBotSays error Bot did not respond within`
Is there a way to assert no response from the bot but do assert some context data?

Thanks!

**Comment by codeforequity-at** [comment]
Enable the [WATSON_FORCE_INTENT_RESOLUTION](https://github.com/codeforequity-at/botium-connector-watson/blob/master/README.md#watson_force_intent_resolution) capability for forwarding these "empty" Watson responses to Botium scripts

**Comment by dadoeyad** [comment]
Awesome! It worked! Thanks a lot!
