### ISSUE TITLE
Context Variable in a Convo file using Watson.

### ISSUE THREAD

**Issue by rafaelBergamin** [codeforequity-at/botium-core#62]
Hi!

I have a conversation tree that can go to multiple subjects, in Watson we have a context variable that can have the following values:

$product == 'Password Reset'
$product == 'Account'

In my convo files, how can I set this variable to initiate each of this products trees in my tests?

Ex:
....
....
#me 
Hi

#bot
How can i help you to reset your password ?

Thanks in advance.

**Comment by rafaelBergamin** [comment]
Hi, thanks for the reply!

So, how I can control the Watson Workspace to prepare my initial context ?
And other problem, we have context variables beeing set during the user conversation, to determine which path the dialogflow will go.

Is there any way to do this using botium ?

Thanks in advance.

**Comment by codeforequity-at** [comment]
We keep this very simple: create an entity (for example testcases_prepare)
with one instance (for example "testcaseprepare_passwordreset"). In
conversation flow insert a branch activated when this entity found and set
your context there.

While it is currently not possible to manipulate context with botium
itself, existing context values are safely handled by botium - your
conversation flow is safe

Am 22.05.2018 20:42 schrieb "rafaelBergamin" <notifications@github.com>:
