### ISSUE TITLE
Loading Botium plugin botium-connector-appium failed

### ISSUE THREAD

**Issue by santhosh-rao** [codeforequity-at/botium-core#624]
Hi,

I'm trying to run chatbot testcases on a live Android device using Botium via Appium.
Currently i'm facing an issue with installing "botium-connector-appium". NPM returned 404 while ]installing botium-connector-appium. So I wanted to download and install from this repo but it looks like this repo is empty.

Can anyone help me with this setup?
Thanks in advance!

Log:

>botium-cli Using Botium configuration file botium_android.json +0ms
>botium-cli-run command options: {
>botium-cli-run   _: [ 'run' ],
>botium-cli-run   verbose: true,
>botium-cli-run   v: true,
>botium-cli-run   config: 'botium_android.json',
>botium-cli-run   c: 'botium_android.json',
>botium-cli-run   convos: [ 'give_me_a_picture.convo.txt' ],
>botium-cli-run   C: [ 'give_me_a_picture.convo.txt' ],
>botium-cli-run   output: 'spec',
>botium-cli-run   testsuitename: 'Botium Test-Suite',
>botium-cli-run   n: 'Botium Test-Suite',
>botium-cli-run   expandutterances: false,
>botium-cli-run   expandscriptingmemory: false,
>botium-cli-run   timeout: 60,
>botium-cli-run   '$0': 'C:\\Users\\myname\\AppData\\Roaming\\npm\\node_modules\\botium-cli\\bin\\botium-cli.js'
>botium-cli-run } +0ms
>botium-cli-run Mocha Reporter "spec", options: undefined +4ms
>botium-core-BotDriver Loaded Botium configuration files E:\botium_urc\botium.json,E:\botium_test\botium_android.json +0ms
>botium-core-ScriptingProvider ReadConvosFromDirectory(.) found filenames: give_me_a_picture.convo.txt +0ms
>botium-core-ScriptingProvider ReadConvosFromDirectory(.) found convos:
>botium-core-ScriptingProvider  1 give me picture ({ convoDir: '.', filename: 'give_me_a_picture.convo.txt' }): Line 3: #me - Cox | Line 6: #bot - Connectivity* | Line 9: #me - XR15 | Line 12: #bot - Connectivity*
>botium-core-ScriptingProvider Alright! Here are some things I can help you with | Line 16: #me - Setup Remote | Line 19: #bot - I can definitely help with that, just tap the button and I will guide you through the setup +12ms
>botium-core-ScriptingProvider ReadConvosFromDirectory(.) found utterances:
>botium-core-ScriptingProvider  none +4ms
>botium-core-ScriptingProvider ReadConvosFromDirectory(.) found partial convos:
>botium-core-ScriptingProvider  none +3ms
>botium-core-ScriptingProvider ReadConvosFromDirectory(.) scripting memories:
>botium-core-ScriptingProvider  none +5ms
>botium-cli-run ready reading convos (1), expanding convos ... +799ms
>botium-core-ScriptingProvider ExpandConvos - Using utterances expansion mode: all +4ms
>botium-cli-run ready expanding convos and utterances, number of test cases: (1). +67ms
>botium-cli-run adding test case give me picture (from: { convoDir: '.', filename: 'give_me_a_picture.convo.txt' }) +10ms
>
>
>Botium Test-Suite
>botium-core-BotDriver Build - Botium Core Version: 1.11.2 +879ms
>botium-core-BotDriver Build - Capabilites: {
>botium-core-BotDriver   PROJECTNAME: 'WebdriverIO Plugin Sample',
>botium-core-BotDriver   TESTSESSIONNAME: 'Botium Test Session',
>botium-core-BotDriver   TESTCASENAME: 'Botium Test Case',
>botium-core-BotDriver   TEMPDIR: 'botiumwork',
>botium-core-BotDriver   CLEANUPTEMPDIR: true,
>botium-core-BotDriver   WAITFORBOTTIMEOUT: 30000,
>botium-core-BotDriver   SIMULATE_WRITING_SPEED: true,
>botium-core-BotDriver   SIMPLEREST_PING_RETRIES: 6,
>botium-core-BotDriver   SIMPLEREST_PING_TIMEOUT: 10000,
>botium-core-BotDriver   SIMPLEREST_PING_VERB: 'GET',
>botium-core-BotDriver   SIMPLEREST_PING_UPDATE_CONTEXT: true,
>botium-core-BotDriver   SIMPLEREST_STOP_RETRIES: 6,
>botium-core-BotDriver   SIMPLEREST_STOP_TIMEOUT: 10000,
>botium-core-BotDriver   SIMPLEREST_STOP_VERB: 'GET',
>botium-core-BotDriver   SIMPLEREST_START_RETRIES: 6,
>botium-core-BotDriver   SIMPLEREST_START_TIMEOUT: 10000,
>botium-core-BotDriver   SIMPLEREST_START_VERB: 'GET',
>botium-core-BotDriver   SIMPLEREST_POLL_VERB: 'GET',
>botium-core-BotDriver   SIMPLEREST_POLL_INTERVAL: 1000,
>botium-core-BotDriver   SIMPLEREST_POLL_UPDATE_CONTEXT: true,
>botium-core-BotDriver   SIMPLEREST_METHOD: 'POST',
>botium-core-BotDriver   SIMPLEREST_IGNORE_EMPTY: true,
>botium-core-BotDriver   SIMPLEREST_TIMEOUT: 10000,
>botium-core-BotDriver   SIMPLEREST_EXTRA_OPTIONS: {},
>botium-core-BotDriver   SIMPLEREST_STRICT_SSL: true,
>botium-core-BotDriver   SIMPLEREST_INBOUND_UPDATE_CONTEXT: true,
>botium-core-BotDriver   SIMPLEREST_CONTEXT_MERGE_OR_REPLACE: 'MERGE',
>botium-core-BotDriver   SCRIPTING_TXT_EOL: '\n',
>botium-core-BotDriver   SCRIPTING_XLSX_EOL_WRITE: '\r\n',
>botium-core-BotDriver   SCRIPTING_XLSX_HASHEADERS: true,
>botium-core-BotDriver   SCRIPTING_CSV_SKIP_HEADER: true,
>botium-core-BotDriver   SCRIPTING_CSV_QUOTE: '"',
>botium-core-BotDriver   SCRIPTING_CSV_ESCAPE: '"',
>botium-core-BotDriver   SCRIPTING_NORMALIZE_TEXT: true,
>botium-core-BotDriver   SCRIPTING_ENABLE_MEMORY: false,
>botium-core-BotDriver   SCRIPTING_ENABLE_MULTIPLE_ASSERT_ERRORS: false,
>botium-core-BotDriver   SCRIPTING_MATCHING_MODE: 'wildcardIgnoreCase',
>botium-core-BotDriver   SCRIPTING_UTTEXPANSION_MODE: 'all',
>botium-core-BotDriver   SCRIPTING_UTTEXPANSION_RANDOM_COUNT: 1,
>botium-core-BotDriver   SCRIPTING_UTTEXPANSION_NAMING_MODE: 'justLineTag',
>botium-core-BotDriver   SCRIPTING_UTTEXPANSION_NAMING_UTTERANCE_MAX: '16',
>botium-core-BotDriver   SCRIPTING_MEMORYEXPANSION_KEEP_ORIG: false,
>botium-core-BotDriver   ASSERTERS: [],
>botium-core-BotDriver   LOGIC_HOOKS: [],
>botium-core-BotDriver   USER_INPUTS: [],
>botium-core-BotDriver   SECURITY_ALLOW_UNSAFE: true,
>botium-core-BotDriver   CONTAINERMODE: 'appium',
>botium-core-BotDriver   WEBDRIVERIO_OPTIONS: {
>botium-core-BotDriver     capabilities: {
>botium-core-BotDriver       browserName: 'chrome',
>botium-core-BotDriver       platformName: 'Android',
>botium-core-BotDriver       platformVersion: '9',
>botium-core-BotDriver       deviceName: 'beryllium',
>botium-core-BotDriver       automationName: 'UiAutomator1',
>botium-core-BotDriver       appPackage: '<my app package>',
>botium-core-BotDriver       appActivity: 'crc64b4cc8eac7e5070a8.SplashActivity',
>botium-core-BotDriver       noReset: 'true',
>botium-core-BotDriver       newCommandTimeout: '2000'
>botium-core-BotDriver     },
>botium-core-BotDriver     hostname: 'http://127.0.0.1:4723/wd/hub',
>botium-core-BotDriver     port: 80
>botium-core-BotDriver   },
>botium-core-BotDriver   WEBDRIVERIO_URL: '<my chatbot url>',
>botium-core-BotDriver   WEBDRIVERIO_INPUT_ELEMENT: "//input[@class='webchat__send-box-text-box__input']",
>botium-core-BotDriver   WEBDRIVERIO_INPUT_ELEMENT_SENDBUTTON: "//button[@class='css-1ueqw9g webchat__icon-button']",
>botium-core-BotDriver   WEBDRIVERIO_OUTPUT_ELEMENT: "//html/body/div[@id='webchat']",
>botium-core-BotDriver   waitForPrompt: 100,
>botium-core-BotDriver   SIMPLEREST_BODY_TEMPLATE: 'userUtterance={{msg.messageText}}&sender=765757765',
>botium-core-BotDriver   SIMPLEREST_BODY_RAW: true,
>botium-core-BotDriver   SIMPLEREST_HEADERS_TEMPLATE: { 'Content-Type': 'application/x-www-form-urlencoded' },
>botium-core-BotDriver   SIMPLEREST_INIT_CONTEXT: {
>botium-core-BotDriver     conversation_id: 'z0vRUM70iEE.cwA.ZUQ.Ic_RmjJrPM5kmJq-tAtZRHpWRafvK3tew4_p8dzkUxo'
>botium-core-BotDriver   },
>botium-core-BotDriver   SIMPLEREST_CONTEXT_JSONPATH: '$',
>botium-core-BotDriver   SIMPLEREST_RESPONSE_JSONPATH: '$.utterance',
>botium-core-BotDriver   CONFIG: 'botium_android.json'
>botium-core-BotDriver } +7ms
>botium-core-BotDriver Build - Sources : { LOCALPATH: '.', GITPATH: 'git', GITBRANCH: 'master', GITDIR: '.' } +39ms
>botium-core-BotDriver Build - Envs : { IS_BOTIUM_CONTAINER: true } +15ms
>botium-core-BotDriver BotDriver Build error: Error: Loading Botium Plugin failed.
>botium-core-BotDriver Loading Botium plugin from appium failed - Cannot find module 'appium'
>botium-core-BotDriver Require stack:
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\containers\plugins\index.js
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\index.js
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\src\run\index.js
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\bin\botium-cli.js
>botium-core-BotDriver Loading Botium plugin botium-connector-appium failed, try "npm install botium-connector-appium" - Cannot find module 'botium-connector-appium'
>botium-core-BotDriver Require stack:
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\containers\plugins\index.js
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\index.js
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\src\run\index.js
>botium-core-BotDriver - C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\bin\botium-cli.js +117ms
>  1) "before all" hook for "give me picture"
>
>
>0 passing (218ms)
>1 failing
>
>1) Botium Test-Suite
>     "before all" hook for "give me picture":
>   Error: Loading Botium Plugin failed.
>Loading Botium plugin from appium failed - Cannot find module 'appium'
>Require stack:
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\containers\plugins\index.js
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\index.js
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\src\run\index.js
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\bin\botium-cli.js
>Loading Botium plugin botium-connector-appium failed, try "npm install botium-connector-appium" - Cannot find module 'botium-connector-appium'
>Require stack:
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\containers\plugins\index.js
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\index.js
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\src\run\index.js
>- C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\bin\botium-cli.js
>      at tryLoadPlugin (C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\containers\plugins\index.js:133:9)
>      at PluginConnectorContainer.Validate (C:\Users\myname\AppData\Roaming\npm\node_modules\botium-cli\node_modules\botium-core\src\containers\PluginConnectorContainer.js:14:27)
>      at processTicksAndRejections (internal/process/task_queues.js:93:5)
>
>
>
>
# E:\botium_test>npm install botium-connector-appium
>npm ERR! code E404
>npm ERR! 404 Not Found - GET https://registry.npmjs.org/botium-connector-appium - Not found
>npm ERR! 404
>npm ERR! 404  'botium-connector-appium@latest' is not in the npm registry.
>npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
>npm ERR! 404
>npm ERR! 404 Note that you can also install from a
>npm ERR! 404 tarball, folder, http url, or git url.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\myname\AppData\Roaming\npm-cache\_logs\2021-04-23T13_57_43_151Z-debug.log

@codeforequity-at

**Comment by btlucas** [comment]
I think you should take a look at https://github.com/codeforequity-at/botium-connector-webdriverio instead. The [appium repository](https://github.com/codeforequity-at/botium-connector-appium) is empty and what is described there was implemented on the webdriverio connector.
