### ISSUE TITLE
when i do humanification testing in botium box mini edition, Test cases are failing. 

### ISSUE THREAD

**Issue by mauli9530** [codeforequity-at/botium-core#625]
Hi, 

I am trying to do humanification testing in botium box mini edition. but the Test cases are failing. In the failed Test Cases It shows me double character in the Intents Training data. Actually When I check the utterances file, there I don't have any double characters in the training data.

Can someone let me know How should I solve this error?
![Capture](https://user-images.githubusercontent.com/75463711/116646491-d1081880-a93d-11eb-8517-cc078c195e95.PNG)

**Comment by codeforequity-at** [comment]
pls use the botium box forum for botium box questions. this is for botium core only.
