### ISSUE TITLE
Capability "CLEANUPTEMPDIR" = false from botium.json configuration file is not working

### ISSUE THREAD

**Issue by vkotev** [codeforequity-at/botium-core#63]
Hello,
I cannot find any difference between **"CLEANUPTEMPDIR" = true** and **"CLEANUPTEMPDIR" = false**. Both values keep the working directory cleaned up after stopping _Botium_. Could you, please, check and give a feedback on this issue?
![botium json](https://user-images.githubusercontent.com/20876519/40534291-de7f122c-6005-11e8-9bcf-46ab2363f3b1.png)
![botiumwork](https://user-images.githubusercontent.com/20876519/40534292-de9b793a-6005-11e8-9f5c-2c52749e78e9.png)

**Comment by codeforequity-at** [comment]
Closed for long inactivity. If still an issue, please contact on stackoverflow.
