### ISSUE TITLE
Support for web channel

### ISSUE THREAD

**Issue by ajaykumar1452** [codeforequity-at/botium-core#65]
Provide the  implementation for web channel using Microsoft Botframework, like slack and Facebook channel implementation.

**Comment by codeforequity-at** [comment]
Bot Framework can can be targeted with Botium in two ways:

During development, with the "docker" mode, placing your bot framework bot in a docker container (see  [Wiki](https://github.com/codeforequity-at/botium-core/wiki/operation-mode-docker) and the [sample]( https://github.com/codeforequity-at/botium-core/tree/master/samples/botframework)).

Or by using the "directline" connector - easier to setup and access to source code not required:

see [Wiki](https://github.com/codeforequity-at/botium-core/wiki/operation-mode-directline3) and some [sample code](https://github.com/codeforequity-at/botium-connector-directline3)
