### ISSUE TITLE
Load convos from buffer

### ISSUE THREAD

**Issue by lukasonokoleg** [codeforequity-at/botium-core#655]
**Is your feature request related to a problem? Please describe.**
At this moment it seems we can load "convos" - from files. It would be nice to have capability to load convos from buffer (of-course passing convos format. 

**Describe the solution you'd like**
Introducing of new method within
`src/scripting/ScriptingProvider.js -> ReadScriptFromBuffer( convosType, buffer)`

Also this method then could be reused in existing  `ReadScript` method.

Remark: It would be nice if library would expose CONVOS format types. 

**Describe alternatives you've considered**
Well - the only alternative there is - to manage files within runtime.

**Comment by codeforequity-at** [comment]
In the next release there will be a "ReadScriptFromBuffer" method.

    const { ScriptingConstants} = require('botium-core')
    ...
    scriptingProvider.ReadScriptFromBuffer(mybuffer, ScriptingConstants.SCRIPTING_FORMAT_TXT, ScriptingConstants.SCRIPTING_TYPE_CONVO)
