### ISSUE TITLE
EADDRINUSE with botium-connector-botframework when using botium grid

### ISSUE THREAD

**Issue by arnbaksys** [codeforequity-at/botium-core#659]
**Describe the bug**
When using this connector (https://github.com/codeforequity-at/botium-connector-botframework) and botium grid together getting the following error: 
`Error: listen EADDRINUSE: address already in use :::45100`

**To Reproduce**

1. Run ngrok with command: `ngrok http 45100`
2. Put the following config into botium.json 

``` 
{
  "botium": {
    "Capabilities": {
      "PROJECTNAME": "Test",
      "CONTAINERMODE": "botframework",
      "BOTFRAMEWORK_ENDPOINTURL": "https://xxxx/api/messages",
      "BOTFRAMEWORK_SERVICEURL": "https://xxxx.ngrok.io",
      "BOTFRAMEWORK_APP_ID": "xxxx",
      "BOTFRAMEWORK_APP_SECRET": "xxxx",
      "SIMPLEREST_INBOUND_PORT": 45100,
      "SIMPLEREST_INBOUND_ENDPOINT": "/",
      "SIMPLEREST_TIMEOUT": 60000,
      "SIMULATE_WRITING_SPEED": 250,
      "WAITFORBOTTIMEOUT": 30000,
      "SCRIPTING_MATCHING_MODE": "regexp"
    }
  }
}
``` 
3. Run botium grid with: `botium-cli agent`
4. Make a post to URL `localhost:46100/api/build` with body 
```
{
	"Capabilities": {
	}
}
```
5. Repeat step 4 

**Expected behavior**
There should be no errors and botium-connector-botframework should be able to listen for all conversations bot messages on the same server and port which is initiated only once. 

**Screenshots and Log files**

```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::45100
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at Function.listen (C:\Users\UserName\AppData\Roaming\npm\node_modules\botium-connector-botframework\node_modules\express\lib\application.js:618:24)
    at C:\Users\UserName\AppData\Roaming\npm\node_modules\botium-connector-botframework\node_modules\botium-core\src\grid\inbound\proxy.js:61:23
    at new Promise (<anonymous>)
    at startProxy (C:\Users\UserName\AppData\Roaming\npm\node_modules\botium-connector-botframework\node_modules\botium-core\src\grid\inbound\proxy.js:48:10)
    at SimpleRestContainer._buildInbound (C:\Users\UserName\AppData\Roaming\npm\node_modules\botium-connector-botframework\node_modules\botium-core\src\containers\plugins\SimpleRestContainer.js:628:26)
    at SimpleRestContainer.Build (C:\Users\UserName\AppData\Roaming\npm\node_modules\botium-connector-botframework\node_modules\botium-core\src\containers\plugins\SimpleRestContainer.js:77:17)
    at BotiumConnectorBotFramework.Build (C:\Users\UserName\AppData\Roaming\npm\node_modules\botium-connector-botframework\dist\botium-connector-botframework-cjs.js:371:34)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1361:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 45100
}
```

**Botium Flavour:**
 - Botium CLI

**Botium Version**
Using 1.1.0

**Additional context**
Not using direct line API connector as it is a premium channel and each API request generates additional cost.
So that is not an option.

**Comment by codeforequity-at** [comment]
I think the failure message is pretty clear, there is something else listing on the port 45100 - what happens if you just choose another one, like 45101 ?

**Comment by arnbaksys** [comment]
> I think the failure message is pretty clear, there is something else listing on the port 45100 - what happens if you just choose another one, like 45101 ?

Same behaviour:
First slot creation with /api/build request succeeds and returns slot 0.
Second time /api/build is called, botium crashes. As if botium tries to occupy the port again.
So nothing else is listening on the same port except botium once the first slot is created.

**Comment by codeforequity-at** [comment]
ah, now I know what you mean. when using "build", then the endpoint is actually created and listening on this port. you cannot do this two times in parallel.

**Comment by arnbaksys** [comment]
Thank you for good and quick replies!

**Comment by aibiem** [comment]
@codeforequity-at any ETA on this?

**Comment by codeforequity-at** [comment]
This is not a bug, but by design.
The */build* endpoint will occupy this port, and it will be freed with the */clean*/ endpoint. No parallelism possible out-of-the-box.

If you want to have parallelism here, you have to take care for the port allocations yourself, by splitting up the configuration into multiple botium-core-configs with own ngrok channel etc

**Comment by codeforequity-at** [comment]
That's neither a Botium Grid nor a Bot Framework Connector issue.

With the above configuration, Botium Core launches it's inbound endpoint and occupies the given port. You cannot parallelize this.

You should use the [Botium CLI inbound proxy](https://botium-docs.readthedocs.io/en/latest/04_usage/index.html?highlight=inbound#botium-cli-inbound-proxy) instead (*botium-cli inbound-proxy*), with a Redis queue in between. The inbound endpoint is then only launched once, and you can run parallel Botium Core sessions (using **SIMPLEREST_INBOUND_REDISURL** instead of **SIMPLEREST_INBOUND_ENDPOINT** in botium.json).

**Comment by aibiem** [comment]
Thanks. Will try that.

**Comment by arnbaksys** [comment]
Solved.
