### ISSUE TITLE
Botium-cli throwing deprecation warning for uuid

### ISSUE THREAD

**Issue by rajageetha2003** [codeforequity-at/botium-core#680]
**Describe the bug**
(node:59416) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x.

**To Reproduce**
When DIRECTLINE3_GENERATE_USERNAME set true using [
](https://github.com/codeforequity-at/botium-connector-directline3)

**Expected behavior**
Expect to generate uuid and allow to test multiple conversations

**Screenshots and Log files**
(node:59416) DeprecationWarning: Deep requiring like `const uuidv4 = require('uuid/v4');` is deprecated as of uuid@7.x. Please require the top-level module when using the Node.js CommonJS module or use ECMAScript Modules when bundling for the browser. See https://github.com/uuidjs/uuid#deep-requires-now-deprecated for more information.
at wrapBotiumError (/usr/local/lib/node_modules/botium-cli/src/run/index.js:76:12)
      at finish (/usr/local/lib/node_modules/botium-cli/src/run/index.js:205:24)
      at /usr/local/lib/node_modules/botium-cli/src/run/index.js:218:11
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Botium Flavour:**
 - Botium CLI 

**Botium Version**
- latest

**Additional context**

**Comment by codeforequity-at** [comment]
Fixed https://github.com/codeforequity-at/botium-connector-directline3/commit/9cc819f580db0af15fe57bc1062145bf4cd2442f
