### ISSUE TITLE
Generate Test Report

### ISSUE THREAD

**Issue by ram-d** [codeforequity-at/botium-core#685]
Hi,

I am using Jest html reporters currently to generate the test result for my botium tests. When an utterance fails, it generate the info with expected and actual result but it is time consuming as we have to open each failure to view the expected and actual result. Is there an alternate option to generate the report in excel with 'utterance','#me','#bot' ? This will help review the results where the automation is run for more than 500 utterances. 

Thank you!

**Comment by codeforequity-at** [comment]
With botium-cli there is the option to output the test result as CSV file

**Comment by ram-d** [comment]
I tried with this option but I do not see any csv file generated

botium-cli run -C ./spec/convo/convo.xlsx --reporter-options csv

**Comment by codeforequity-at** [comment]
Try it without the --reporter-options switch

    botium-cli run -C ./spec/convo/convo.xlsx csv

**Comment by ram-d** [comment]
I am getting an error with that option

Error: ENOENT: no such file or directory, stat 'csv'
    at Object.statSync (node:fs:1538:3)
    at ScriptingProvider.ReadScriptsFromDirectory (/usr/local/lib/node_modules/botium-cli/node_modules/botium-core/src/scripting/ScriptingProvider.js:440:30)
    at /usr/local/lib/node_modules/botium-cli/src/run/index.js:109:14
    at Array.forEach (<anonymous>)
    at handler (/usr/local/lib/node_modules/botium-cli/src/run/index.js:108:15)
    at Object.builder.handler (/usr/local/lib/node_modules/botium-cli/bin/botium-cli.js:34:7)
    at /usr/local/lib/node_modules/botium-cli/node_modules/yargs/build/index.cjs:1:9052
    at j (/usr/local/lib/node_modules/botium-cli/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/usr/local/lib/node_modules/botium-cli/node_modules/yargs/build/index.cjs:1:9021)
    at M.runCommand (/usr/local/lib/node_modules/botium-cli/node_modules/yargs/build/index.cjs:1:7206) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'csv'
}

**Comment by codeforequity-at** [comment]
botium-cli run -C ./spec/convo/convo.xlsx -- csv

**Comment by ram-d** [comment]
Thanks, @codeforequity-at . It ran with no errors but I do not see any csv file generated under the folder where the test is run. I tried adding file name at the end as below but the result was same. How to provide the filename? 


botium-cli run -C ./spec/convo/convo.xlsx -- csv test.csv

**Comment by ram-d** [comment]
I figured it out. I tried with the below option

botium-cli run -C ./spec/convo/convo.xlsx --output csv >> testresults.csv

However, the output was not in the format I expected. I was expecting me# and bot# to be comma separated but it does not come out that way.

**Comment by codeforequity-at** [comment]
everything else you would have to code yourself
