### ISSUE TITLE
Convos (Excel) with Microsoft Directline3 API not working

### ISSUE THREAD

**Issue by ajaykumar1452** [codeforequity-at/botium-core#70]
Issue: From Excel file i am reading question and answers  and passing it to botiumFluent.js then i am getting exception like bot says nothing that is from convos.js file ,if hard coding question and answers in botiumFluent.js i can able to get response from bot,  i have also changed botium.json to my bot configuration.

![botiumfluent](https://user-images.githubusercontent.com/36725410/41642295-86e9416a-7485-11e8-9304-0efbc74997de.PNG)

![cmd](https://user-images.githubusercontent.com/36725410/41642311-918694ba-7485-11e8-8fe6-1f13aacf8b53.PNG)

**Comment by codeforequity-at** [comment]
Hi, with regards to the other issue you posted #75, can I consider this one to be working now ?

**Comment by codeforequity-at** [comment]
?
