### ISSUE TITLE
Variable used in the utterance file does not work 

### ISSUE THREAD

**Issue by ram-d** [codeforequity-at/botium-core#726]
Hi,

When I assign some values to a variable in botium.json file and use it in the utterance file, it does not work as expected. For example, if I assign a value 'The total is 100' to a variable let's say 'TOTAL_COUNT' in capabilities in botium.json and use it as $TOTAL_COUNT it works fine. However, if I set the value '100' to 'TOTAL_COUNT' in capabilities in botium.json and then use it like 'The total is $TOTAL_COUNT' then it does not work. What causes this issue? I have even set SCRIPTING_MEMORY_MATCHING_MODE to joker but that did not help. Could you help with this issue please?

Thanks,
Ram

**Comment by ram-d** [comment]
Hi Attila,

I am setting the variable (TOTAL_COUNT) in botium json as mentioned below. This is just an example but the value 100 is actually calculated dynamically. My requirement is that, the custom variable changes for each type of a test account, so I need to find the value dynamically from a javascript code and put it in botium.json. If what I am trying is not the right approach, is there an alternative solution to use custom variables in the utterance file? Appreciate your help.

"botium": {
        "Capabilities": {
          "PROJECTNAME": "Test - Chatbot",
          "CONTAINERMODE": "<customConnector.js>",
          "SCRIPTING_MATCHING_MODE": "TEXT_CONTAINS_ANY",
          "SCRIPTING_ENABLE_MEMORY" : true,
          "SCRIPTING_XLSX_SHEETNAMES": "Convos_" + process.env.ENV,
          "SCRIPTING_XLSX_SHEETNAMES_UTTERANCES": "Utterances_" + process.env.ENV,
          "RETRY_USERSAYS_NUMRETRIES": 1,
           "TOTAL_COUNT": 100,
          "BOT_CONFIGURATION": { "label": "All","language": language , "profile": profile, "workspace": workspace},
          "BOT_ACTIONS" : [],
          "BOT_WORKSPACE_ID": xyz123,   
          "BOT_TOKEN":  "test123zz23",
          "BOT_CONTEXT": {
                            "attachData": {},
                            "language": en_US,
                        },
          "BOT_INPUT" : {
            "text": ""
          }
        }
    
    
      }

Thanks,
Ram

**Comment by ujja** [comment]
Talked with the team now.

we can implement this feature, to read variables from botium.json. You can get it with the next version. (In a month or so) Is it acceptable for you?

**Comment by ram-d** [comment]
Thank you, @ujja . Sooner the better. Appreciate you and the team for implementing this feature!!

**Comment by ram-d** [comment]
@ujja , just an FYI, I also tried $cap(MY_CAP) to read Botium capabilities but it does not work as expected. The test always passes no matter what value is present. 

https://botium-docs.readthedocs.io/en/latest/05_botiumscript/index.html#scripting-memory

**Comment by ram-d** [comment]
I tried again with multiple tests. I do see a bug here. 

The following passes the test which is great

#me
The total count is $cap(TOTAL_COUNT)

The below one fails which is great too

The total test count is $cap(TOTAL_COUNT) 

However, the below one has extra spaces but the test passes instead of failing. Could you check this once?

The               total count is $cap(TOTAL_COUNT)

**Comment by ujja** [comment]
It is because we clean up the message before checking.

It can be turned of via SCRIPTING_NORMALIZE_TEXT cap.

**Comment by ram-d** [comment]
Awesome. That helped, Attila! Thank you for your time and help!!

**Comment by ujja** [comment]
Very good. :)
