### ISSUE TITLE
To test multiple Utterances in Microsoft Bot via Directline3 api

### ISSUE THREAD

**Issue by ajaykumar1452** [codeforequity-at/botium-core#75]
hi team,

we have a requirement to test a bot with multiple utterances for a question, we are using SCRIPTING_XLSX_SHEETNAMES_UTTERANCES capability but we could  not achieve it.

**Comment by codeforequity-at** [comment]
can you please post your excel file and your botium configuration (maybe
somehow simplified, remove sensitive data), or send by email to
florian.treml "at" botium.at


2018-06-28 9:20 GMT+02:00 ajaykumar1452 <notifications@github.com>:

**Comment by codeforequity-at** [comment]
The file you sent is exactly as it should be.
Can you please post your Botium script here ? (again, pls remove passwords etc)

**Comment by ajaykumar1452** [comment]
i  have also tried with 
  

driver.BuildFluent()
    .Start()
    .Compile(script, 'SCRIPTING_FORMAT_XSLX')
    .Compile(script, 'SCRIPTING_TYPE_UTTERANCES')

it is giving me Error as:
ERROR:  Error: No compiler found for scriptFormat SCRIPTING_TYPE_UTTERANCES
    at ScriptingProvider.GetCompiler (D:\bottesting\botium-connector-directline3-master\samples\node_modules\botium-core\sr
c\scripting\ScriptingProvider.js:88:11)
    at ScriptingProvider.Compile (D:\bottesting\botium-connector-directline3-master\samples\node_modules\botium-core\src\sc
ripting\ScriptingProvider.js:76:25)
    at err (D:\bottesting\botium-connector-directline3-master\samples\node_modules\botium-core\src\Fluent.js:84:25)
    at Compile.tasks.push (D:\bottesting\botium-connector-directline3-master\samples\node_modules\botium-core\src\Fluent.js
:75:14)
    at async.eachSeries (D:\bottesting\botium-connector-directline3-master\samples\node_modules\botium-core\src\Fluent.js:2
9:9)

**Comment by ajaykumar1452** [comment]
i also tried this way, Botium driver is not responding.

**Comment by codeforequity-at** [comment]
pls post the full script

**Comment by ajaykumar1452** [comment]
const BotDriver = require('botium-core').BotDriver
const Capabilities = require('botium-core/index').Capabilities
const Source = require('botium-core/index').Source
const fs = require('fs')
const XLSX = require('xlsx')
const config = require('./config');

function datenum(v, date1904) {
  if (date1904) v += 1462;
  var epoch = Date.parse(v);
  return (epoch - new Date(Date.UTC(1899, 11, 30))) / (24 * 60 * 60 * 1000);
}
function sheet_from_array_of_arrays(data, opts) {
  var ws = {};
  var range = { s: { c: 10000000, r: 10000000 }, e: { c: 0, r: 0 } };
  for (var R = 0; R != data.length; ++R) {
    for (var C = 0; C != data[R].length; ++C) {
      if (range.s.r > R) range.s.r = R;
      if (range.s.c > C) range.s.c = C;
      if (range.e.r < R) range.e.r = R;
      if (range.e.c < C) range.e.c = C;
      var cell = { v: data[R][C] };
      if (cell.v == null) continue;
      var cell_ref = XLSX.utils.encode_cell({ c: C, r: R });

      if (typeof cell.v === 'number') cell.t = 'n';
      else if (typeof cell.v === 'boolean') cell.t = 'b';
      else if (cell.v instanceof Date) {
        cell.t = 'n'; cell.z = XLSX.SSF._table[14];
        cell.v = datenum(cell.v);
      }
      else cell.t = 's';

      ws[cell_ref] = cell;
    }
  }
  if (range.s.c < 10000000) ws['!ref'] = XLSX.utils.encode_range(range);
  return ws;
}

var data = [];

function assert(actualList, expectedList, usersays, isList) {
  var testCase = []

  if (!isList) {
    assertb(actualList, expectedList, usersays);
  } else {

    for (var key in expectedList) {

      if (!actualList[key].includes(expectedList[key])) {

        console.log("--------------------------")

        console.log(`ERROR: Expected <${expectedList}>, got <${actualList}>`)
        testCase.push(usersays)
        testCase.push(actualList[key])
        testCase.push(expectedList[key])
        testCase.push("FAIL")
        data.push(testCase)

        console.log("--------------------------")

        return false
      }
    }
    console.log("--------------------------")

    console.log(`SUCCESS: Got Expected <${expectedList}>`)
    testCase.push(usersays)
    testCase.push(actualList)
    testCase.push(expectedList)
    testCase.push("PASS")
    data.push(testCase)

    console.log("--------------------------")
    return true
  }
}

function assertb(actual, expected, usersays) {

  var testCase = []
  if (!actual || actual.indexOf(expected) < 0) {
    console.log("--------------------------")

    console.log(`ERROR: Expected <${expected}>, got <${actual}>`)
    testCase.push(usersays)
    testCase.push(actual)
    testCase.push(expected)
    testCase.push("FAIL")
    data.push(testCase)

    console.log("--------------------------")

    return false
  } else {
    console.log("--------------------------")

    console.log(`SUCCESS: Got Expected <${expected}>`)
    testCase.push(usersays)
    testCase.push(actual)
    testCase.push(expected)
    testCase.push("PASS")
    data.push(testCase)

    console.log("--------------------------")
    return true
  }
}

function fail(err) {
  console.log(`ERROR: <${err}>`)
}

//reading a folder 
//var baseFolder = "D:/bottesting/botium-connector-directline3-master/samples/TestData"
//var resultsFolder = "D:/bottesting/botium-connector-directline3-master/samples/TestResults"

var baseFolder = config.DIR.basedir
var resultsFolder = config.DIR.resultsdir
                              
                
var fileList = []

fs.readdirSync(baseFolder).forEach(file => {

  fileList.push(file)
})

var index = 0

var readNextFile = function (index) {
  if(fileList.length>0){
 

data=[]
var ws_name = "IAA TestCases";
var header = ["USER SAYS", "BOT SAYS", "EXPECTED", "TEST STATUS"]
data.push(header)

function Workbook() {
  if (!(this instanceof Workbook)) return new Workbook();
  this.SheetNames = [];
  this.Sheets = {};
}


  file = fileList[index]

  console.log("Testing file:" + file)
  var testData = baseFolder + "/" + file
  var testResults = resultsFolder + "/" + file
  const script = fs.readFileSync(testData)
  
  const driver = new BotDriver()
  driver.BuildFluent()
    .Start()
    .Compile(script, 'SCRIPTING_FORMAT_XSLX')
    .Compile(script, 'SCRIPTING_FORMAT_XSLX','SCRIPTING_XLSX_SHEETNAMES_UTTERANCES')
    .RunScripts(assert, fail)
    .Exec()
    .then(() => {

      var wb = new Workbook(), ws = sheet_from_array_of_arrays(data);
      wb.SheetNames.push(ws_name);
      wb.Sheets[ws_name] = ws;
      XLSX.writeFile(wb, testResults);
      index++
      if (fileList.length > index) {
        readNextFile(index);
      }
    }).catch((err) => {
      console.log('ERROR: ', err)
      
       index++
      if (fileList.length > index) {
        readNextFile(index);
      }

    })
  }else{
    console.log("No Test Data Found")
  }
}

readNextFile(index)

**Comment by codeforequity-at** [comment]
Instead of:
`.Compile(script, 'SCRIPTING_FORMAT_XSLX','SCRIPTING_XLSX_SHEETNAMES_UTTERANCES')`

it should be

`.Compile(script, 'SCRIPTING_FORMAT_XSLX','SCRIPTING_TYPE_UTTERANCES')`

**Comment by ajaykumar1452** [comment]
thanks  it works
