### ISSUE TITLE
Error running Dialogflow utterances sample - Insufficient tokens for quota

### ISSUE THREAD

**Issue by edash** [codeforequity-at/botium-core#79]
I tried running the Dialogflow utterances sample, leaving the code unchanged except for adding .setCapability(Capabilities.CLEANUPTEMPDIR, false) to the driver. I didn't get any output.

I managed to get debugging working and it shows this error:

ERROR:  Error: jokes.get/jokes.feedback.bad/Line 12: error sending to bot Error: Cannot send message to dialogflow container: { Error: Insufficient tokens for quota 'dialogflow.googleapis.com/StandardTierTextQueryOperations' aOperations' and limit 'StandardTierTextQueryOperationsPerMinutePerProject' of service 'dialogflow.googleapim' f cnmerojes.com' for consumer 'project_number:552878414608'.

To me it suggests that the quota is too low to handle the volume of requests sent to the bot. Is it possible to increase the quota, or for me to add something to throttle the rate of requests?

Many thanks

**Comment by codeforequity-at** [comment]
The problem here is that the sample is connecting to my personal google project developer account, where a pretty low quota is in place. You will have to create your own google project and dialogflow workspace and connect the sample code.

**Comment by edash** [comment]
Ok thanks.
