### ISSUE TITLE
Extend Dialogflow connector to support context/session/language

### ISSUE THREAD

**Issue by raniachaibi** [codeforequity-at/botium-core#80]
I need to test a chatboat application similar to google assistant. When we send request from our botium, we're sending a simple AIRequest object while in the API.API library we can set multiple parameters like the Context, Lang, Session etc... is that something that we can do with Botium ?

**Comment by codeforequity-at** [comment]
Currently, this is not possible, but it definitly makes sense and will be included in one of the upcoming builds.

**Comment by raniachaibi** [comment]
Should this be integrated in the botium.json file ?

**Comment by raniachaibi** [comment]
How can i modify the DIALOGFLOW_INPUT_CONTEXT_LIFESPAN according to what the test requires?
in some cases I need to set it to 1 and in other cases i need to set it to other values, so i can not run tests together. Can i modify it at the beginning of each test case for example?

**Comment by codeforequity-at** [comment]
I know what you mean - I think you would need some ugly hack currently: getting a reference to the container object and modifiying the capability before running a test case. There is clearly room for improvement here, maybe introducing some kind of hook to make such things possible.

**Comment by frankgerhardt** [comment]
Good support for DialogFlow and Google Assistant is the first thing I look for, after Facebook Messenger. 

Please update the docs and put a release plan with upcoming features somewhere so that we can see what you will do in the future.

**Comment by codeforequity-at** [comment]
@frankgerhardt thanks for the feedback. we are currently working on making the development process more transparent and planable. Are there any special features you want to see in Botium ?

**Comment by frankgerhardt** [comment]
A screencast would certainly be convincing. Just show tests running and walk through the examples. 
Without a video I have to do this myself only to evaluate it.

**Comment by arunb0405** [comment]
Can we manage to pass the Session_Id or a test user_Id and password in one of the capabilities, will this be provided as enhancement?

**Comment by codeforequity-at** [comment]
discussion moved to #88
