### ISSUE TITLE
Make convo files lookup more stable (looking for convos in the wrong places)

### ISSUE THREAD

**Issue by edwardlee** [codeforequity-at/botium-core#84]
_Realized this was a mistake on my part but still a bug_

Running `botium-cli emulator browser` or `botium-cli run` outputs
> Error: EPERM: operation not permitted, scandir 'C:\Users\ELee\AppData\Local\Application Data'

At other times, the error would result from trying to scan my Recycling Bin.

I noticed though that my convos files were stored away in a different directory! In addition, I hadn't set up my BOTIUM_CONVOS environment variable. So I played around with the `cd` command, and found a pattern: whenever I was in a directory that contained a restricted system subdirectory, this error would present itself (For example, the "Application Data" was a subdirectory of the directory from which I ran the command, C:\Users\ELee). If there was no such restricted subdirectory (for example if I was in the directory C:\inetpub), the command will complete, but it would just show `0 passing`.

So a suggestion I have would be to
- do a "breadth-first" search instead of a "depth-first" search, because it's more likely that the convos files are located just 1 folder away, or
- if no convos files are found in the current directory, output a fun error message such as
> I'm "speechless"... convos files not found

**Comment by codeforequity-at** [comment]
Agree, your suggestions definitly make sense - a full directory walk-down is a bad idea (at least it should it just should ignore unreadable content).
