### ISSUE TITLE
Chatbot not built in browser emulator

### ISSUE THREAD

**Issue by supereduardus** [codeforequity-at/botium-core#85]
Clicking New Conversation in the browser emulator produces `Error restarting chatbot {}`.

In my command prompt, the full error message is
![image](https://user-images.githubusercontent.com/7280721/42654266-b11ddc02-85dd-11e8-8db9-d1ab1df02a05.png)

Running `#EXIT` confirms this error, as it maintains that something is "not built".

Incredulously, I run into no errors when running the console version of the emulator, even when entering `#SAVE` or `#EXIT`.

**Comment by codeforequity-at** [comment]
Please get the latest botium-cli version. There are some updated on the Dialogflow connector which fix this issue (it has been moved to a separate Botium plugin, out of the core).

**Comment by supereduardus** [comment]
Beautiful. 0.0.16 works like a charm.
