### ISSUE TITLE
How to validate using regex?

### ISSUE THREAD

**Issue by Endeavour-BRM** [codeforequity-at/botium-core#86]
When the bot response is 

"Your hotel is booked for 2nd July for 2 persons"

In the above response the date changes based on user input. So want to make sure that the above reponse is validated using regex such as "Your hotel is booked for *** **** for 2 persons".

Is there any feature in botium which helps to accomplish this. Please help.

**Comment by codeforequity-at** [comment]
Pls set the capability "SCRIPTING_MATCHING_MODE" to "regexp" and the validation will use regular expressions. So this regexp should work in your case:

```
...
#bot
Your hotel is booked for .* for [0-9] persons
...
```

**Comment by Endeavour-BRM** [comment]
@codeforequity-at That worked. Thanks a lot for the quick response. Closing it.
