### ISSUE TITLE
Need Help: I need to echo the .UserSaysText value in a "console.log"

### ISSUE THREAD

**Issue by karinpstevenson** [codeforequity-at/botium-core#89]
I'm grass-green when it comes to Botium scripting, so I apologize if this is a really stupid question:

I have a special use case where I just need to capture the user input and the response from the Watson bot to my questions (not even check if they are matching anything). 

The problem I've been blocked by is that I don't seem to be able to put the value from .UserSaysText into a console.log statement so I can see both the input and the resulting response in a log file. That complete log will be reviewed by subject matter experts after the fact to see if the bot responded correctly.

I tried a number of things but all end in syntax errors. Could you please help me figure out how to do this? And is there some way to do something like this without having to have the input text twice in the string (I know that the following doesn't work, it's just to demonstrate what I need to do):

     .UserSaysText(('Hi there Botsy') => console.log(.UserSaysText))
     .WaitBotSaysText((text) => console.log(text))

Thanks a ton in advance!
Karin

**Comment by codeforequity-at** [comment]
I think you have to add an additional function to the fluent interface, like this:

```
const fluent = driver.BuildFluent()
fluent.UserSaysTextLog = (t) => { console.log(t); return fluent.UserSaysText(t); }
  
fluent.Start()
  .UserSaysTextLog('start')
  .WaitBotSaysText(console.log)
  .UserSaysTextLog('turn on the lights please')
```

**Comment by codeforequity-at** [comment]
Or another option would be to do something like [this](https://github.com/codeforequity-at/botium-core/blob/master/samples/rasa/botiumFluent.js) in the newest Botium sample.

**Comment by karinpstevenson** [comment]
Perfect solutions, all of them, particularly the last one! 

Thank you so very much for your help. Your assistance is so very much appreciated. 

-- Karin
